/* V3.6 / single shared state for full wizard, quick proposal and marketing selections. */
(() => {
'use strict';
const C=window.BARSYS,Q=window.BarsysQuote;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<svg class="icon" aria-hidden="true"><use href="#i-${n}"/></svg>`;
const money=n=>n===null?'To be quoted':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2,minimumFractionDigits:2}).format(n);
const dollars=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const eventTypes=[{id:'team',name:'Team happy hour',icon:'users'},{id:'client',name:'Client event',icon:'glass'},{id:'celebration',name:'Company celebration',icon:'spark'},{id:'recruiting',name:'Recruiting event',icon:'users'},{id:'executive',name:'Executive event',icon:'glass'},{id:'exploring',name:'Just exploring',icon:'calendar'},{id:'birthday',name:'Birthday party',icon:'spark'},{id:'engagement',name:'Engagement party',icon:'glass'},{id:'venue',name:'Venue event',icon:'pin'},{id:'other',name:'Another occasion',icon:'calendar'}];
const steps=['Your event','Your experience','Your drinks','Add-ons','Review & request'];
const blankDetails=()=>({name:'',email:'',company:'',phone:'',date:'',startTime:'',timezone:'America/New_York',city:'New York',region:'NY',venue:'',venueType:'office',budget:'',restrictions:'',notes:'',venueApproval:'not-checked',coi:'unsure',glassware:'discuss',contractEntity:'',marketingInterest:'no',photoPreference:'discuss'});
const defaults=()=>({type:'team',guests:C.defaultGuests,tier:'signature',menus:[],menuMode:'recommend',addons:{},enhancements:[],program:'single',frequency:'exploring',commitment:'exploring',billing:'exploring',beverage:'mixed',serviceHours:2,details:blankDetails()});
let state=defaults(),currentStep=0,complete=false,toastTimer,lastDialogFocus=null,menuQuery='',menuZero=false;
const eventName=()=>eventTypes.find(e=>e.id===state.type)?.name||'Event';
const menuNames=()=>state.menus.map(id=>C.menus.find(m=>m.id===id)?.name).filter(Boolean);
const menuLabel=()=>[menuNames().join(', '),state.menuMode==='recommend'?'Team recommendation requested':''].filter(Boolean).join(' / ')||'Team recommendation';
const estimate=()=>Q.calculate(state,C);
const corporate=()=>['team','client','celebration','recruiting','executive'].includes(state.type);
const todayISO=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);};
const friendlyDate=()=>state.details.date?new Date(`${state.details.date}T12:00:00`).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric'}):'Date to be decided';
const serviceLabel=()=>state.serviceHours===null?'Duration to be decided':`${state.serviceHours} hours requested`;
const motion=()=>document.documentElement.dataset.motion!=='off';
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
function saveDraft(){window.BarsysPrivacy?.saveDraft(state);}
function loadDraft(){try{const x=window.BarsysPrivacy?.loadDraft();if(!x||x.version!==3)return;if(eventTypes.some(t=>t.id===x.type))state.type=x.type;if(Number.isInteger(x.guests)&&x.guests>=1&&x.guests<=10000)state.guests=x.guests;if(Object.hasOwn(C.packages,x.tier))state.tier=x.tier;if(Array.isArray(x.menus))state.menus=[...new Set(x.menus)].filter(id=>C.menus.some(m=>m.id===id));state.menuMode=['choose','recommend'].includes(x.menuMode)?x.menuMode:state.menus.length?'choose':'recommend';for(const a of C.addons){const v=x.addons?.[a.id];if(v)state.addons[a.id]={quantity:Q.quantity(a,x),variant:a.variants?.some(t=>t[0]===v.variant)?v.variant:a.variants?.[0]?.[0]||''};}for(const k of ['program','frequency','commitment','billing','beverage'])if(validOption(k,x[k]))state[k]=x[k];if(x.serviceHours===null||Number.isFinite(x.serviceHours)&&x.serviceHours>=1&&x.serviceHours<=8)state.serviceHours=x.serviceHours;}catch(_){}}
const optionSets={program:['single','recurring'],frequency:['monthly','twice-monthly','quarterly','exploring'],commitment:['3-months','6-months','12-months','exploring'],billing:['monthly','quarterly','annual','exploring'],beverage:['mixed','zero','recommend']};
function validOption(key,value){return optionSets[key]?.includes(value);}
function syncGuests(skip){$$('[data-guest-input]').forEach(el=>{if(el!==skip)el.value=state.guests;});}
function commit(){saveDraft();updateSummary();updateMenuSelections();}
function setGuests(n,source=null){if(!Number.isInteger(n)||n<1||n>C.quoteRules.maxInquiryGuests)return false;state.guests=n;syncGuests(source);commit();refreshAddonHosts();return true;}
function availableMenu(m){return Q.menuAvailable(m.id,state.tier,C);}
function refreshPackageMenus(){renderFeaturedMenus();updateMenuGrid();if($('#menus-dialog').open)renderDialog();}
function setTier(t){if(!Object.hasOwn(C.packages,t))return;state.tier=t;refreshPackageMenus();commit();refreshAddonHosts();if(estimate().unavailableMenus.length)toast('Some retained preferences are outside this package. Review them in menu choices.');if(estimate().menuOverflow)toast('Your menu choices were kept. Review the extra mixlist request for this package.');}
function setDetails(patch){for(const [k,v] of Object.entries(patch))if(Object.hasOwn(state.details,k)&&typeof v==='string')state.details[k]=v.slice(0,['notes','restrictions'].includes(k)?2000:254);updateSummary();}
function setOption(k,v){if(!validOption(k,v))return;state[k]=v;commit();}
function setHours(value){const n=value===''||value===null?null:Number(value);if(n!==null&&(!Number.isInteger(n)||n<1||n>8))return;state.serviceHours=n;state.addons['extra-hours']={quantity:Math.max(0,(n||2)-2),variant:''};commit();refreshAddonHosts();}
function setAddon(id,n,variant){const a=C.addons.find(x=>x.id===id);if(!a)return;const prev=state.addons[id]||{};state.addons[id]={quantity:Math.max(0,Math.min(a.maxQuantity,Math.trunc(Number(n)||0))),variant:a.variants?.some(v=>v[0]===variant)?variant:prev.variant||a.variants?.[0]?.[0]||''};if(id==='extra-hours')state.serviceHours=2+state.addons[id].quantity;commit();}
function refreshAddonHosts(){const active=document.activeElement;const marker=active?.dataset?.addon||active?.dataset?.addonVariant;const scope=active?.closest('#step-content,#quick-content');const delta=active?.dataset?.delta;$$('[data-addon-host]').forEach(host=>host.innerHTML=addonsMarkup(host.closest('#quick-planner')?'quick':'detail'));if(marker&&scope)$(active.hasAttribute('data-addon-variant')?`[data-addon-variant="${marker}"]`:`[data-addon="${marker}"]${delta?`[data-delta="${delta}"]`:''}`,scope)?.focus({preventScroll:true});}
function toggleMenu(id){const m=C.menus.find(x=>x.id===id);if(!m)return false;if(!state.menus.includes(id)&&!availableMenu(m)){toast('This collection is not available with '+C.packages[state.tier].name+'. Choose another package to explore it.');return false;}if(state.menus.includes(id))state.menus=state.menus.filter(x=>x!==id);else {if(state.menus.length>=estimate().menuLimit){toast('Included slots are full. Request an additional mixlist in Add-ons, or remove a collection.');return false;}state.menus.push(id);}state.menuMode=state.menus.length?'choose':'recommend';commit();if($('#menus-dialog').open)renderDialog();return true;}
function extraMenuRequest(){setAddon('extra-mixlists',Q.quantity(C.addons.find(a=>a.id==='extra-mixlists'),state)+1);toast('One extra collection slot requested. Its price will be quoted separately.');renderStep(false);}
function priceMarkup(){const t=estimate(),p=C.packages[state.tier];return `<div class="price-line"><span>${esc(p.name)} / ${state.guests} guests${t.eligible?` &times; ${dollars(p.rate)}`:''}</span><strong>${t.base===null?'Custom quote':money(t.base)}</strong></div>${t.priced.map(l=>`<div class="price-line"><span>${esc(l.name)}${l.quantity>1?' &times; '+l.quantity:''}</span><strong>${money(l.total)}</strong></div>`).join('')}${t.scopeCosts.length?`<div class="scope-costs"><span class="pending-title">EVENT SCOPE TO CONFIRM</span>${t.scopeCosts.map(l=>`<div class="price-line"><span>${esc(l.name)}</span><span>${l.status==='priced'?money(l.total):esc(l.label)}</span></div>`).join('')}</div>`:''}<div class="price-line tax-unconfirmed"><span>Tax</span><span>To be confirmed</span></div>${t.pending.length?`<div class="pending-quotes"><span class="pending-title">${t.pending.length} REQUEST${t.pending.length===1?'':'S'} TO QUOTE</span>${t.pending.map(l=>`<div class="price-line"><span>${esc(l.name)}${l.quantity>1?' &times; '+l.quantity:''}</span><span>Separate quote</span></div>`).join('')}</div>`:''}`;}
function estimateNote(){const t=estimate();return [t.subtotal===null?'Custom quote required.':'Package and explicitly priced items only, before tax.',t.pending.length?'Unpriced requests are NOT included in the subtotal.':'','Delivery, access and glassware scope are confirmed separately; see the breakdown.',state.program==='recurring'?'Single-event baseline; recurring terms are not priced.':'',...t.reasons.filter(r=>!r.startsWith('Recurring')),'Nothing is booked or sent.'].filter(Boolean).join(' ');}
function updateSummary(){const t=estimate(),p=C.packages[state.tier];$$('[data-hours]').forEach(el=>{if(el!==document.activeElement)el.value=state.serviceHours===null?'':String(state.serviceHours);});$('#summary-details').innerHTML=[['users',`${eventName()} / ${state.guests} guests`],['glass',p.name],['clock',serviceLabel()],['calendar',friendlyDate()+(state.details.startTime?' / '+state.details.startTime+' ET':'')],['pin',[state.details.city,state.details.region].filter(Boolean).join(', ')],['leaf',menuLabel()]].map(([i,v])=>`<div class="summary-row">${icon(i)}<span>${esc(v)}</span></div>`).join('');$('#price-breakdown').innerHTML=priceMarkup();$('#estimate-total').textContent=t.subtotal===null?'Custom quote':money(t.subtotal);$('#mobile-estimate').textContent=t.subtotal===null?'Custom quote':money(t.subtotal);$('#estimate-note').textContent=estimateNote();$$('[data-package-subtotal]').forEach(el=>el.textContent=t.eligible?dollars(C.packages[el.dataset.packageSubtotal].rate*state.guests):'Custom quote');$$('[data-guest-count]').forEach(el=>el.textContent=state.guests);$$('[data-select-package]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.selectPackage===state.tier)));$$('.package-card').forEach(el=>el.classList.toggle('is-selected',el.classList.contains(state.tier)));document.dispatchEvent(new CustomEvent('barsys:state'));}
function updateMenuSelections(){const t=estimate();if(C.menuPolicy?.published)$$('[data-open-menus]').forEach(b=>b.textContent='Explore '+C.menus.filter(availableMenu).length+' '+C.packages[state.tier].name+' collections');$$('[data-select-menu]').forEach(b=>{const on=state.menus.includes(b.dataset.selectMenu);b.setAttribute('aria-pressed',String(on));if(b.closest('.menu-card-footer'))b.innerHTML=`${on?'Added to your event':'Add to my event'}${icon(on?'check':'plus')}`;if(b.classList.contains('wm-select'))b.innerHTML=on?`${icon('check')} Selected`:`${icon('plus')} Select`;});$$('.selection-count').forEach(el=>el.textContent=`${state.menus.length} selected / ${t.includedMenus} included${t.menuLimit>t.includedMenus?' + '+(t.menuLimit-t.includedMenus)+' extra requested':''}`);$('#dialog-selected-count').textContent=`${state.menus.length} / ${t.menuLimit} slots`;$('#menu-dialog-help').textContent=`${t.includedMenus} included with ${C.packages[state.tier].name}. ${t.menuLimit-t.includedMenus} extra requested. Final menu and any extra cost are confirmed by the team.`;const recommend=$('[name="menu-mode"]');if(recommend)recommend.checked=state.menuMode==='recommend';}
function field(key,label,{type='text',required=false,wide=false,placeholder=''}={}){return `<div class="field ${wide?'field-full':''}"><label for="detail-${key}">${label}${required?'':' <small>Optional</small>'}</label><input id="detail-${key}" name="${key}" ${({name:'name',email:'email',phone:'tel',company:'organization',city:'address-level2'}[key])?`autocomplete="${({name:'name',email:'email',phone:'tel',company:'organization',city:'address-level2'}[key])}"`:''} data-field="${key}" type="${type}" value="${esc(state.details[key])}" ${required?'required':''} ${type==='date'?`min="${todayISO()}"`:''} ${type==='number'?'min="0" step="1"':''} maxlength="254" placeholder="${esc(placeholder)}"/></div>`;}
function selectDetail(key,label,options){return `<div class="field"><label for="detail-${key}">${label}</label><select id="detail-${key}" data-field="${key}">${options.map(([id,name])=>`<option value="${id}" ${state.details[key]===id?'selected':''}>${esc(name)}</option>`).join('')}</select></div>`;}
function optionSelect(key,label,options){return `<div class="field"><label for="plan-${key}">${label}</label><select id="plan-${key}" data-option="${key}">${options.map(([id,name])=>`<option value="${id}" ${state[key]===id?'selected':''}>${name}</option>`).join('')}</select></div>`;}
function hoursMarkup(){return `<div class="field"><label for="service-hours">Requested service time</label><select id="service-hours" data-hours><option value="" ${state.serviceHours===null?'selected':''}>Not sure yet</option>${[1,2,3,4,5,6,7,8].map(n=>`<option value="${n}" ${state.serviceHours===n?'selected':''}>${n} hours${n===2?' / package baseline':n>2?' / extra time quoted separately':' / custom scope'}</option>`).join('')}</select><small class="field-hint">Extra time is a request, not a confirmed booking.</small></div>`;}
function addonsMarkup(prefix='detail'){return `${window.BarsysReadiness.glasswareMarkup(state,prefix)}<div class="addon-grid">${C.addons.map((a,i)=>{const l=Q.line(a,state);return `<article class="addon-card ${l.selected?'is-added':''} ${l.status==='included'?'is-included':''}" data-addon-card="${a.id}"><div class="addon-top"><span class="addon-icon">${icon(a.icon)}</span><span class="addon-kicker">${l.status==='included'?'IN YOUR PACKAGE':String(i+1).padStart(2,'0')+' / OPTIONAL'}</span></div><h4>${esc(a.name)}</h4><p>${esc(l.status==='included'?a.includedNotes[state.tier]:a.description)}</p>${a.variants?`<label class="addon-variant"><span class="sr-only">${esc(a.name)} preference</span><select data-addon-variant="${a.id}" ${l.status==='included'?'disabled':''}>${a.variants.map(([id,n])=>`<option value="${id}" ${l.variant===id?'selected':''}>${esc(n)}</option>`).join('')}</select></label>`:''}<div class="addon-bottom"><div class="addon-price"><strong>${l.status==='included'?'Included':l.status==='priced'?money(l.unitPrice):'Quoted separately'}</strong><span>${l.status==='included'?'No additional charge':esc(a.unitLabel)}</span>${l.selected&&l.status==='priced'?`<em>${money(l.total)} for your event</em>`:''}</div>${l.status==='included'?`<span class="included-tick">${icon('check')}</span>`:a.maxQuantity>1?`<div class="addon-counter"><button type="button" data-addon="${a.id}" data-delta="-1" ${l.quantity===0?'disabled':''} aria-label="Remove one ${esc(a.name)}">${icon('minus')}</button><output aria-label="${esc(a.name)} quantity">${l.quantity}</output><button type="button" data-addon="${a.id}" data-delta="1" ${l.quantity===a.maxQuantity?'disabled':''} aria-label="Add one ${esc(a.name)}">${icon('plus')}</button></div>`:`<button type="button" class="addon-add" data-addon="${a.id}" aria-pressed="${l.selected}">${icon(l.selected?'check':'plus')}${l.selected?'Added':'Add'}</button>`}</div></article>`;}).join('')}</div>`;}
function menuCard(m){return `<article class="wizard-menu-card"><div class="wm-art" data-photo-frame>${m.image?`<img loading="lazy" data-image="${m.image}" alt="${esc(m.name)} collection artwork" width="400" height="400"/>`:''}<span class="wm-placeholder">BARSYS<br/>MIXLIST</span><span class="wm-type">${m.zeroProof?'ZERO PROOF':'COCKTAILS'}</span></div><div class="wm-body"><h4>${esc(m.name)}</h4><p>${m.recipes} recipes</p><div class="wm-actions">${m.image?`<button type="button" class="wm-details" data-preview-menu="${m.id}">View drinks</button>`:'<span></span>'}<button type="button" class="wm-select" data-select-menu="${m.id}" aria-pressed="${state.menus.includes(m.id)}">${icon(state.menus.includes(m.id)?'check':'plus')}${state.menus.includes(m.id)?'Selected':'Select'}</button></div></div></article>`;}
function menuMarkup(){const visible=C.menus.filter(m=>availableMenu(m)&&(!menuZero||m.zeroProof)&&`${m.name} ${m.description}`.toLowerCase().includes(menuQuery));const retained=state.menus.filter(id=>!Q.menuAvailable(id,state.tier,C));return `${retained.length?`<p class="wizard-notice">Outside this package — kept for review: ${retained.map(id=>`${esc(C.menus.find(m=>m.id===id)?.name)} <button type="button" data-select-menu="${id}">Remove preference</button>`).join('; ')}. Switch package to keep these selections.</p>`:''}<div class="wizard-menu-grid">${visible.map(menuCard).join('')||'<p>No collections match this filter.</p>'}</div>`;}
function updateMenuGrid(){const host=$('#wizard-menu-host');if(host){host.innerHTML=menuMarkup();initImages(host);}}
function eventMarkup(){return `<h3 tabindex="-1">Let's set the scene.</h3><p class="step-description">An approximate headcount is perfect. Dates and details can stay undecided.</p><div class="field-grid"><div class="field"><label for="occasion">The occasion</label><select id="occasion" name="occasion">${eventTypes.map(t=>`<option value="${t.id}" ${state.type===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></div><div class="field"><label for="planner-guests">Approximate guests</label><input id="planner-guests" data-guest-input type="number" inputmode="numeric" min="1" max="10000" step="1" required value="${state.guests}"/><small class="field-hint">20-250: instant package baseline. Other sizes: custom quote.</small></div>${field('city','City',{required:true})}${selectDetail('region','State',[['NY','New York'],['NJ','New Jersey'],['CT','Connecticut'],['Other','Other / to confirm']])}${field('date','Preferred date',{type:'date'})}${field('startTime','Start time / Eastern Time',{type:'time'})}${selectDetail('venueType','Event setting',[['office','Office'],['rooftop','Rooftop'],['venue','Private venue'],['deciding','Still deciding']])}${hoursMarkup()}</div><p class="step-hint">An unspecified date or time means undecided. Building access and setup logistics come after the initial conversation.</p>${window.BarsysReadiness.eventFields(state)}`;}
function experienceMarkup(){return `<h3 tabindex="-1">Your kind of happy hour.</h3><p class="step-description">Same effortless service. Choose the level of occasion. Signature is a starting selection, not a personalized recommendation.</p><div class="tier-choices">${Object.entries(C.packages).map(([id,p])=>`<label class="choice tier-choice"><input type="radio" name="tier" value="${id}" ${state.tier===id?'checked':''}/><span><span class="choice-title">${esc(p.name)}</span><span class="choice-description">${p.menuLimit} included collections / ${esc(p.description)}</span></span><span class="choice-price">${dollars(p.rate)}<small> / guest</small></span><span class="choice-check"></span></label>`).join('')}</div><div class="field-grid wizard-extra-fields">${field('budget','Approximate total budget',{type:'number',placeholder:'e.g. 5000'})}${optionSelect('program','One event or a new tradition?',[['single','Single event'],['recurring','Recurring program']])}</div>${state.program==='recurring'?`<div class="recurring-options"><p class="mini-heading">YOUR PREFERRED PROGRAM</p><div class="field-grid">${optionSelect('frequency','How often?',[['exploring','Still exploring'],['twice-monthly','Twice a month'],['monthly','Once a month'],['quarterly','Once a quarter']])}${optionSelect('commitment','Commitment preference',[['exploring','Discuss with the team'],['3-months','3 months'],['6-months','6 months'],['12-months','12 months']])}${optionSelect('billing','Billing preference',[['exploring','Discuss with the team'],['monthly','Monthly'],['quarterly','Quarterly'],['annual','Annual']])}</div><p>Preferences only. No contract, discount or billing terms are confirmed in this preview.</p></div>`:''}<div class="wizard-notice">${icon('check')} Every baseline includes 2 hours of service, machines, bartenders, setup and cleanup.</div>`;}
function drinksMarkup(){const t=estimate();return `<h3 tabindex="-1">Find your first pour.</h3><p class="step-description">Choose a few collections or let us curate them. Mocktail options are already part of the experience.</p><div class="beverage-options" role="group" aria-label="Beverage preference">${[['mixed','Cocktails + mocktails'],['zero','Entirely zero proof'],['recommend','Help me choose']].map(([id,label])=>`<button type="button" data-beverage="${id}" aria-pressed="${state.beverage===id}">${label}</button>`).join('')}</div><div class="menu-step-tools"><span class="selection-count"></span><button type="button" class="text-link" id="request-extra-menu">Request extra mixlist ${icon('plus')}</button></div>${t.menuOverflow?`<p class="wizard-notice">${t.menuOverflow} extra preference${t.menuOverflow===1?'':'s'} kept after your package change. Add slots or remove collections; nothing was discarded.</p>`:''}<div class="wizard-menu-search"><label><span class="sr-only">Search collections</span><input id="wizard-menu-search" type="search" placeholder="Search all collections" value="${esc(menuQuery)}"/></label><label class="filter-toggle"><input id="wizard-zero-filter" type="checkbox" ${menuZero?'checked':''}/>Zero proof only</label></div><div id="wizard-menu-host">${menuMarkup()}</div><div class="menu-help-row"><button type="button" class="text-link" data-open-menus>Browse ${C.menus.filter(availableMenu).length} ${C.packages[state.tier].name} collections ${icon('arrow')}</button></div><label class="recommend-choice choice"><input name="menu-mode" type="checkbox" ${state.menuMode==='recommend'?'checked':''}/><span><strong>Let the team recommend</strong><small>Keep any favorites as preferences; we'll help finalize the mix.</small></span></label><div class="field wizard-extra-fields"><label for="detail-restrictions">Ingredient restrictions or preferences <small>Optional</small></label><textarea id="detail-restrictions" data-field="restrictions" maxlength="2000" placeholder="Event-level requirements only. Avoid entering guests' personal medical information.">${esc(state.details.restrictions)}</textarea><small class="field-hint">Requests require team confirmation; this is not an allergen-free guarantee.</small></div>${window.BarsysReadiness.serviceMarkup(state)}`;}
function addonsStep(){return `<h3 tabindex="-1">A little extra. A lot more you.</h3><p class="step-description">Optional finishing touches. Nothing is preselected or charged automatically.</p><div class="addon-intro"><span>${icon('spark')} MAKE IT YOURS</span><p>Approved prices go into your subtotal. Everything else stays clearly marked <strong>Quoted separately</strong>.</p></div><div data-addon-host>${addonsMarkup()}</div><button type="button" class="text-link wizard-skip" id="skip-extras">${Object.values(state.addons).some(a=>a.quantity)?'Continue with my selections':'Continue without extras'} ${icon('arrow')}</button>`;}
function reviewMarkup(){const t=estimate();const rows=[['Your event',`${eventName()} / ${state.guests} guests`,0],['Date & time',friendlyDate()+(state.details.startTime?' / '+state.details.startTime+' ET':''),0],['Location',[state.details.city,state.details.region,state.details.venueType].filter(Boolean).join(' / '),0],['Duration',serviceLabel(),0],['Experience',C.packages[state.tier].name,1],['Program',state.program==='single'?'Single event':`${state.frequency} / ${state.commitment} / ${state.billing} billing (requested)`,1],['Menu preferences',menuLabel(),2],['Beverage preference',state.beverage==='zero'?'Entirely zero proof':state.beverage==='mixed'?'Cocktails + mocktails':'Help choosing',2],...window.BarsysReadiness.summaryRows(state),['Add-ons',t.lines.filter(l=>l.selected).map(l=>`${l.name}${l.quantity>1?' x '+l.quantity:''}${l.variantLabel?' / '+l.variantLabel:''} / ${l.status==='included'?'included':l.status==='priced'?money(l.total):'quote pending'}`).join('\n')||'None requested',3]];return `<dl class="review-grid">${rows.map(([k,v,n])=>`<div class="review-item"><dt>${esc(k)}<button type="button" data-wizard-step="${n}" aria-label="Edit ${esc(k)}">Edit</button></dt><dd>${esc(v).replace(/\n/g,'<br>')}</dd></div>`).join('')}</dl>`;}
function contactMarkup(){return `<div class="field-grid">${field('name','Your full name',{required:true,placeholder:'Alex Morgan'})}${field('company','Company',{required:corporate(),placeholder:corporate()?'Your company':'Optional for private events'})}${field('email',corporate()?'Work email':'Email',{type:'email',required:true,placeholder:'alex@example.com'})}${field('phone','Phone',{type:'tel'})}${field('contractEntity','Contracting entity, if known',{placeholder:'Confirm at agreement stage'})}${field('venue','Venue or office address',{wide:true,placeholder:'Optional / can be confirmed later'})}<div class="field field-full"><label for="detail-notes">Anything else? <small>Optional</small></label><textarea id="detail-notes" data-field="notes" maxlength="2000" placeholder="Preferred brands, branding details, access requirements or the occasion.">${esc(state.details.notes)}</textarea></div></div>`;}
function renderStep(focus=false){complete=false;$('#event-form').hidden=false;$('.planner-controls').hidden=false;$('#form-error').hidden=true;$('#step-count').textContent=`0${currentStep+1} / 05`;$('#step-label').textContent=steps[currentStep];$('#progress-fill').style.width=`${(currentStep+1)*20}%`;$('#wizard-nav').innerHTML=steps.map((name,i)=>`<button type="button" data-wizard-step="${i}" ${i===currentStep?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span><b>${['Event','Experience','Drinks','Add-ons','Review'][i]}</b></button>`).join('');$('#back-step').style.visibility=currentStep?'visible':'hidden';$('#next-step').innerHTML=currentStep===4?`Create local event plan ${icon('check')}`:`Next: ${steps[currentStep+1]} ${icon('arrow')}`;$('#step-content').innerHTML=[eventMarkup,experienceMarkup,drinksMarkup,addonsStep,()=>`<h3 tabindex="-1">One last look. Then cheers.</h3><p class="step-description">Your preferences, your details, and an honest estimate. Review and edit anything below.</p>${reviewMarkup()}<h4 class="contact-heading">Who should the team speak with?</h4>${contactMarkup()}${window.BarsysReadiness.finalNotice(state)}<p class="review-info">Local preview only. Creating a plan does not send an inquiry, hold a date, take payment or subscribe you to marketing. Personal details stay in this tab unless you export them.</p>`][currentStep]();initImages($('#step-content'));updateMenuSelections();updateSummary();if(focus){$('#step-content h3')?.focus({preventScroll:true});$('#planner-shell').scrollIntoView({behavior:motion()?'smooth':'auto',block:'start'});}}
function showError(text,el){$('#form-error').textContent=text;$('#form-error').hidden=false;if(el){el.setAttribute('aria-invalid','true');el.setAttribute('aria-describedby',[...(el.getAttribute('aria-describedby')||'').split(' ').filter(Boolean).filter(x=>x!=='form-error'),'form-error'].join(' '));for(let parent=el.parentElement;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true;el.focus();}}
function validateStep(){for(const f of $$('input,select,textarea',$('#step-content'))){if(f.disabled)continue;if(['text','email'].includes(f.type))f.value=f.value.trim();if(f.dataset.field)state.details[f.dataset.field]=f.value;f.removeAttribute('aria-invalid');if(!f.checkValidity()){showError(f.type==='date'?'Choose today or a future date, or leave the date undecided.':f.type==='email'?'Please enter a valid email address.':`Please check ${f.labels?.[0]?.textContent||'this field'}.`,f);return false;}}if(currentStep===4){if(!state.details.city.trim()){currentStep=0;renderStep(true);showError('Please enter an event city.',$('#detail-city'));return false;}if(state.details.date&&state.details.date<todayISO()){currentStep=0;renderStep(true);showError('Choose a future date or leave it undecided.',$('#detail-date'));return false;}}return true;}
function submitLocalPlan(){complete=true;$('#step-label').textContent='Your local plan';$('#step-content').innerHTML=`<div class="success-icon">${icon('check')}</div><h3 tabindex="-1">Your event is taking shape.</h3><p class="success-message">Your plan is ready. <strong>Nothing has been sent, booked or charged yet.</strong>${window.BARSYS_RUNTIME?' Review it, then send your inquiry below.':''}</p>${reviewMarkup()}${window.BarsysReadiness.timeline()}<div class="success-actions"><button type="button" class="button" data-open-summary>View event summary ${icon('arrow')}</button><button type="button" class="button button-outline" id="download-plan">Download JSON</button><button type="button" class="text-link" data-download-summary>Download summary</button></div>`;$('.planner-controls').hidden=true;$('#step-content h3').focus({preventScroll:true});updateSummary();}
function exportData(){const t=estimate();return {mode:'LOCAL_PREVIEW_NOT_SENT',createdAt:new Date().toISOString(),sourceReviewed:C.quoteRules.sourceReviewed,event:{occasion:eventName(),guests:state.guests,package:C.packages[state.tier].name,serviceHours:state.serviceHours,includedServiceHours:2,beveragePreference:state.beverage,menus:menuNames(),menuRecommendationRequested:state.menuMode==='recommend',includedMenuCount:t.includedMenus,additionalMenuSlots:t.menuLimit-t.includedMenus,addons:t.lines.filter(l=>l.selected),enhancements:t.lines.filter(l=>l.selected).map(l=>l.name),program:state.program,requestedCadence:state.program==='recurring'?state.frequency:null,commitmentPreference:state.program==='recurring'?state.commitment:null,billingPreference:state.program==='recurring'?state.billing:null},contact:{...state.details},readiness:window.BarsysReadiness.exportMeta(state),estimate:{...t,excludesUnpricedRequests:true,recurringDiscountApplied:false,note:estimateNote()}};}
function downloadPlan(){const u=URL.createObjectURL(new Blob([JSON.stringify(exportData(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='Barsys-Local-Event-Plan.json';document.body.append(a);a.click();a.remove();toast('JSON download requested. Check your browser downloads. Nothing was sent.');setTimeout(()=>URL.revokeObjectURL(u),3000);}
async function copyPlan(){const e=exportData(),t=e.estimate;const text=['BARSYS / LOCAL PREVIEW - NOT SENT',`${e.event.occasion} | ${e.event.guests} guests | ${e.event.package}`,`${friendlyDate()} | ${state.details.startTime||'Time undecided'} | ${serviceLabel()}`,`Location: ${state.details.city}, ${state.details.region}`,`Contact: ${state.details.name} | ${state.details.email}`,`Menus: ${menuLabel()}`,`Add-ons: ${e.event.addons.map(l=>`${l.name} x ${l.quantity}${l.variantLabel?' ('+l.variantLabel+')':''} - ${l.status==='included'?'Included':l.total===null?'Quoted separately':money(l.total)}`).join('; ')||'None'}`,`Subtotal before tax: ${t.subtotal===null?'Custom quote':money(t.subtotal)}`,'Tax: to be confirmed',`Delivery/access: ${t.scopeCosts.map(l=>l.name+' - '+l.label).join('; ')}`,`Venue permission: ${window.BarsysReadiness.label('venueApproval',state.details.venueApproval)}`,`COI: ${window.BarsysReadiness.label('coi',state.details.coi)}`,`Glassware: ${window.BarsysReadiness.label('glassware',state.details.glassware)}`,`Publicity: ${window.BarsysReadiness.label('photoPreference',state.details.photoPreference)} - no permission granted`,`Marketing: ${state.details.marketingInterest==='yes'?'interested; not subscribed':'no opt-in'}`,`Program: ${e.event.program}`,estimateNote()].join('\n');try{await navigator.clipboard.writeText(text);toast('Preview copied. Nothing was sent.');}catch(_){toast('Clipboard unavailable. Download the summary instead.');}}
function resetPlan(){state=defaults();menuQuery='';menuZero=false;$('#menu-search').value='';$('#zero-proof-filter').checked=false;currentStep=0;complete=false;try{localStorage.removeItem(C.storageKey);}catch(_){}syncGuests();renderStep(true);commit();toast('A fresh start. All entered details were cleared.');}
function renderDialog(){const q=$('#menu-search').value.toLowerCase(),z=$('#zero-proof-filter').checked;const match=C.menus.filter(m=>availableMenu(m)&&(!z||m.zeroProof)&&`${m.name} ${m.description}`.toLowerCase().includes(q));$('#dialog-menu-grid').innerHTML=state.menus.filter(id=>!Q.menuAvailable(id,state.tier,C)).map(id=>`<p class="wizard-notice">${esc(C.menus.find(m=>m.id===id)?.name)} is outside ${esc(C.packages[state.tier].name)}. <button type="button" data-select-menu="${id}">Remove preference</button></p>`).join('')+match.map(menuCard).join('')||'<p>No matching collections.</p>';initImages($('#dialog-menu-grid'));updateMenuSelections();}
function openMenus(){lastDialogFocus=document.activeElement;$('#menu-search').value='';$('#zero-proof-filter').checked=state.beverage==='zero';renderDialog();$('#menus-dialog').showModal();$('#menu-search').focus({preventScroll:true});}
function closeMobileNav(){$('#mobile-nav').hidden=true;$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').setAttribute('aria-label','Open navigation');$('.menu-toggle').innerHTML=icon('menu');}
  function imageSource(key) {
    const asset = C.assets[key];
    if (!asset) return '';
    const src=(window.BARSYS_LOCAL_ASSETS || []).includes(key) ? asset.local : asset.remote || asset.local;
    return src; // Company-owned artwork is ordinary page content, not a tracking category.
  }
  function setImage(img, key) {
    const asset = C.assets[key];
    if (!asset || !img) return;
    const frame = img.closest('[data-photo-frame], .menu-image, .taste-stage, .collection-cover');
    img.dataset.image = key;
    img.dataset.initialized = 'true';
    img.alt = asset.alt;
    img.referrerPolicy = 'no-referrer';
    if (frame) {
      frame.dataset.illustration = String(Boolean(asset.initialIllustration));
      delete frame.dataset.failed; delete frame.dataset.loaded;
    }
    img.onload = () => {
      if (frame) { frame.dataset.loaded = 'true'; delete frame.dataset.failed; }
    };
    img.onerror = () => {
      if (frame) { frame.dataset.failed = 'true'; delete frame.dataset.loaded; }
    };
    const src=imageSource(key);
    if(!src){img.removeAttribute('src');if(frame)frame.dataset.failed='true';return;}
    img.src=src;
  }
  function initImages(root = document) {
    $$('img[data-image]:not([data-initialized])', root).forEach(img => setImage(img, img.dataset.image));
  }
  function renderPackages() {
    $('#package-grid').innerHTML = Object.entries(C.packages).map(([id, p], index) => `
      <article data-reveal class="package-card ${id}" aria-labelledby="package-${id}">
        <div class="package-top"><span class="package-type">${esc(p.positioning || `EXPERIENCE 0${index+1}`)}</span>${id === 'signature' ? `<span class="recommendation">${icon('spark')}THE SWEET SPOT</span>` : ''}</div>
        <h3 id="package-${id}">${esc(p.name)}</h3><p class="package-desc">${esc(p.description)}</p>
        <div class="package-price"><strong>${dollars(p.rate)}</strong><span>/ guest</span></div>
        <p class="event-subtotal"><span data-package-subtotal="${id}">${dollars(p.rate*state.guests)}</span> for <span data-guest-count>${state.guests}</span> guests &middot; before tax</p>
        <ul class="package-features">${p.features.map(feature => `<li>${icon('check')}${esc(feature)}</li>`).join('')}</ul>
        <details class="package-details"><summary>What's included ${icon('chevron')}</summary><p>${esc(p.detail)}</p></details>
        <button type="button" class="button ${id === 'signature' ? 'button-light' : 'button-outline'}" data-select-package="${id}">Choose ${esc(p.name)}${icon('arrow')}</button>
      </article>`).join('');
  }
  function renderFeaturedMenus() {
    $('#featured-menus').innerHTML = C.menus.filter(availableMenu).sort((a,b)=>Number(!!b.featured)-Number(!!a.featured)).map(m => `
      <article class="menu-card" data-collection="${m.id}" data-zero-proof="${!!m.zeroProof}"><button type="button" class="menu-image" data-preview-menu="${m.id}" data-photo-frame aria-label="Explore ${esc(m.name)}">
        <img data-image="${m.image}" width="1000" height="1000" loading="lazy" alt="${esc(C.assets[m.image].alt)}">
        <span class="photo-fallback" aria-hidden="true"><span class="cover-loading">BARSYS MIXLISTS</span><span class="cover-unavailable">Artwork unavailable<br><small>Check your connection. Collection details are still available.</small></span></span>
        <span class="menu-tag">${esc(m.tag)}</span></button>
        <h3>${esc(m.name)}</h3><p>${esc(m.description)}</p><button class="menu-details-link text-link" type="button" data-rich-menu="${m.id}">Explore this collection ${icon("arrow")}</button><div class="menu-card-footer"><span>${m.recipes} recipes ${m.zeroProof ? '&middot; Alcohol free' : ''}</span><button type="button" class="text-link" data-select-menu="${m.id}" aria-pressed="false">Add to my event${icon('plus')}</button></div>
      </article>`).join('');
    initImages($('#featured-menus'));document.dispatchEvent(new CustomEvent('barsys:menus'));
  }

function goStep(n){if(n<0||n>4)return;currentStep=n;document.dispatchEvent(new CustomEvent('barsys:route',{detail:'full'}));renderStep(true);}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;
if(b.hasAttribute('data-adjust-guests'))setGuests(Math.max(1,Math.min(10000,state.guests+Number(b.dataset.adjustGuests))));
if(b.hasAttribute('data-select-package')){setTier(b.dataset.selectPackage);document.dispatchEvent(new CustomEvent('barsys:route',{detail:'quick'}));}
if(b.hasAttribute('data-select-menu'))toggleMenu(b.dataset.selectMenu);
if(b.hasAttribute('data-open-menus'))openMenus();
if(b.hasAttribute('data-preview-menu'))document.dispatchEvent(new CustomEvent('barsys:collection',{detail:b.dataset.previewMenu}));
if(b.hasAttribute('data-close-dialog'))$('#menus-dialog').close();
if(b.hasAttribute('data-wizard-step'))goStep(Number(b.dataset.wizardStep));
if(b.hasAttribute('data-beverage')){setOption('beverage',b.dataset.beverage);menuZero=b.dataset.beverage==='zero';renderStep(false);}
if(b.hasAttribute('data-addon')){const id=b.dataset.addon,a=C.addons.find(x=>x.id===id);const n=Q.quantity(a,state);setAddon(id,b.dataset.delta?n+Number(b.dataset.delta):n?0:1);refreshAddonHosts();}
if(b.id==='request-extra-menu')extraMenuRequest();
if(b.id==='skip-extras')goStep(4);
if(b.id==='download-plan')downloadPlan();
if(b.id==='copy-plan')copyPlan();
if(b.id==='edit-plan')goStep(4);
if(b.closest('#mobile-nav'))closeMobileNav();});
document.addEventListener('input',e=>{const f=e.target;if(f.matches('[data-guest-input]')){if(setGuests(Number(f.value),f))f.removeAttribute('aria-invalid');else f.setAttribute('aria-invalid','true');}if(f.hasAttribute('data-field')){setDetails({[f.dataset.field]:f.value});f.removeAttribute('aria-invalid');$('#form-error').hidden=true;}if(f.id==='wizard-menu-search'){menuQuery=f.value.toLowerCase();updateMenuGrid();}});
document.addEventListener('change',e=>{const f=e.target;if(f.name==='occasion'){state.type=f.value;commit();}if(f.name==='tier'){setTier(f.value);renderStep(false);}if(f.hasAttribute('data-field'))setDetails({[f.dataset.field]:f.value});if(f.hasAttribute('data-hours'))setHours(f.value);if(f.hasAttribute('data-option')){setOption(f.dataset.option,f.value);if(f.dataset.option==='program')renderStep(false);}if(f.hasAttribute('data-addon-variant')){const a=C.addons.find(a=>a.id===f.dataset.addonVariant);setAddon(a.id,Q.quantity(a,state),f.value);refreshAddonHosts();}if(f.name==='menu-mode'){state.menuMode=f.checked?'recommend':'choose';commit();}if(f.id==='wizard-zero-filter'){menuZero=f.checked;updateMenuGrid();}});
$('#event-form').addEventListener('submit',e=>{e.preventDefault();if(complete||!validateStep())return;if(currentStep===4)submitLocalPlan();else{currentStep++;renderStep(true);}});
$('#back-step').addEventListener('click',()=>{if(currentStep){currentStep--;renderStep(true);}});
$('#reset-plan').addEventListener('click',resetPlan);
$('#recurring-link').addEventListener('click',()=>{setOption('program','recurring');goStep(1);});
$('.summary-mobile-toggle').addEventListener('click',e=>{const b=e.currentTarget,on=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(on));$('.plan-summary').classList.toggle('expanded',on);});
$('.menu-toggle').addEventListener('click',()=>{const open=$('#mobile-nav').hidden;$('#mobile-nav').hidden=!open;$('.menu-toggle').setAttribute('aria-expanded',String(open));$('.menu-toggle').setAttribute('aria-label',open?'Close navigation':'Open navigation');$('.menu-toggle').innerHTML=icon(open?'close':'menu');});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMobileNav();});
$('#menu-search').addEventListener('input',renderDialog);$('#zero-proof-filter').addEventListener('change',renderDialog);
$('#menus-dialog').addEventListener('close',()=>{if(lastDialogFocus?.isConnected)lastDialogFocus.focus({preventScroll:true});});
$('#menus-dialog').addEventListener('click',e=>{const d=e.currentTarget,r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close();});
window.addEventListener('scroll',()=>$('.site-header').classList.toggle('scrolled',scrollY>25),{passive:true});
if('IntersectionObserver'in window)new IntersectionObserver(es=>es.forEach(e=>$('#mobile-book').classList.toggle('suppressed',e.isIntersecting))).observe($('#proposal'));
window.addEventListener('resize',()=>{if(innerWidth>=800)closeMobileNav();},{passive:true});
$('#year').textContent=new Date().getFullYear();loadDraft();renderPackages();renderFeaturedMenus();renderStep();syncGuests();initImages();
window.BarsysPlanner=Object.freeze({getState:()=>JSON.parse(JSON.stringify(state)),getEstimate:estimate,exportData,setGuests,setTier,toggleMenu,copyPlan,downloadPlan,initImages,imageSource,setImage,toast,setDetails,setOption,setHours,setAddon,addonsMarkup,priceMarkup,estimateNote,corporate,serviceLabel,menuLabel,refreshAddonHosts,reviewMarkup,goStep,
setOccasion(value){if(eventTypes.some(e=>e.id===value)){state.type=value;commit();}},refresh(){renderStep(false);},reset:resetPlan,openFull(){renderStep(false);},addMenu(id){if(!state.menus.includes(id))toggleMenu(id);return state.menus.includes(id);}});
window.BarsysPreview=Object.freeze({getState:()=>JSON.parse(JSON.stringify(state)),getEstimate:estimate,getStep:()=>currentStep,isComplete:()=>complete});
})();
