/* V4.0 / unified 5-card planner (guests, package, add-ons, location & date, your details) + Customize/Estimate sheets.
   Replaces the old 5-step "Customize everything" wizard. Marketing-page grids/dialogs and the state
   machine (menus, addons, quote, readiness) are unchanged; only card rendering/navigation is new. */
(() => {
'use strict';
const C=window.BARSYS,Q=window.BarsysQuote;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<svg class="icon" aria-hidden="true"><use href="#i-${n}"/></svg>`;
const money=n=>n===null?'To be quoted':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2,minimumFractionDigits:2}).format(n);
const dollars=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const eventTypes=[{id:'team',name:'Team happy hour',icon:'users'},{id:'client',name:'Client event',icon:'glass'},{id:'celebration',name:'Company celebration',icon:'spark'},{id:'recruiting',name:'Recruiting event',icon:'users'},{id:'executive',name:'Executive event',icon:'glass'},{id:'exploring',name:'Just exploring',icon:'calendar'},{id:'birthday',name:'Birthday party',icon:'spark'},{id:'engagement',name:'Engagement party',icon:'glass'},{id:'venue',name:'Venue event',icon:'pin'},{id:'other',name:'Another occasion',icon:'calendar'}];
const cardTitles=['Guests','Package','Add-ons','Location & date','Your details'];
const blankDetails=()=>({name:'',email:'',company:'',phone:'',date:'',startTime:'',timezone:'America/New_York',city:'New York',region:'NY',venue:'',venueType:'office',budget:'',restrictions:'',notes:'',venueApproval:'not-checked',coi:'unsure',glassware:'discuss',contractEntity:'',marketingInterest:'no',photoPreference:'discuss'});
const defaults=()=>({type:'team',guests:C.defaultGuests,tier:'signature',menus:[],menuMode:'recommend',addons:{},enhancements:[],program:'single',frequency:'exploring',commitment:'exploring',billing:'exploring',beverage:'mixed',serviceHours:2,details:blankDetails()});
const RUNTIME_MODE=window.BARSYS_RUNTIME?.mode||null,CONNECTED=!!window.BARSYS_RUNTIME,LIVE_MODE=RUNTIME_MODE==='LIVE';
let state=defaults(),step=0,furthest=0,flipped=false,guestDraft=String(C.defaultGuests),dateDecided=false,complete=false,receiptId=null,customTab='menus',toastTimer,lastDialogFocus=null,menuQuery='',menuZero=false;
const eventName=()=>eventTypes.find(e=>e.id===state.type)?.name||'Event';
const menuNames=()=>state.menus.map(id=>C.menus.find(m=>m.id===id)?.name).filter(Boolean);
const menuLabel=()=>[menuNames().join(', '),state.menuMode==='recommend'?'Team recommendation requested':''].filter(Boolean).join(' / ')||'Team recommendation';
const estimate=()=>Q.calculate(state,C);
const corporate=()=>['team','client','celebration','recruiting','executive'].includes(state.type);
const todayISO=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);};
const friendlyDate=()=>state.details.date?new Date(`${state.details.date}T12:00:00`).toLocaleDateString('en-US',{year:'numeric',month:'short',day:'numeric'}):'Date to be decided';
const serviceLabel=()=>state.serviceHours===null?'Duration to be decided':`${state.serviceHours} hours requested`;
const motion=()=>document.documentElement.dataset.motion!=='off';
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4500);}
function saveDraft(){window.BarsysPrivacy?.saveDraft(state);}
function loadDraft(){try{const x=window.BarsysPrivacy?.loadDraft();if(!x||x.version!==3)return;if(eventTypes.some(t=>t.id===x.type))state.type=x.type;if(Number.isInteger(x.guests)&&x.guests>=1&&x.guests<=10000)state.guests=x.guests;if(Object.hasOwn(C.packages,x.tier))state.tier=x.tier;if(Array.isArray(x.menus))state.menus=[...new Set(x.menus)].filter(id=>C.menus.some(m=>m.id===id));state.menuMode=['choose','recommend'].includes(x.menuMode)?x.menuMode:state.menus.length?'choose':'recommend';for(const a of C.addons){const v=x.addons?.[a.id];if(v)state.addons[a.id]={quantity:Q.quantity(a,x),variant:a.variants?.some(t=>t[0]===v.variant)?v.variant:a.variants?.[0]?.[0]||''};}for(const k of ['program','frequency','commitment','billing','beverage'])if(validOption(k,x[k]))state[k]=x[k];if(x.serviceHours===null||Number.isFinite(x.serviceHours)&&x.serviceHours>=1&&x.serviceHours<=8)state.serviceHours=x.serviceHours;}catch(_){}guestDraft=String(state.guests);dateDecided=!!state.details.date;}
const optionSets={program:['single','recurring'],frequency:['monthly','twice-monthly','quarterly','exploring'],commitment:['3-months','6-months','12-months','exploring'],billing:['monthly','quarterly','annual','exploring'],beverage:['mixed','zero','recommend']};
function validOption(key,value){return optionSets[key]?.includes(value);}
function syncGuestInputs(skip){$$('[data-guest-input]').forEach(el=>{if(el!==skip)el.value=state.guests;});const g=$('#card-guests');if(g&&g!==skip&&g!==document.activeElement){g.value=guestDraft;g.classList.toggle('long-number',guestDraft.length>3);}$$('[data-guests]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.guests)===state.guests)));}
function commit(){saveDraft();document.body.classList.add('plan-intent');updateDeckTotals();updateMenuSelections();updateDock();}
function setGuests(n,source=null){if(!Number.isInteger(n)||n<1||n>C.quoteRules.maxInquiryGuests)return false;state.guests=n;guestDraft=String(n);syncGuestInputs(source);commit();refreshAddonHosts();return true;}
function availableMenu(m){return Q.menuAvailable(m.id,state.tier,C);}
function refreshPackageMenus(){renderFeaturedMenus();updateMenuGrid();if($('#menus-dialog').open)renderDialog();}
function setTier(t){if(!Object.hasOwn(C.packages,t))return;state.tier=t;if(!C.packages[t].menuLimit&&state.menus.length){state.menus=[];toast('Collins runs on your own drinks list, so Barsys menu preferences were cleared.');}const keep=new Set(Q.packageAddons(t,C).map(a=>a.id));for(const id of Object.keys(state.addons))if(!keep.has(id))delete state.addons[id];const hours=Q.packageAddons(t,C).find(a=>a.extendsService);state.serviceHours=hours?2+(state.addons[hours.id]?.quantity||0):2;refreshPackageMenus();commit();refreshAddonHosts();if(estimate().unavailableMenus.length)toast('Some retained preferences are outside this package. Review them in Menus & extras.');if(estimate().menuOverflow)toast('Your menu choices were kept. Review the extra mixlist request for this package.');}
function setDetails(patch){for(const [k,v] of Object.entries(patch))if(Object.hasOwn(state.details,k)&&typeof v==='string')state.details[k]=v.slice(0,['notes','restrictions'].includes(k)?2000:254);updateDeckTotals();}
function setOption(k,v){if(!validOption(k,v))return;state[k]=v;commit();}
function serviceAddon(){return Q.packageAddons(state.tier,C).find(a=>a.extendsService)||null;}
function setHours(value){const n=value===''||value===null?null:Number(value);if(n!==null&&(!Number.isInteger(n)||n<1||n>8))return;state.serviceHours=n;const a=serviceAddon();if(a)state.addons[a.id]={quantity:Math.max(0,(n||2)-2),variant:''};commit();}
function setAddon(id,n,variant){const a=C.addons.find(x=>x.id===id);if(!a)return;const prev=state.addons[id]||{};state.addons[id]={quantity:Math.max(0,Math.min(a.maxQuantity,Math.trunc(Number(n)||0))),variant:a.variants?.some(v=>v[0]===variant)?variant:prev.variant||a.variants?.[0]?.[0]||''};if(a.extendsService)state.serviceHours=2+state.addons[id].quantity;commit();}
function refreshAddonHosts(){
 if(flipped||!$('#step-content')?.querySelector('[data-addon-host]'))return;
 const active=document.activeElement;const marker=active?.dataset?.addon||active?.dataset?.addonVariant;
 const delta=active?.dataset?.delta;
 const restore=marker?(active.hasAttribute('data-addon-variant')?`[data-addon-variant="${marker}"]`:`[data-addon="${marker}"]${delta?`[data-delta="${delta}"]`:''}`):null;
 refreshAddonCard(restore);
}
/* Re-render in place: the card is mid-interaction, so scroll position, the open state of
   the disclosure and the control that was just clicked all have to survive. */
function refreshAddonCard(restore){
 const content=$('#step-content');if(!content)return;
 const scroll=content.scrollTop,wasOpen=$('#addon-more',content)?.open;
 content.innerHTML=addonsCard();
 const more=$('#addon-more',content);if(more&&wasOpen!==undefined)more.open=wasOpen;
 content.scrollTop=scroll;
 if(restore)$(restore,content)?.focus({preventScroll:true});
 updateDeckTotals();
}
function toggleMenu(id){const m=C.menus.find(x=>x.id===id);if(!m)return false;if(!state.menus.includes(id)&&!availableMenu(m)){toast('This collection is not available with '+C.packages[state.tier].name+'. Choose another package to explore it.');return false;}if(state.menus.includes(id))state.menus=state.menus.filter(x=>x!==id);else {if(state.menus.length>=estimate().menuLimit){toast('Included slots are full. Request an additional mixlist in Add-ons, or remove a collection.');return false;}state.menus.push(id);}state.menuMode=state.menus.length?'choose':'recommend';commit();if($('#menus-dialog').open)renderDialog();if($('#customize').open&&customTab==='menus')renderCustom(`[data-select-menu="${id}"]`);return true;}
function extraMenuRequest(){setAddon('extra-mixlists',Q.quantity(C.addons.find(a=>a.id==='extra-mixlists'),state)+1);toast('One extra collection slot requested. Its price will be quoted separately.');if($('#customize').open&&customTab==='menus')renderCustom();}
function packageTotal(p){const n=Q.packagePrice(p,state.guests);return n===null||!estimate().eligible?'Custom quote':dollars(n);}
function priceMarkup(){const t=estimate(),p=C.packages[state.tier];return `<div class="price-line"><span>${esc(p.name)} / ${state.guests} guests${t.eligible?t.minimumApplies?` &middot; ${dollars(t.minimumFee)} event minimum`:` &times; ${dollars(p.rate)}`:''}</span><strong>${t.base===null?'Custom quote':money(t.base)}</strong></div>${t.priced.map(l=>`<div class="price-line"><span>${esc(l.name)}${l.quantity>1?' &times; '+l.quantity:''}</span><strong>${money(l.total)}</strong></div>`).join('')}${t.scopeCosts.length?`<div class="scope-costs"><span class="pending-title">EVENT SCOPE TO CONFIRM</span>${t.scopeCosts.map(l=>`<div class="price-line"><span>${esc(l.name)}</span><span>${l.status==='priced'?money(l.total):esc(l.label)}</span></div>`).join('')}</div>`:''}<div class="price-line tax-unconfirmed"><span>Tax</span><span>To be confirmed</span></div>${t.pending.length?`<div class="pending-quotes"><span class="pending-title">${t.pending.length} REQUEST${t.pending.length===1?'':'S'} TO QUOTE</span>${t.pending.map(l=>`<div class="price-line"><span>${esc(l.name)}${l.quantity>1?' &times; '+l.quantity:''}</span><span>Separate quote</span></div>`).join('')}</div>`:''}`;}
function estimateNote(){const t=estimate();return [t.subtotal===null?'Custom quote required.':'Package and explicitly priced items only, before tax.',t.pending.length?'Unpriced requests are NOT included in the subtotal.':'','Delivery, access and glassware scope are confirmed separately; see the breakdown.',state.program==='recurring'?'Single-event baseline; recurring terms are not priced.':'',...t.reasons.filter(r=>!r.startsWith('Recurring')),'Nothing is booked or sent.'].filter(Boolean).join(' ');}
function updateMenuSelections(){const t=estimate();if(C.menuPolicy?.published)$$('[data-open-menus]').forEach(b=>b.textContent='Explore '+C.menus.filter(availableMenu).length+' '+C.packages[state.tier].name+' collections');$$('[data-select-menu]').forEach(b=>{const on=state.menus.includes(b.dataset.selectMenu);b.setAttribute('aria-pressed',String(on));if(b.closest('.menu-card-footer'))b.innerHTML=`${on?'Added to your event':'Add to my event'}${icon(on?'check':'plus')}`;if(b.classList.contains('wm-select'))b.innerHTML=on?`${icon('check')} Selected`:`${icon('plus')} Select`;});$$('.selection-count').forEach(el=>el.textContent=`${state.menus.length} selected / ${t.includedMenus} included${t.menuLimit>t.includedMenus?' + '+(t.menuLimit-t.includedMenus)+' extra requested':''}`);$('#dialog-selected-count').textContent=`${state.menus.length} / ${t.menuLimit} slots`;$('#menu-dialog-help').textContent=`${t.includedMenus} included with ${C.packages[state.tier].name}. ${t.menuLimit-t.includedMenus} extra requested. Final menu and any extra cost are confirmed by the team.`;const recommend=$('[name="menu-mode"]');if(recommend)recommend.checked=state.menuMode==='recommend';}
function field(key,label,{type='text',required=false,wide=false,placeholder=''}={}){return `<div class="field ${wide?'field-full':''}"><label for="detail-${key}">${label}${required?'':' <small>Optional</small>'}</label><input id="detail-${key}" name="${key}" ${({name:'name',email:'email',phone:'tel',company:'organization',city:'address-level2'}[key])?`autocomplete="${({name:'name',email:'email',phone:'tel',company:'organization',city:'address-level2'}[key])}"`:''} data-field="${key}" type="${type}" value="${esc(state.details[key])}" ${required?'required':''} ${type==='date'?`min="${todayISO()}"`:''} ${type==='number'?'min="0" step="1"':''} maxlength="254" placeholder="${esc(placeholder)}"/></div>`;}
function selectDetail(key,label,options){return `<div class="field"><label for="detail-${key}">${label}</label><select id="detail-${key}" data-field="${key}">${options.map(([id,name])=>`<option value="${id}" ${state.details[key]===id?'selected':''}>${esc(name)}</option>`).join('')}</select></div>`;}
function optionSelect(key,label,options){return `<div class="field"><label for="plan-${key}">${label}</label><select id="plan-${key}" data-option="${key}">${options.map(([id,name])=>`<option value="${id}" ${state[key]===id?'selected':''}>${name}</option>`).join('')}</select></div>`;}
function hoursMarkup(){return `<div class="field"><label for="service-hours">Requested service time</label><select id="service-hours" data-hours><option value="" ${state.serviceHours===null?'selected':''}>Not sure yet</option>${[1,2,3,4,5,6,7,8].map(n=>`<option value="${n}" ${state.serviceHours===n?'selected':''}>${n} hours${n===2?' / package baseline':n>2?' / extra time quoted separately':' / custom scope'}</option>`).join('')}</select><small class="field-hint">Extra time is a request, not a confirmed booking.</small></div>`;}
const ESSENTIAL_ADDONS=['beer-wine','extra-hours'];
function addonCard(a,i){const l=Q.line(a,state);return `<article class="addon-card ${l.selected?'is-added':''} ${l.status==='included'?'is-included':''}" data-addon-card="${a.id}"><div class="addon-top"><span class="addon-icon">${icon(a.icon)}</span><span class="addon-kicker">${l.status==='included'?'IN YOUR PACKAGE':String(i+1).padStart(2,'0')+' / OPTIONAL'}</span></div><h4>${esc(a.name)}</h4>${a.includes?.length?`<ul class="addon-includes">${a.includes.map(f=>`<li>${icon('check')}<span>${esc(f)}</span></li>`).join('')}</ul>`:`<p>${esc(a.description)}</p>`}${l.status==='included'&&a.includedNotes?.[state.tier]?`<p class="addon-note">${esc(a.includedNotes[state.tier])}</p>`:''}${a.variants?`<label class="addon-variant"><span class="sr-only">${esc(a.name)} preference</span><select data-addon-variant="${a.id}" ${l.status==='included'?'disabled':''}>${a.variants.map(([id,n])=>`<option value="${id}" ${l.variant===id?'selected':''}>${esc(n)}</option>`).join('')}</select></label>`:''}<div class="addon-bottom"><div class="addon-price"><strong>${l.status==='included'?'Included':l.status==='priced'?money(l.unitPrice):'Quoted separately'}</strong><span>${l.status==='included'?'No additional charge':esc(a.unitLabel)}</span>${l.selected&&l.status==='priced'?`<em>${money(l.total)} for your event</em>`:''}</div>${l.status==='included'?`<span class="included-tick">${icon('check')}</span>`:a.maxQuantity>1?`<div class="addon-counter"><button type="button" data-addon="${a.id}" data-delta="-1" ${l.quantity===0?'disabled':''} aria-label="Remove one ${esc(a.name)}">${icon('minus')}</button><output aria-label="${esc(a.name)} quantity">${l.quantity}</output><button type="button" data-addon="${a.id}" data-delta="1" ${l.quantity===a.maxQuantity?'disabled':''} aria-label="Add one ${esc(a.name)}">${icon('plus')}</button></div>`:`<button type="button" class="addon-add" data-addon="${a.id}" aria-pressed="${l.selected}">${icon(l.selected?'check':'plus')}${l.selected?'Added':'Add'}</button>`}</div></article>`;}
function addonGrid(list){return `<div class="addon-grid">${list.map(addonCard).join('')}</div>`;}
function menuCard(m){return `<article class="wizard-menu-card"><div class="wm-art" data-photo-frame>${m.image?`<img loading="lazy" data-image="${m.image}" alt="${esc(m.name)} collection artwork" width="400" height="400"/>`:''}<span class="wm-placeholder">BARSYS<br/>MIXLIST</span><span class="wm-type">${m.zeroProof?'ZERO PROOF':'COCKTAILS'}</span></div><div class="wm-body"><h4>${esc(m.name)}</h4><p>${m.recipes} recipes</p><div class="wm-actions">${m.image?`<button type="button" class="wm-details" data-preview-menu="${m.id}">View drinks</button>`:'<span></span>'}<button type="button" class="wm-select" data-select-menu="${m.id}" aria-pressed="${state.menus.includes(m.id)}">${icon(state.menus.includes(m.id)?'check':'plus')}${state.menus.includes(m.id)?'Selected':'Select'}</button></div></div></article>`;}
function menuMarkup(){const visible=C.menus.filter(m=>availableMenu(m)&&(!menuZero||m.zeroProof)&&`${m.name} ${m.description}`.toLowerCase().includes(menuQuery));const retained=state.menus.filter(id=>!Q.menuAvailable(id,state.tier,C));return `${retained.length?`<p class="wizard-notice">Outside this package — kept for review: ${retained.map(id=>`${esc(C.menus.find(m=>m.id===id)?.name)} <button type="button" data-select-menu="${id}">Remove preference</button>`).join('; ')}. Switch package to keep these selections.</p>`:''}<div class="wizard-menu-grid">${visible.map(menuCard).join('')||'<p>No collections match this filter.</p>'}</div>`;}
function updateMenuGrid(){const host=$('#wizard-menu-host');if(host){host.innerHTML=menuMarkup();initImages(host);}}
/* ---- Card content ---- */
function cardMeta(extra=''){return `<div class="card-meta"><span class="card-kicker">${step===5?(CONNECTED?(LIVE_MODE?'Inquiry sent':'Test inquiry saved'):'YOUR PLAN'):String(step+1).padStart(2,'0')+' / '+cardTitles[step].toUpperCase()}</span>${extra}</div>`;}
function guestCard(){return `${cardMeta()}<h3 id="card-title" tabindex="-1">How many guests<br>are you planning for?</h3><p class="step-description">An approximate headcount is perfect. Dates and details can stay undecided.</p><div class="stepper"><button type="button" data-card-guest-delta="-10" aria-label="10 fewer guests">${icon('minus')}</button><label class="sr-only" for="card-guests">Approximate number of guests</label><input id="card-guests" type="number" inputmode="numeric" min="1" max="${C.quoteRules.maxInquiryGuests}" step="1" required value="${esc(guestDraft)}" class="${guestDraft.length>3?'long-number':''}"/><button type="button" data-card-guest-delta="10" aria-label="10 more guests">${icon('plus')}</button></div><div class="presets" role="group" aria-label="Quick guest counts">${[25,50,75,100].map(n=>`<button type="button" data-guests="${n}" aria-pressed="${state.guests===n}">${n}</button>`).join('')}</div><p class="card-tip">${C.minGuests}&ndash;${C.maxGuests} guests: instant package estimate. Other sizes: custom quote.</p>`;}
function packageCard(){const t=estimate();return `${cardMeta(`<button type="button" class="flip-link" id="flip-card">${icon('flip')} What's included?</button>`)}<h3 id="card-title" tabindex="-1">Your kind of occasion.</h3><p class="step-description">One starting package for ${state.guests} guests. Add-ons come next; menus live in Menus &amp; extras above.</p><div class="tier-choices">${Object.entries(C.packages).map(([id,p])=>`<label class="choice tier-choice"><input type="radio" name="tier" value="${id}" ${state.tier===id?'checked':''}/><span><span class="choice-title">${esc(p.name)}</span><span class="choice-description">${esc(p.positioning||p.description)}</span></span><span class="choice-price">${packageTotal(p)}<small>${Q.minimumApplies(p,state.guests)?`${dollars(p.minimumFee)} event minimum`:`${dollars(p.rate)} / guest`}${Q.stations(p,state.guests)?` &middot; ${Q.stations(p,state.guests)} station${Q.stations(p,state.guests)===1?'':'s'}`:''}</small></span><span class="choice-check"></span></label>`).join('')}</div><p class="card-tip">Package estimates are before tax, delivery, glassware and extras.</p>`;}
function packageBack(){const p=C.packages[state.tier];return `${cardMeta(`<button type="button" class="flip-link" id="flip-card">${icon('flip')} Back to choices</button>`)}<h3 id="card-title" tabindex="-1">Inside ${esc(p.name)}.</h3><p class="step-description">${esc(p.detail)}</p><ul class="package-features">${[...p.features,...(p.serviceFeatures||['2 hours of service, machines and bartending','Cocktail and zero-proof options included'])].map(f=>`<li>${icon('check')}<span>${esc(f)}</span></li>`).join('')}</ul><p class="field-hint">Final menus, staffing, availability and any extras are confirmed in your proposal.</p>`;}
function addonsCard(){
 const offered=Q.packageAddons(state.tier,C);
 const essentials=ESSENTIAL_ADDONS.map(id=>offered.find(a=>a.id===id)).filter(Boolean);
 const others=offered.filter(a=>!ESSENTIAL_ADDONS.includes(a.id));
 const added=others.filter(a=>Q.line(a,state).selected).length;
 /* A bring-your-own-bar package puts no Barsys glassware in the room. */
 const scope=Q.bringsOwnBar(C.packages[state.tier])?'':window.BarsysReadiness.glasswareMarkup(state,'detail');
 /* With only a couple of add-ons on offer there is nothing to recommend between, so the
    card drops the grouping rather than heading an empty grid. */
 if(!essentials.length)return `${cardMeta()}<h3 id="card-title" tabindex="-1">Anything else<br>for the room?</h3><p class="step-description">${esc(C.packages[state.tier].name)} brings its own bar, so this is a short list. All optional, all confirmed in your proposal.</p><div data-addon-host>${scope}${addonGrid(others)}</div><p class="card-tip">Add-ons show up in your estimate as you pick them. You can change any of this later.</p>`;
 return `${cardMeta()}<h3 id="card-title" tabindex="-1">What should we<br>bring with it?</h3><p class="step-description">Glassware, and the extras most ${esc(C.packages[state.tier].name)} events add. All optional, all confirmed in your proposal &mdash; nothing is charged here.</p><div data-addon-host><p class="mini-heading">RECOMMENDED ADD-ONS</p>${scope}${addonGrid(essentials)}${others.length?`<details class="addon-more" id="addon-more" ${added?'open':''}><summary>Other add-ons<span>${added?`${added} added`:`${others.length} more`}</span></summary>${addonGrid(others)}</details>`:''}</div><p class="card-tip">Add-ons show up in your estimate as you pick them. You can change any of this later.</p>`;
}
function whenCard(){return `${cardMeta()}<h3 id="card-title" tabindex="-1">Where's the good time?</h3><p class="step-description">The city is enough to start. Venue details can follow.</p><div class="field-grid"><div class="field field-full location-row">${field('city','City',{required:true,placeholder:'New York'})}${selectDetail('region','State',[['NY','New York'],['NJ','New Jersey'],['CT','Connecticut'],['Other','Other / to confirm']])}</div></div><div class="field"><span>Have a date in mind?</span><div class="date-choices" role="group" aria-label="Date preference"><button type="button" data-date="flexible" aria-pressed="${!dateDecided}">Still deciding</button><button type="button" data-date="chosen" aria-pressed="${dateDecided}">Choose a date</button></div><div class="date-field" ${dateDecided?'':'hidden'}>${field('date','Preferred date',{type:'date'})}</div></div><p class="field-hint">Not in New York City? Your details are kept for a custom quote. No date is held by this plan.</p>${window.BarsysReadiness.eventFields(state)}`;}
function contactMarkup(){return `<div class="field-grid">${field('name','Your full name',{required:true,placeholder:'Alex Morgan'})}${field('company','Company',{required:corporate(),placeholder:corporate()?'Your company':'Optional for private events'})}${field('email',corporate()?'Work email':'Email',{type:'email',required:true,placeholder:'alex@example.com'})}${field('phone','Phone',{type:'tel'})}<div class="field field-full"><label for="detail-notes">Anything else? <small>Optional</small></label><textarea id="detail-notes" data-field="notes" maxlength="2000" placeholder="Preferred brands, branding details, access requirements or the occasion.">${esc(state.details.notes)}</textarea></div></div>`;}
function miniReview(){const t=estimate();return `<div class="compact-review"><div><p>${state.guests} guests &middot; ${esc(C.packages[state.tier].name)} &middot; ${esc(state.details.city||'Location to confirm')}</p><small>${esc(friendlyDate())}${state.details.startTime?' / '+state.details.startTime+' ET':''} &middot; ${esc(serviceLabel())}${state.menus.length?' &middot; '+state.menus.length+' menu preference'+(state.menus.length===1?'':'s'):''} &middot; ${t.subtotal===null?'Custom quote':money(t.subtotal)+' est. subtotal'}</small></div><button type="button" data-open-sheet="estimate">Review estimate</button></div>`;}
function contactCard(){return `${cardMeta()}<h3 id="card-title" tabindex="-1">Put a name to<br>the good time.</h3><p class="step-description">Add your details to the plan. ${CONNECTED?'':'Nothing is sent in this preview.'}</p>${contactMarkup()}${miniReview()}${window.BarsysReadiness.consentLine(state,'detail')}<label class="quick-privacy quick-remember"><input id="quick-remember" type="checkbox"/><span>Remember my selections on this device</span></label>`;}
function successCard(){return `${cardMeta()}<div class="success-icon">${icon('check')}</div><h3 id="card-title" tabindex="-1">${CONNECTED?(LIVE_MODE?'Inquiry sent.':'Test inquiry saved.'):'Your plan is ready.'}</h3><p class="step-description">${CONNECTED?(LIVE_MODE?`We'll be in touch at <strong>${esc(state.details.email)}</strong> to confirm availability, menus and scope. Nothing is booked or charged.`:`Saved to the ${RUNTIME_MODE==='LOCAL_TEST'?'local':'staging'} database. Nothing was sent to the event team.`):'<strong>Nothing has been sent, booked or charged.</strong>'}</p>${receiptId?`<p class="field-hint">Reference ${esc(receiptId)}</p>`:''}<div class="success-receipt"><span><small>YOUR GUESTS</small>${state.guests}</span><span><small>YOUR PACKAGE</small>${esc(C.packages[state.tier].name)}</span><span><small>YOUR CITY</small>${esc(state.details.city||'To confirm')}</span></div><div class="success-actions">${CONNECTED?'':'<button type="button" class="button" data-open-summary>View event summary '+icon('arrow')+'</button>'}<button type="button" class="button button-outline" data-download-summary>Download summary</button>${CONNECTED?'':'<button type="button" class="text-link" data-copy-summary>Copy the details</button>'}</div><button type="button" class="text-link" id="edit-plan">Edit my plan ${icon('arrow')}</button>`;}
function reviewMarkup(){const t=estimate();const rows=[['Your event',`${eventName()} / ${state.guests} guests`,0],['Date & time',friendlyDate()+(state.details.startTime?' / '+state.details.startTime+' ET':''),2],['Location',[state.details.city,state.details.region,state.details.venueType].filter(Boolean).join(' / '),2],['Duration',serviceLabel(),0],['Experience',C.packages[state.tier].name,1],['Program',state.program==='single'?'Single event':`${state.frequency} / ${state.commitment} / ${state.billing} billing (requested)`,1],['Menu preferences',menuLabel(),0],['Beverage preference',state.beverage==='zero'?'Entirely zero proof':state.beverage==='mixed'?'Cocktails + mocktails':'Help choosing',0],...window.BarsysReadiness.summaryRows(state),['Add-ons',t.lines.filter(l=>l.selected).map(l=>`${l.name}${l.quantity>1?' x '+l.quantity:''}${l.variantLabel?' / '+l.variantLabel:''} / ${l.status==='included'?'included':l.status==='priced'?money(l.total):'quote pending'}`).join('\n')||'None requested',1]];return `<dl class="review-grid">${rows.map(([k,v])=>`<div class="review-item"><dt>${esc(k)}</dt><dd>${esc(v).replace(/\n/g,'<br>')}</dd></div>`).join('')}</dl>`;}
/* ---- Deck navigation ---- */
function renderCard(direction='none',focus=true){
 $('#flashcard').className='flashcard'+(direction==='none'?'':' '+direction);
 $('#step-content').className=flipped?'card-package-back':['card-guest','card-package','card-addons','card-when','card-contact','card-success'][step];
 $('#step-content').innerHTML=flipped?packageBack():[guestCard,packageCard,addonsCard,whenCard,contactCard,successCard][step]();
 $('#step-content').scrollTop=0;
 $('#previous-card').hidden=step===0||step===5;
 $('#next-card').type=step===5?'button':'submit';
 $('#next-card').innerHTML=step===5?`Back to website ${icon('arrow')}`:step===4?`${CONNECTED?(LIVE_MODE?'Send inquiry':'Save test inquiry'):'Create local event plan'} ${icon('check')}`:`Continue ${icon('arrow')}`;
 $('#open-customize').hidden=step===5;
 $('#keyboard-hint').hidden=step>=4;
 renderStepNav();syncGuestInputs();updateDeckTotals();updateDock();
 if(focus){$('#card-title')?.focus({preventScroll:true});$('#planner-announcement').textContent=step===5?'Local plan ready. Nothing sent or booked.':`Card ${step+1} of ${cardTitles.length}. ${cardTitles[step]}.`;}
}
function renderStepNav(){$('#step-nav').innerHTML=cardTitles.map((name,i)=>`<button type="button" data-card-step="${i}" ${step===i?'aria-current="step"':''} ${i>furthest?'disabled':''} aria-label="Card ${i+1}: ${name}${i>furthest?', complete the previous cards first':''}"><span>${String(i+1).padStart(2,'0')}</span><b>${name}</b></button>`).join('');}
function showCardError(text,el){$('#form-error').textContent=text;$('#form-error').hidden=false;if(el){el.setAttribute('aria-invalid','true');el.setAttribute('aria-describedby',[...(el.getAttribute('aria-describedby')||'').split(' ').filter(Boolean).filter(x=>x!=='form-error'),'form-error'].join(' '));for(let parent=el.parentElement;parent;parent=parent.parentElement)if(parent.tagName==='DETAILS')parent.open=true;el.focus();}}
function validateCard(){
 if(step===0){const el=$('#card-guests');const n=Number(el.value);if(!el.value||!Number.isInteger(n)||n<1||n>C.quoteRules.maxInquiryGuests){showCardError(`Enter a whole number from 1 to ${C.quoteRules.maxInquiryGuests.toLocaleString()}.`,el);return false;}setGuests(n,el);return true;}
 if(step===3){const city=$('#detail-city');city.value=city.value.trim();state.details.city=city.value;if(!city.value){showCardError('Add the event city so we can scope your plan.',city);return false;}const dateEl=$('#detail-date');if(dateDecided){if(!dateEl.value){showCardError('Choose a date, or select Still deciding.',dateEl);return false;}if(dateEl.value<todayISO()){showCardError('Choose today or a future date, or keep the date flexible.',dateEl);return false;}state.details.date=dateEl.value;}else state.details.date='';return true;}
 if(step===4){
  for(const f of $$('input,select,textarea',$('#step-content'))){if(f.disabled)continue;if(['text','email'].includes(f.type))f.value=f.value.trim();if(f.dataset.field)state.details[f.dataset.field]=f.value;f.removeAttribute('aria-invalid');if(!f.checkValidity()){showCardError(f.type==='email'?'Please enter a valid email address.':`Please check ${f.labels?.[0]?.textContent||'this field'}.`,f);return false;}}
  const t=estimate();
  if(t.menuOverflow){showCardError('Your menu preferences exceed this package. Open Menus & extras to remove a choice or add collection slots.');return false;}
  if(state.beverage==='zero'&&(state.menus.some(id=>!C.menus.find(m=>m.id===id)?.zeroProof)||Q.quantity(C.addons.find(a=>a.id==='beer-wine'),state)||Q.quantity(C.addons.find(a=>a.id==='spirits'),state))){showCardError('This plan is zero proof, but includes alcohol preferences. Review Menus & extras before saving.');return false;}
  if(!state.details.city.trim()||(state.details.date&&state.details.date<todayISO())){step=3;renderCard('backward');showCardError('Review the city and date before saving.');return false;}
  return true;
 }
 return true;
}
function goTo(n){if(!Number.isInteger(n)||n<0||n>4||n>furthest)return;if(n>step&&!validateCard())return;const prev=step;step=n;flipped=false;renderCard(n<prev?'backward':'forward');}
function advance(){if(step===5){document.dispatchEvent(new CustomEvent('barsys:close'));return;}if(flipped){flipped=false;renderCard('flip');return;}if(!validateCard())return;if(step===4){if(CONNECTED)sendInquiry();else submitLocalPlan();return;}step++;furthest=Math.max(furthest,step);renderCard('forward');}
async function sendInquiry(){const b=$('#next-card');b.disabled=true;b.textContent=LIVE_MODE?'Sending…':'Saving…';let receipt;try{if(!window.BarsysInquiry)throw new Error('Not sent. Email '+C.email+'.');receipt=await window.BarsysInquiry.send();}catch(error){b.disabled=false;renderCard('none',false);showCardError(error.message||'Not sent. Please try again.');return;}b.disabled=false;complete=true;receiptId=receipt.id;step=5;furthest=5;renderCard('forward');commit();}
function submitLocalPlan(){complete=true;receiptId=null;step=5;furthest=5;renderCard('forward');commit();}
/* ---- Customize / Estimate sheets ---- */
function renderCustom(restoreSelector){
 $$('[data-custom-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.customTab===customTab)));
 const body=$('#custom-body'),scroll=body.scrollTop;
 if(customTab==='menus'){
  const t=estimate();
  body.innerHTML=`<div class="beverage-options" role="group" aria-label="Beverage preference">${[['mixed','Cocktails + mocktails'],['zero','Entirely zero proof'],['recommend','Help me choose']].map(([id,label])=>`<button type="button" data-beverage="${id}" aria-pressed="${state.beverage===id}">${label}</button>`).join('')}</div><div class="menu-step-tools"><span class="selection-count"></span><button type="button" class="text-link" id="request-extra-menu">Request extra mixlist ${icon('plus')}</button></div>${t.menuOverflow?`<p class="wizard-notice">${t.menuOverflow} extra preference${t.menuOverflow===1?'':'s'} kept after your package change. Add slots or remove collections; nothing was discarded.</p>`:''}<div class="wizard-menu-search"><label><span class="sr-only">Search collections</span><input id="wizard-menu-search" type="search" placeholder="Search all collections" value="${esc(menuQuery)}"/></label><label class="filter-toggle"><input id="wizard-zero-filter" type="checkbox" ${menuZero?'checked':''}/>Zero proof only</label></div><div id="wizard-menu-host">${menuMarkup()}</div><div class="menu-help-row"><button type="button" class="text-link" data-open-menus>Browse ${C.menus.filter(availableMenu).length} ${C.packages[state.tier].name} collections ${icon('arrow')}</button></div><label class="recommend-choice choice"><input name="menu-mode" type="checkbox" ${state.menuMode==='recommend'?'checked':''}/><span><strong>Let the team recommend</strong><small>Keep any favorites as preferences; we'll help finalize the mix.</small></span></label><div class="field wizard-extra-fields"><label for="detail-restrictions">Ingredient restrictions or preferences <small>Optional</small></label><textarea id="detail-restrictions" data-field="restrictions" maxlength="2000" placeholder="Event-level requirements only. Avoid entering guests' personal medical information.">${esc(state.details.restrictions)}</textarea><small class="field-hint">Requests require team confirmation; this is not an allergen-free guarantee.</small></div>${window.BarsysReadiness.serviceMarkup(state)}`;
  initImages(body);updateMenuSelections();
 } else {
  body.innerHTML=`<div class="field-grid"><div class="field"><label for="occasion">Occasion</label><select id="occasion" name="occasion">${eventTypes.map(t=>`<option value="${t.id}" ${state.type===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></div>${selectDetail('venueType','Event setting',[['office','Office'],['rooftop','Rooftop'],['venue','Private venue'],['deciding','Still deciding']])}${field('startTime','Start time / Eastern Time',{type:'time'})}${hoursMarkup()}${field('budget','Approximate total budget',{type:'number',placeholder:'e.g. 5000'})}</div>${optionSelect('program','One event or a new tradition?',[['single','Single event'],['recurring','Recurring program']])}${state.program==='recurring'?`<div class="recurring-options"><p class="mini-heading">YOUR PREFERRED PROGRAM</p><div class="field-grid">${optionSelect('frequency','How often?',[['exploring','Still exploring'],['twice-monthly','Twice a month'],['monthly','Once a month'],['quarterly','Once a quarter']])}${optionSelect('commitment','Commitment preference',[['exploring','Discuss with the team'],['3-months','3 months'],['6-months','6 months'],['12-months','12 months']])}${optionSelect('billing','Billing preference',[['exploring','Discuss with the team'],['monthly','Monthly'],['quarterly','Quarterly'],['annual','Annual']])}</div><p>Preferences only. No contract, discount or billing terms are confirmed in this preview.</p></div>`:''}`;
 }
 if(restoreSelector){body.scrollTop=scroll;$(restoreSelector,body)?.focus({preventScroll:true});}
 updateDeckTotals();
}
function renderEstimateSheet(){const t=estimate();$('#estimate-body').innerHTML=`<dl class="review-grid"><div class="review-item"><dt>Guests</dt><dd>${state.guests}</dd></div><div class="review-item"><dt>Package</dt><dd>${esc(C.packages[state.tier].name)}</dd></div><div class="review-item"><dt>Where</dt><dd>${esc([state.details.city,state.details.region].filter(Boolean).join(', ')||'To confirm')}</dd></div><div class="review-item"><dt>When</dt><dd>${esc(friendlyDate())}</dd></div><div class="review-item"><dt>Duration</dt><dd>${esc(serviceLabel())}</dd></div><div class="review-item"><dt>Menu preferences</dt><dd>${esc(menuLabel())}</dd></div></dl><div class="price-breakdown">${priceMarkup()}</div><div class="estimate-total"><span>Estimated subtotal</span><strong>${t.subtotal===null?'Custom quote':money(t.subtotal)}</strong></div><p class="estimate-note">${estimateNote()}</p>`;}
function openSheet(id,from){lastDialogFocus=from||document.activeElement;if(id==='customize')renderCustom();if(id==='estimate')renderEstimateSheet();$('#'+id).showModal();$('#'+id+' .icon-button')?.focus({preventScroll:true});updateDock();}
function closeSheet(id){$('#'+id).close();if(lastDialogFocus?.isConnected)lastDialogFocus.focus({preventScroll:true});if(id==='customize')renderCard('none',false);updateDock();}
/* ---- Resume dock ---- */
function updateDock(){const dock=$('#resume-dock');if(!dock)return;const hero=document.querySelector('.hero');const plannerOpen=document.body.classList.contains('planner-focus');const sheetOpen=!!document.querySelector('dialog[open]');dock.hidden=!document.body.classList.contains('plan-intent')||plannerOpen||sheetOpen||!hero||hero.getBoundingClientRect().bottom>80;}
function updateDeckTotals(){
 const t=estimate();
 const deckTotal=$('#deck-total');if(deckTotal)deckTotal.textContent=t.subtotal===null?'Custom quote':money(t.subtotal);
 const deckEx=$('#deck-exclusions');if(deckEx)deckEx.textContent=t.pending.length?`Before tax & venue costs; ${t.pending.length} extra${t.pending.length===1?'':'s'} to quote`:'Before tax, delivery & glassware';
 const count=state.menus.length;
 const badge=$('#custom-count');if(badge){badge.textContent=count;badge.hidden=!count;}
 const total=$('#custom-total');if(total)total.textContent=`${t.subtotal===null?'Custom quote':money(t.subtotal)} estimated subtotal`;
 const dockEst=$('#dock-estimate');if(dockEst)dockEst.textContent=`${state.guests} guests · ${t.subtotal===null?'Custom quote':money(t.subtotal)}`;
 const mobileDock=$('#mobile-plan-dock-price');if(mobileDock)mobileDock.textContent=t.subtotal===null?`${state.guests} guests · Custom quote`:`${state.guests} guests · ${money(t.subtotal)}`;
 $$('[data-package-subtotal]').forEach(el=>el.textContent=packageTotal(C.packages[el.dataset.packageSubtotal]));
 $$('[data-guest-count]').forEach(el=>el.textContent=state.guests);
 $$('[data-select-package]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.selectPackage===state.tier)));
 $$('.package-card').forEach(el=>el.classList.toggle('is-selected',el.classList.contains(state.tier)));
 document.dispatchEvent(new CustomEvent('barsys:state'));
}
function exportData(){const t=estimate();return {mode:'LOCAL_PREVIEW_NOT_SENT',createdAt:new Date().toISOString(),sourceReviewed:C.quoteRules.sourceReviewed,event:{occasion:eventName(),guests:state.guests,package:C.packages[state.tier].name,serviceHours:state.serviceHours,includedServiceHours:2,beveragePreference:state.beverage,menus:menuNames(),menuRecommendationRequested:state.menuMode==='recommend',includedMenuCount:t.includedMenus,additionalMenuSlots:t.menuLimit-t.includedMenus,addons:t.lines.filter(l=>l.selected),enhancements:t.lines.filter(l=>l.selected).map(l=>l.name),program:state.program,requestedCadence:state.program==='recurring'?state.frequency:null,commitmentPreference:state.program==='recurring'?state.commitment:null,billingPreference:state.program==='recurring'?state.billing:null},contact:{...state.details},readiness:window.BarsysReadiness.exportMeta(state),estimate:{...t,excludesUnpricedRequests:true,recurringDiscountApplied:false,note:estimateNote()}};}
function downloadPlan(){const u=URL.createObjectURL(new Blob([JSON.stringify(exportData(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='Barsys-Local-Event-Plan.json';document.body.append(a);a.click();a.remove();toast('JSON download requested. Check your browser downloads.');setTimeout(()=>URL.revokeObjectURL(u),3000);}
async function copyPlan(){const e=exportData(),t=e.estimate;const text=['BARSYS / EVENT SUMMARY',`${e.event.occasion} | ${e.event.guests} guests | ${e.event.package}`,`${friendlyDate()} | ${state.details.startTime||'Time undecided'} | ${serviceLabel()}`,`Location: ${state.details.city}, ${state.details.region}`,`Contact: ${state.details.name} | ${state.details.email}`,`Menus: ${menuLabel()}`,`Add-ons: ${e.event.addons.map(l=>`${l.name} x ${l.quantity}${l.variantLabel?' ('+l.variantLabel+')':''} - ${l.status==='included'?'Included':l.total===null?'Quoted separately':money(l.total)}`).join('; ')||'None'}`,`Subtotal before tax: ${t.subtotal===null?'Custom quote':money(t.subtotal)}`,'Tax: to be confirmed',`Delivery/access: ${t.scopeCosts.map(l=>l.name+' - '+l.label).join('; ')}`,`Venue permission: ${window.BarsysReadiness.label('venueApproval',state.details.venueApproval)}`,`COI: ${window.BarsysReadiness.label('coi',state.details.coi)}`,`Glassware: ${window.BarsysReadiness.label('glassware',state.details.glassware)}`,`Publicity: ${window.BarsysReadiness.label('photoPreference',state.details.photoPreference)} - no permission granted`,`Marketing: ${state.details.marketingInterest==='yes'?'interested; not subscribed':'no opt-in'}`,`Program: ${e.event.program}`,estimateNote()].join('\n');try{await navigator.clipboard.writeText(text);toast('Summary copied.');}catch(_){toast('Clipboard unavailable. Download the summary instead.');}}
function resetPlan(){state=defaults();menuQuery='';menuZero=false;$('#menu-search').value='';$('#zero-proof-filter').checked=false;guestDraft=String(state.guests);dateDecided=false;step=0;furthest=0;flipped=false;complete=false;receiptId=null;customTab='menus';if($('#customize').open)$('#customize').close();if($('#estimate').open)$('#estimate').close();try{localStorage.removeItem(C.storageKey);}catch(_){}syncGuestInputs();renderCard('none',true);commit();toast('A fresh start. All entered details were cleared.');}
function renderDialog(){const q=$('#menu-search').value.toLowerCase(),z=$('#zero-proof-filter').checked;const match=C.menus.filter(m=>availableMenu(m)&&(!z||m.zeroProof)&&`${m.name} ${m.description}`.toLowerCase().includes(q));$('#dialog-menu-grid').innerHTML=state.menus.filter(id=>!Q.menuAvailable(id,state.tier,C)).map(id=>`<p class="wizard-notice">${esc(C.menus.find(m=>m.id===id)?.name)} is outside ${esc(C.packages[state.tier].name)}. <button type="button" data-select-menu="${id}">Remove preference</button></p>`).join('')+match.map(menuCard).join('')||'<p>No matching collections.</p>';initImages($('#dialog-menu-grid'));updateMenuSelections();}
function openMenus(){lastDialogFocus=document.activeElement;$('#menu-search').value='';$('#zero-proof-filter').checked=state.beverage==='zero';renderDialog();$('#menus-dialog').showModal();$('#menu-search').focus({preventScroll:true});}
function closeMobileNav(){$('#mobile-nav').hidden=true;$('.menu-toggle').setAttribute('aria-expanded','false');$('.menu-toggle').setAttribute('aria-label','Open navigation');$('.menu-toggle').innerHTML=icon('menu');}
  function imageSource(key) {
    const asset = C.assets[key];
    if (!asset) return '';
    const src=(window.BARSYS_LOCAL_ASSETS || []).includes(key) ? asset.local : asset.remote || asset.local;
    return src; // Company-owned artwork is ordinary page content, not a tracking category.
  }
  function setImage(img, key) {
    const asset = C.assets[key];
    if (!asset || !img) return;
    const frame = img.closest('[data-photo-frame], .menu-image, .taste-stage, .collection-cover');
    img.dataset.image = key;
    img.dataset.initialized = 'true';
    img.alt = asset.alt;
    img.referrerPolicy = 'no-referrer';
    if (frame) {
      frame.dataset.illustration = String(Boolean(asset.initialIllustration));
      delete frame.dataset.failed; delete frame.dataset.loaded;
    }
    img.onload = () => {
      if (frame) { frame.dataset.loaded = 'true'; delete frame.dataset.failed; }
    };
    img.onerror = () => {
      if (frame) { frame.dataset.failed = 'true'; delete frame.dataset.loaded; }
    };
    const src=imageSource(key);
    if(!src){img.removeAttribute('src');if(frame)frame.dataset.failed='true';return;}
    img.src=src;
  }
  function initImages(root = document) {
    $$('img[data-image]:not([data-initialized])', root).forEach(img => setImage(img, img.dataset.image));
  }
  function renderPackages() {
    const tiers = Object.entries(C.packages).filter(([, p]) => !Q.bringsOwnBar(p));
    const banners = Object.entries(C.packages).filter(([, p]) => Q.bringsOwnBar(p));
    $('#package-banner').innerHTML = banners.map(([id, p]) => `
      <section class="package-banner" data-reveal><div class="pb-row">
        <span class="pb-badge">${esc(p.badge)}</span><h3>${esc(p.name)}</h3>
        <p class="pb-price">${dollars(p.rate)}<span> / guest</span></p>
        <p class="pb-meta">${dollars(p.minimumFee)} minimum &middot; one iPad per ${p.guestsPerStation} guests</p>
      </div><p class="pb-tagline">${esc(p.tagline)}</p>
      <ul class="pb-features">${p.features.map(f=>`<li>${icon('check')}<span>${esc(f)}</span></li>`).join('')}</ul>
      <button type="button" class="pb-cta" data-select-package="${id}">Choose ${esc(p.name)}${icon('arrow')}</button></section>`).join('');
    $('#package-grid').innerHTML = tiers.map(([id, p], index) => `
      <article data-reveal class="package-card ${id}" aria-labelledby="package-${id}">
        <div class="package-top"><span class="package-type">${esc(p.positioning || `EXPERIENCE 0${index+1}`)}</span>${id === 'signature' ? `<span class="recommendation">${icon('spark')}THE SWEET SPOT</span>` : ''}</div>
        <h3 id="package-${id}">${esc(p.name)}</h3><p class="package-desc">${esc(p.description)}</p>
        <div class="package-price"><strong>${dollars(p.rate)}</strong><span>/ guest</span></div>
        <p class="event-subtotal"><span data-package-subtotal="${id}">${packageTotal(p)}</span> for <span data-guest-count>${state.guests}</span> guests &middot; before tax</p>
        <ul class="package-features">${p.features.map(feature => `<li>${icon('check')}${esc(feature)}</li>`).join('')}</ul>
        <button type="button" class="button ${id === 'signature' ? 'button-light' : 'button-outline'}" data-select-package="${id}">Choose ${esc(p.name)}${icon('arrow')}</button>
      </article>`).join('');
  }
  function renderFeaturedMenus() {
    $('#featured-menus').innerHTML = C.menus.filter(availableMenu).sort((a,b)=>Number(!!b.featured)-Number(!!a.featured)).map(m => `
      <article class="menu-card" data-collection="${m.id}" data-zero-proof="${!!m.zeroProof}"><button type="button" class="menu-image" data-preview-menu="${m.id}" data-photo-frame aria-label="Explore ${esc(m.name)}">
        <img data-image="${m.image}" width="1000" height="1000" loading="lazy" alt="${esc(C.assets[m.image].alt)}">
        <span class="photo-fallback" aria-hidden="true"><span class="cover-loading">BARSYS MIXLISTS</span><span class="cover-unavailable">Artwork unavailable<br><small>Check your connection. Collection details are still available.</small></span></span>
        <span class="menu-tag">${esc(m.tag)}</span></button>
        <h3>${esc(m.name)}</h3><p>${esc(m.description)}</p><button class="menu-details-link text-link" type="button" data-rich-menu="${m.id}">Explore this collection ${icon("arrow")}</button><div class="menu-card-footer"><span>${m.recipes} recipes ${m.zeroProof ? '&middot; Alcohol free' : ''}</span><button type="button" class="text-link" data-select-menu="${m.id}" aria-pressed="false">Add to my event${icon('plus')}</button></div>
      </article>`).join('');
    initImages($('#featured-menus'));document.dispatchEvent(new CustomEvent('barsys:menus'));
  }

document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;
if(b.hasAttribute('data-adjust-guests'))setGuests(Math.max(1,Math.min(10000,state.guests+Number(b.dataset.adjustGuests))));
if(b.hasAttribute('data-card-guest-delta')){const n=Math.max(1,Math.min(C.quoteRules.maxInquiryGuests,state.guests+Number(b.dataset.cardGuestDelta)));setGuests(n);guestDraft=String(state.guests);syncGuestInputs();}
if(b.hasAttribute('data-guests')){setGuests(Number(b.dataset.guests));guestDraft=String(state.guests);syncGuestInputs();}
if(b.hasAttribute('data-select-package')){setTier(b.dataset.selectPackage);document.dispatchEvent(new CustomEvent('barsys:open',{detail:{card:1}}));}
if(b.hasAttribute('data-select-menu'))toggleMenu(b.dataset.selectMenu);
if(b.hasAttribute('data-open-menus'))openMenus();
if(b.hasAttribute('data-preview-menu'))document.dispatchEvent(new CustomEvent('barsys:collection',{detail:b.dataset.previewMenu}));
if(b.hasAttribute('data-close-dialog'))$('#menus-dialog').close();
if(b.hasAttribute('data-card-step'))goTo(Number(b.dataset.cardStep));
if(b.hasAttribute('data-date')){dateDecided=b.dataset.date==='chosen';if(!dateDecided){state.details.date='';commit();}renderCard('none',false);$(dateDecided?'#detail-date':'[data-date="flexible"]')?.focus({preventScroll:true});}
if(b.id==='flip-card'){flipped=!flipped;renderCard('flip');}
if(b.id==='previous-card'){if(flipped){flipped=false;renderCard('flip');}else if(step>0){step--;renderCard('backward');}}
if(b.id==='open-customize')openSheet('customize',b);
if(b.id==='open-estimate'||b.hasAttribute('data-open-sheet'))openSheet('estimate',b);
if(b.hasAttribute('data-close-sheet'))closeSheet(b.dataset.closeSheet);
if(b.hasAttribute('data-custom-tab')){customTab=b.dataset.customTab;renderCustom();$('#custom-body').scrollTop=0;}
if(b.hasAttribute('data-beverage')){setOption('beverage',b.dataset.beverage);menuZero=b.dataset.beverage==='zero';if($('#customize').open&&customTab==='menus')renderCustom(`[data-beverage="${b.dataset.beverage}"]`);}
if(b.hasAttribute('data-addon')){const id=b.dataset.addon,a=C.addons.find(x=>x.id===id);const n=Q.quantity(a,state);setAddon(id,b.dataset.delta?n+Number(b.dataset.delta):n?0:1);refreshAddonHosts();}
if(b.id==='request-extra-menu')extraMenuRequest();
if(b.id==='edit-plan'){step=4;renderCard('backward');}
if(b.id==='download-plan')downloadPlan();
if(b.id==='copy-plan')copyPlan();
if(b.closest('#mobile-nav'))closeMobileNav();});
document.addEventListener('input',e=>{const f=e.target;if(f.matches('[data-guest-input]')){if(setGuests(Number(f.value),f)){f.removeAttribute('aria-invalid');guestDraft=String(state.guests);}else f.setAttribute('aria-invalid','true');}if(f.id==='card-guests'){guestDraft=f.value;f.classList.toggle('long-number',guestDraft.length>3);if(f.value&&f.checkValidity())setGuests(Number(f.value),f);else updateDeckTotals();}if(f.hasAttribute('data-field')){setDetails({[f.dataset.field]:f.value});f.removeAttribute('aria-invalid');$('#form-error').hidden=true;}if(f.id==='wizard-menu-search'){menuQuery=f.value.toLowerCase();updateMenuGrid();}});
document.addEventListener('change',e=>{const f=e.target;if(f.name==='occasion'){state.type=f.value;commit();}if(f.name==='tier'){setTier(f.value);}if(f.hasAttribute('data-field'))setDetails({[f.dataset.field]:f.value});if(f.hasAttribute('data-hours'))setHours(f.value);if(f.hasAttribute('data-option')){setOption(f.dataset.option,f.value);if(f.dataset.option==='program'&&$('#customize').open&&customTab==='details')renderCustom();}if(f.hasAttribute('data-addon-variant')){const a=C.addons.find(a=>a.id===f.dataset.addonVariant);setAddon(a.id,Q.quantity(a,state),f.value);refreshAddonHosts();}if(f.name==='menu-mode'){state.menuMode=f.checked?'recommend':'choose';commit();}if(f.id==='wizard-zero-filter'){menuZero=f.checked;updateMenuGrid();}});
$('#card-form').addEventListener('submit',e=>{e.preventDefault();advance();});
$('#reset-plan').addEventListener('click',resetPlan);
$('#recurring-link').addEventListener('click',()=>{setOption('program','recurring');document.dispatchEvent(new CustomEvent('barsys:open',{detail:{card:0,sheet:'details'}}));});
$('.menu-toggle').addEventListener('click',()=>{const open=$('#mobile-nav').hidden;$('#mobile-nav').hidden=!open;$('.menu-toggle').setAttribute('aria-expanded',String(open));$('.menu-toggle').setAttribute('aria-label',open?'Close navigation':'Open navigation');$('.menu-toggle').innerHTML=icon(open?'close':'menu');});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMobileNav();});
document.addEventListener('keydown',e=>{if(!document.body.classList.contains('planner-focus')||document.querySelector('dialog[open]'))return;const t=e.target;if(t.closest('input,select,textarea,button,a,summary'))return;if(e.key==='ArrowLeft'&&step>0&&step<5){e.preventDefault();step--;flipped=false;renderCard('backward');}if(e.key==='ArrowRight'&&step<4){e.preventDefault();advance();}if(e.key==='Enter'&&step<3){e.preventDefault();advance();}});
for(const id of ['customize','estimate'])$('#'+id).addEventListener('cancel',e=>{e.preventDefault();closeSheet(id);});
for(const id of ['customize','estimate'])$('#'+id).addEventListener('click',e=>{const d=e.currentTarget,r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))closeSheet(id);});
$('#menu-search').addEventListener('input',renderDialog);$('#zero-proof-filter').addEventListener('change',renderDialog);
$('#menus-dialog').addEventListener('close',()=>{if(lastDialogFocus?.isConnected)lastDialogFocus.focus({preventScroll:true});});
$('#menus-dialog').addEventListener('click',e=>{const d=e.currentTarget,r=d.getBoundingClientRect();if(e.target===d&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))d.close();});
window.addEventListener('scroll',()=>{$('.site-header').classList.toggle('scrolled',scrollY>25);updateDock();},{passive:true});
if('IntersectionObserver'in window)new IntersectionObserver(es=>es.forEach(e=>$('#mobile-book').classList.toggle('suppressed',e.isIntersecting))).observe($('#proposal'));
window.addEventListener('resize',()=>{if(innerWidth>=800)closeMobileNav();},{passive:true});
$('#year').textContent=new Date().getFullYear();loadDraft();renderPackages();renderFeaturedMenus();renderCard('none',false);syncGuestInputs();initImages();
window.BarsysPlanner=Object.freeze({getState:()=>JSON.parse(JSON.stringify(state)),getEstimate:estimate,exportData,setGuests,setTier,toggleMenu,copyPlan,downloadPlan,initImages,imageSource,setImage,toast,setDetails,setOption,setHours,setAddon,priceMarkup,estimateNote,corporate,serviceLabel,menuLabel,refreshAddonHosts,reviewMarkup,goStep(n){if(!Number.isInteger(n)||n<0||n>3)return;furthest=Math.max(furthest,n);step=n;flipped=false;renderCard('none',false);},
setOccasion(value){if(eventTypes.some(e=>e.id===value)){state.type=value;commit();}},refresh(){renderCard('none',false);},reset:resetPlan,openFull(){renderCard('none',false);},addMenu(id){if(!state.menus.includes(id))toggleMenu(id);return state.menus.includes(id);}});
window.BarsysPreview=Object.freeze({getState:()=>JSON.parse(JSON.stringify(state)),getEstimate:estimate,getStep:()=>step,isComplete:()=>complete});
})();
