/* Preview notices describe THIS local build. Event terms are a planning guide,
   not a universal adoption of the supplied customer's negotiated agreement. */
window.BARSYS_POLICIES={
 privacy:{title:'Privacy notice',tag:'THIS LOCAL PREVIEW / 09 SEPTEMBER 2026',body:`
 <p class="policy-lead">Your event details stay in this open page. This preview does not submit an inquiry, take payment or connect to a CRM.</p>
 <h3>Information you enter</h3><p>The wizard holds your contact details, event preferences and optional venue or ingredient notes in browser memory so you can review a plan. Only enter what is needed for your event. Do not include payment-card information, identity documents or named guests' medical information.</p>
 <h3>What is saved on your device</h3><p>Your privacy decision can be saved for up to 180 days. A motion preference is saved only when you choose it. With <strong>Remember event selections</strong> enabled, package, guest count, mixlists and other non-contact selections can be saved for up to 30 days. We exclude names, emails, phone numbers, dates, addresses, budget, free-text notes and permission choices from that saved draft.</p>
 <h3>Media and external connections</h3><p>Event films, event photos and logo assets are bundled in this copy. No third-party video player, analytics script or advertising pixel is installed. Company-owned menu artwork is normal page content and does not require a privacy-toggle choice. The page uses local covers when available; unbundled covers load automatically from media.barsys.com when needed. The image host receives a normal web request, including connection information such as your IP address; form values are not attached to it and images use a no-referrer policy. The host's own logging and retention have not been verified.</p>
 <h3>Your deliberate actions</h3><p>Copy, download and print actions put the details you entered into a clipboard or local file. Keep those exports private and share them deliberately. Email and original-source links open outside this page; contacting Barsys by email or visiting another site is not controlled by these preview settings.</p>
 <h3>Your controls</h3><p>Open <button class="policy-inline" type="button" data-open-privacy>Privacy preferences</button> at any time to turn off optional draft storage. Turning off draft storage deletes this copy's saved draft but leaves your current open plan intact. The storage choice does not block menu images or bundled event media. Use <strong>Start over</strong> to clear the in-page plan. Downloaded files and clipboard copies must be removed separately.</p>
 <h3>Scope and contact</h3><p>This notice covers this downloadable prototype, not all Barsys websites or a future production service. Direct-file browser storage may behave differently from storage on a hosted website. Contact <a href="mailto:fareed@barsys.com">fareed@barsys.com</a> with an event or privacy question. Before production, the business must approve its actual recipients, retention, security, vendors, contact details and applicable privacy rights.</p>`},
 terms:{title:'Event service terms',tag:'PLANNING GUIDE / FINAL AGREEMENT REQUIRED',body:`
 <p class="policy-lead">A plan is the start of the conversation, not a reservation. Your event's signed agreement defines the scope, price and responsibilities.</p>
 <h3>From inquiry to confirmation</h3><p>This local build creates a preview only. The booking model reflected here requires both a signed event agreement and receipt of the required deposit before the date is held, followed by written confirmation from Barsys. Payment alone is not an executed agreement. Deposit amounts, payment dates and final terms must be stated in your event agreement.</p>
 <h3>Your agreed event scope</h3><p>Confirm the service window, guest count, package, machines, mixlists, glassware, staffing, setup and breakdown in writing. The on-page subtotal is a planning baseline, not the complete event price. Unpriced requests, delivery and access costs, tax, venue charges and any applicable payment fees must be resolved in the written proposal. Imagery does not promise a pictured venue, food, decorations or specific spirit brand.</p>
 <h3>Responsible alcohol service</h3><p>The sample service standards include measured pours, age-21-plus ID checks at the point of alcohol service, and the ability to refuse or stop service for underage, intoxicated or unsafe guests, or to suspend service for unsafe conduct. Open-bar language is subject to these safeguards. Outside beverages or competing bar service in the service area require prior written agreement. Confirm venue permission and applicable alcohol-service arrangements with the event team; this website is not evidence of a licence or permit.</p>
 <h3>Venue access and insurance paperwork</h3><p>The organizer is responsible for arranging the venue's consent where required. Introduce the event team to the building or facilities contact and confirm access, setup space, power and water for the agreed equipment configuration. Share any certificate-of-insurance request and exact additional-insured naming instructions in advance. Requirements, coverage and document availability need review; selecting a COI request in this wizard does not issue a certificate or confirm coverage.</p>
 <h3>Menus, allergens and changes</h3><p>Confirm menu selection and substitutions at the event-specific sign-off deadline. Drinks are prepared in a shared service environment; the absence of allergens cannot be guaranteed. Share event-level ingredient requirements with the team and inform guests of the agreed limitations. Additional guests, menu changes or extra time may affect cost. Event-day extensions require authorization by the agreed on-site lead and staff availability; no automatic extension or universal overtime rate is promised.</p>
 <h3>Photography and business information</h3><p>Station and drink photography, any dedicated photographer, delivery of content and publication rights need their own written scope. A contact form or marketing preference is not a guest-photo release. The source agreement requires prior written client approval for publication of individually identifiable guests, and limits name/logo use to the specific collaboration. Confirm all permissions needed for the intended use. Non-public proposals and negotiated commercial information are not public case studies.</p>
 <h3>Agreement controls</h3><p>Barsys, Inc. and the authorized contracting entity must be identified in the final agreement. Your organizer contact may be different from that entity. This guide intentionally does not adopt a sample client's prices, deposit percentage, cancellation schedule, grace headcount, insurance limits or liability provisions as company-wide policy. Review the completed agreement before signing.</p>`},
 cancellations:{title:'Cancellations & rescheduling',tag:'EVENT-SPECIFIC TERMS / NOT A REFUND CALCULATOR',body:`
 <p class="policy-lead">There is no booking, payment or cancellation charge in this preview. For a booked event, check the signed agreement before making a change.</p>
 <h3>What must be confirmed in your proposal</h3><p>Your written terms should specify cancellation notice cutoffs, how notice is delivered and acknowledged, the timezone, the basis for any retained amount, the liability cap if any, and whether rescheduling is available. No universal percentage, refund period or rescheduling guarantee has been approved in this build.</p>
 <h3>Different circumstances need different treatment</h3><p>Client cancellation, a date-change request, Barsys cancellation and disruptions outside either party's control must be considered separately. The supplied example agreement includes different provisions for those situations, but its negotiated amounts and time windows are not applied to other events here.</p>
 <h3>Request a change</h3><p>Contact the event team using the notice details in your agreement. For a planning question, email <a href="mailto:fareed@barsys.com">fareed@barsys.com</a>. A message from this website does not itself cancel, reschedule or refund an event. Ask for written acknowledgment and confirmation of the financial effect before treating a change as agreed.</p>
 <h3>Before publication</h3><p>The business must approve precise, non-overlapping cancellation boundaries and final refund terms before enabling a payment or cancellation workflow. This preview does not determine an entitlement or override an existing agreement.</p>`},
 cookies:{title:'Cookies & browser storage',tag:'TECHNICAL INVENTORY / THIS BUILD ONLY',body:`
 <p class="policy-lead">This preview does not set cookies or install analytics, advertising tags, session replay, or third-party video players.</p>
 <div class="policy-table-wrap"><table><thead><tr><th>Item</th><th>Purpose and control</th><th>Retention</th></tr></thead><tbody>
 <tr><td>barsys-privacy-v38</td><td>Stores your explicit privacy choice on this device. No contact fields.</td><td>Up to 180 days</td></tr>
 <tr><td>barsys-v2-motion</td><td>Remembers an explicit motion on/off preference.</td><td>Until cleared</td></tr>
 <tr><td>barsys-local-draft-v38</td><td>Optional non-contact event selections. Written only with Remember event selections enabled.</td><td>Up to 30 days</td></tr>
 <tr><td>Barsys menu artwork</td><td>Normal image delivery, independent of optional draft storage. Local covers are preferred; missing covers use the configured Barsys image host.</td><td>Host/cache behavior not controlled by this page</td></tr></tbody></table></div>
 <p>Expired entries are removed or ignored the next time this copy runs; this page does not run in the background after you close it. Direct-file storage support varies by browser. Other downloaded copies may have separate storage areas.</p>
 <h3>Change your decision</h3><p><button class="policy-inline" type="button" data-open-privacy>Open Privacy preferences</button> to change or clear these settings. Your current in-memory plan is separate from stored choices. Use Start over in the planner to clear it.</p>
 <h3>Production changes</h3><p>A future hosted version must inventory its real scripts, cookies, vendors and server logs, then update both the controls and this notice. No consent checkbox here authorizes unlisted trackers. Do not add third-party tags without implementing and testing the corresponding controls.</p>`},
 accessibility:{title:'Accessibility & help',tag:'FEATURES IMPLEMENTED / NOT A CONFORMANCE CLAIM',body:`
 <p class="policy-lead">Explore the event and plan at your own pace. Motion can be paused without losing access to the content.</p>
 <h3>Controls in this preview</h3><p>The page includes a skip link, visible keyboard focus, labeled inputs, error messages, and native dialogs that support Escape and restore focus. Carousel arrows and media controls are buttons. The hero stops automatic slide rotation after keyboard focus enters, until you explicitly resume it. Global motion, banner and video controls remain available; reduced-motion preferences disable automatic movement.</p>
 <h3>Media alternatives</h3><p>Bundled event films are silent. Each full-film dialog includes a written description of the visual action. The event-photo section also offers an expandable list of all film descriptions. Images have descriptive alternative text or empty alternative text when decorative. These descriptions do not identify guests, establish a recipe, or imply that a pictured venue is included.</p>
 <h3>Need assistance?</h3><p>Email <a href="mailto:fareed@barsys.com">fareed@barsys.com</a> with the section or step that caused difficulty and the assistance you need. Please do not send sensitive personal information. An alternative event-planning conversation can be requested.</p>
 <h3>Testing limits</h3><p>This is a tested prototype, not a claim of complete WCAG conformance or legal compliance. A production audit must include representative assistive technologies, browsers, mobile devices, third-party content and the live submission flow. New content and integrations need fresh testing.</p>`},
 references:{title:'About the names & event images',tag:'EDITORIAL REFERENCES / COMPANY ASSETS',body:`
 <p class="policy-lead">The moving banner carries names from the original Barsys landing page. They do not all represent the same relationship.</p>
 <p>A company name, publication or event location is not an automatic endorsement. These names are retained as references from the original Barsys landing page; this banner does not claim that every company is a client, partner or sponsor. No unverified rating or customer quotation has been added.</p>
 <p>The project owner has confirmed that the supplied Barsys website, uploads and shared Drive libraries are company-owned assets authorized for this landing-page project. Source records retain that confirmation. This is a record of owner authorization, not an independent audit of third-party rights. A future event's publicity preference remains separate from its booking and marketing choices.</p>
 <p>The editable project includes an asset register recording the owner authorization and source mappings. Any specific restrictions encountered should be recorded without reopening ownership questions for every company asset. Banner relationships and the other operational and production launch items still require verification. The confidential sample event proposal is not bundled with this website.</p>`}
};
