import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createStore} from '../backend/store.mjs';
import {createAPI} from '../backend/api.mjs';
import {validate,estimate} from '../backend/model.mjs';
const testAuth={clientId:'test-client',user:async()=>({email:'test@example.com'}),require:async()=> 'fareed@barsys.com'};
const sample=()=>({schemaVersion:1,type:'team',guests:50,tier:'signature',menus:[],menuMode:'recommend',addons:{},program:'single',frequency:'exploring',commitment:'exploring',billing:'exploring',beverage:'mixed',serviceHours:2,details:{name:'Backend Test',email:'test@example.com',company:'Test Company',phone:'',date:'',startTime:'',timezone:'America/New_York',city:'New York',region:'NY',venue:'',venueType:'office',budget:'',restrictions:'',notes:'',venueApproval:'not-checked',coi:'unsure',glassware:'discuss',contractEntity:'',marketingInterest:'no',photoPreference:'discuss'}});
test('server ignores forged prices and preserves unknown amounts',()=>{const p=sample();p.estimate={total:1};p.guests=10;const s=validate(p);assert.equal(s.estimate,undefined);assert.equal(estimate(s).subtotal,null);p.guests=50;const q=estimate(validate(p));assert.equal(q.base,4250);assert.equal(q.tax,null);assert.equal(q.total,null);});
test('invalid fields, addon IDs, dates, durations and enums rejected',()=>{for(const change of [p=>p.guests=0,p=>p.guests=1.5,p=>p.tier='__proto__',p=>p.details.email='bad',p=>p.details.date='2099-02-30',p=>p.details.startTime='25:00',p=>p.details.marketingInterest='subscribed',p=>p.details.budget='-3',p=>p.details.notes='x'.repeat(2001),p=>p.addons={unknown:{quantity:1}},p=>p.serviceHours=3,p=>p.menus=['unknown']]){const p=sample();change(p);assert.throws(()=>validate(p),e=>e.status===422);}});
test('all frontend options, retained conflicts and recurring requests survive',()=>{const p=sample();p.program='recurring';p.serviceHours=3;p.addons={'extra-hours':{quantity:1,variant:''}};p.details.city='Jersey City';p.details.region='NJ';p.details.marketingInterest='yes';const q=estimate(validate(p));assert.equal(q.subtotal,null);assert.equal(q.addOnTotal,500);assert.ok(q.reasons.some(r=>r.startsWith('Recurring')));});
test('durable API, retries, concurrent updates, privacy and auth',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'barsys-api-'));let store=await createStore({filename:join(dir,'test.sqlite')});let handler;const server=http.createServer((req,res)=>handler(req,res));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;handler=createAPI({store,origin,auth:testAuth});
 t.after(async()=>{await new Promise(r=>server.close(r));await store.close();await rm(dir,{recursive:true,force:true});});
 const request=(path,method='GET',payload,headers={})=>fetch(origin+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...headers},...(payload!==undefined?{body:JSON.stringify(payload)}:{})});
 const key=randomUUID();const responses=await Promise.all(Array.from({length:4},()=>request('/api/inquiries','POST',sample(),{'Idempotency-Key':key})));assert.ok(responses.every(r=>[200,201].includes(r.status)));const receipts=await Promise.all(responses.map(r=>r.json()));assert.equal(new Set(receipts.map(r=>r.id)).size,1);assert.equal(receipts[0].mode,'LOCAL_TEST');assert.equal(receipts[0].booked,false);assert.equal(receipts[0].payload,undefined);
 const id=receipts[0].id;assert.equal((await request('/api/inquiries','POST',{...sample(),guests:60},{'Idempotency-Key':key})).status,409);
 assert.equal((await request('/api/inquiries','POST',sample(),{Origin:'https://attacker.example','Idempotency-Key':randomUUID()})).status,403);
 assert.equal((await request('/api/inquiries','POST',sample(),{'Content-Type':'text/plain','Idempotency-Key':randomUUID()})).status,415);
 assert.equal((await request('/api/inquiries','POST',{...sample(),details:{...sample().details,notes:'x'.repeat(70000)}},{'Idempotency-Key':randomUUID()})).status,413);
 let list=await (await request('/api/admin/inquiries')).json();assert.equal(list.items.length,1);assert.equal(list.items[0].estimate.base,4250);
 const patch={version:1,status:'contacted',owner:'Event team',note:'Follow up tomorrow'};const updates=await Promise.all([request('/api/admin/inquiries/'+id,'PATCH',patch),request('/api/admin/inquiries/'+id,'PATCH',patch)]);assert.deepEqual(updates.map(r=>r.status).sort(),[200,409]);
 await store.close();store=await createStore({filename:join(dir,'test.sqlite')});handler=createAPI({store,origin,auth:testAuth});let doc=await (await request('/api/admin/inquiries/'+id)).json();assert.equal(doc.status,'contacted');assert.equal(doc.history.length,2);assert.equal(doc.booking.confirmed,false);assert.equal(doc.payload.details.marketingInterest,'no');
 const retry=await request('/api/inquiries','POST',sample(),{'Idempotency-Key':key});assert.equal(retry.status,200);assert.equal((await retry.json()).id,id);
 handler=createAPI({store,local:false,origin:'https://barsys.example',auth:{...testAuth,require:async()=>{const e=new Error('Sign-in required');e.status=401;throw e;}}});
 assert.equal((await request('/api/admin/inquiries','GET',undefined,{Origin:'https://barsys.example'})).status,401);
 assert.equal((await request('/api/admin/inquiries','GET',undefined,{Origin:'https://barsys.example',Authorization:'Bearer '+'a'.repeat(40)})).status,401);
});
test('production access fails closed without secrets',()=>assert.throws(()=>createAPI({local:false,store:{},auth:testAuth}),/Production requires/));
test('temporary storage failure never reports success',async t=>{const origin='http://localhost';const handler=createAPI({origin,auth:testAuth,store:{findKey:async()=>{throw new Error('sensitive database secret');}}});const {Readable}=await import('node:stream');const req=Readable.from([Buffer.from(JSON.stringify(sample()))]);Object.assign(req,{url:'/api/inquiries',method:'POST',headers:{origin,'content-type':'application/json','idempotency-key':randomUUID()},socket:{remoteAddress:'127.0.0.1'}});let status,body;await handler(req,{writeHead:s=>status=s,end:s=>body=s});assert.equal(status,503);assert.ok(!body.includes('sensitive'));});
