import test from 'node:test';import assert from 'node:assert/strict';
import {defaultPreparation,validatePreparation,preparationSummary,recipeCatalog} from '../backend/preparation.mjs';
import {costSummary,validateCosts} from '../backend/costing.mjs';
const payload={guests:10,menus:['signature','vibrant'],menuMode:'choose'};
function fixture(){const plan=defaultPreparation(payload);plan.drinksPerGuest=1;plan.recipes.forEach((r,i)=>{r.share=i===0||i===4?1:0;r.confirmed=true;r.ingredients=[{name:'Test liquid',amount:60,unit:'ml'}];});return plan;}
const catalog={checkedAt:'2026-09-09',items:[{name:'Test liquid',unit:'ml',packAmount:750,priceCents:1500}]};
test('shared ingredients are rounded to packs after combining mixlists',()=>{const p=fixture(),s=preparationSummary(payload,p),c=costSummary(payload,p,s,catalog);assert.equal(c.totalUsedCents,1200);assert.equal(c.totalPurchaseCents,1500);assert.equal(c.rows[0].packs,1);assert.deepEqual(c.menus.map(m=>m.totalCents),[600,600]);});
test('unknown prices and different units never masquerade as complete totals',()=>{const p=fixture();p.recipes[0].ingredients.push({name:'Test liquid',amount:1,unit:'pinch'});const c=costSummary(payload,p,preparationSummary(payload,p),catalog);assert.equal(c.complete,false);assert.equal(c.missing,1);assert.equal(c.totalUsedCents,null);assert.equal(c.knownUsedCents,1200);assert.equal(c.rows.find(r=>r.unit==='pinch').price,null);});
test('event overrides are validated, used, and exported without changing catalog prices',()=>{const p=fixture();p.costOverrides=validateCosts([{name:'Test liquid',unit:'ml',packAmount:500,priceCents:1000,supplier:'QA supplier'}]);const c=costSummary(payload,p,preparationSummary(payload,p),catalog);assert.equal(c.totalPurchaseCents,2000);assert.equal(c.rows[0].price.source,'Staff-entered event estimate');assert.equal(c.rows[0].reference.priceCents,1500);for(const x of [{packAmount:0},{priceCents:-1},{priceCents:1.1},{supplier:''},{unit:'bottle'}])assert.throws(()=>validateCosts([{...p.costOverrides[0],...x}]),e=>e.status===422);});
test('unmeasured recipes and unset demand keep costs incomplete',()=>{const p=fixture();p.recipes[0].confirmed=false;let c=costSummary(payload,p,preparationSummary(payload,p),catalog);assert.equal(c.totalUsedCents,null);assert.equal(c.menus[0].unmeasured,1);p.drinksPerGuest=null;c=costSummary(payload,p,preparationSummary(payload,p),catalog);assert.equal(c.totalUsedCents,null);});
test('all verified CMS menus validate with original measurement units and mapping warnings',()=>{assert.equal(Object.keys(recipeCatalog.menus).length,27);for(const id of Object.keys(recipeCatalog.menus)){const e={...payload,menus:[id]};validatePreparation(defaultPreparation(e),e);}assert.match(preparationSummary({...payload,menus:['spritz']}).catalogWarnings[0],/mapping/);assert.match(preparationSummary({...payload,menus:['love']}).catalogWarnings[0],/compatible/);});
test('different ingredient names mapped to one catalog bottle share purchase rounding',()=>{const p=fixture();p.recipes[4].ingredients[0].name='Alias';const cat={...catalog,items:[...catalog.items.map(x=>({...x,url:'https://example.com/product'})),{...catalog.items[0],name:'Alias',url:'https://example.com/product'}]};const c=costSummary(payload,p,preparationSummary(payload,p),cat);assert.equal(c.totalPurchaseCents,1500);assert.equal(c.purchases.length,1);assert.equal(c.purchases[0].amount,600);});
test('a sourced fruit price without usable yield stays incomplete until staff supplies it',()=>{const p=fixture(),cat={...catalog,items:[{...catalog.items[0],packAmount:null,packLabel:'1 fruit'}]};let c=costSummary(payload,p,preparationSummary(payload,p),cat);assert.equal(c.yieldMissing,1);assert.equal(c.priceMissing,0);assert.equal(c.totalPurchaseCents,null);assert.equal(c.knownPurchaseCents,0);p.costOverrides=validateCosts([{name:'Test liquid',unit:'ml',packAmount:100,priceCents:1500,supplier:'Measured fruit yield'}]);c=costSummary(payload,p,preparationSummary(payload,p),cat);assert.equal(c.totalPurchaseCents,9000);assert.equal(c.yieldMissing,0);});
