import test from 'node:test';
import assert from 'node:assert/strict';
import {startFixture,syntheticInquiry,owner} from './lifecycle-fixture.mjs';
import {calculateProposal} from '../admin/proposal-model.js';

test('isolated inquiry-to-closeout rehearsal through authenticated HTTP APIs',async t=>{
  const f=await startFixture();t.after(()=>f.close());
  const req=f.request;
  const ok=async(path,options={},status=200)=>{const r=await req(path,options);assert.equal(r.status,status,`${path}: ${JSON.stringify(r.body)}`);return r.body;};
  let id,accepted,staffId,supplyId,machineId,loaded=[];
  const inquiry=syntheticInquiry();
  const eventPath=()=>'/api/admin/inquiries/'+id;
  const operations=async()=> (await ok('/api/admin/operations')).state;
  const op=async(action,payload={},expected=200)=>{
    const s=await operations();return ok('/api/admin/operations',{method:'POST',body:{version:s.version,action,payload:{eventId:id,...payload}}},expected);
  };
  const prep=()=>ok(eventPath()+'/preparation');
  const savePrep=async(view,plan=view.plan,expected=200)=>ok(eventPath()+'/preparation',{method:'PATCH',body:{version:view.version,operationsVersion:view.operationsVersion,plan}},expected);
  const finishStage=async()=>{const s=await operations(),stage=s.events[id].stage;for(let index=0;index<2;index++)await op('task',{stage,index,done:true});await op('advance');};
  await t.test('inquiry validation, duplicate retry, conflicting retry and access control',async()=>{
    assert.equal((await req('/api/admin/inquiries',{anonymous:true})).status,401);
    const key='synthetic-rehearsal-inquiry-0001';
    const created=await ok('/api/inquiries',{method:'POST',body:inquiry,key,anonymous:true},201);id=created.id;
    assert.equal(created.booked,false);
    assert.equal((await ok('/api/inquiries',{method:'POST',body:inquiry,key,anonymous:true})).id,id);
    assert.equal((await req('/api/inquiries',{method:'POST',body:{...inquiry,guests:26},key,anonymous:true})).status,409);
    assert.equal((await ok('/api/admin/inquiries')).items.length,1);
  });
  await t.test('proposal is saved, reviewed, accepted once and transferred without booking',async()=>{
    f.nextWindow();const p=await ok(eventPath()+'/proposal');
    Object.assign(p.plan,{billedGuests:25,graceGuests:0,rateCents:8500,taxMilliPercent:8875,expires:'2099-09-10',depositDue:'2099-09-10'});
    Object.assign(p.plan.details,{loadIn:'16:00',departure:'20:00',terms:'Synthetic rehearsal only.'});
    p.plan.lines=[{label:'Synthetic glassware',quantity:1,unitCents:0,taxable:true},{label:'Synthetic delivery',quantity:1,unitCents:10000,taxable:true}];
    for(const k of Object.keys(p.plan.confirmed))p.plan.confirmed[k]=true;
    accepted=calculateProposal(p.plan);
    assert.equal(accepted.totalCents,242247);assert.equal(accepted.depositCents+accepted.balanceCents,accepted.totalCents);
    const saved=await ok(eventPath()+'/proposal',{method:'PATCH',body:{version:p.version,plan:p.plan}});
    const s=await operations(),input={version:saved.version,operationsVersion:s.version,revision:saved.revision,confirmed:true,reference:'SYNTHETIC acceptance - not a client approval',acknowledgeImpact:true};
    await ok(eventPath()+'/accept-proposal',{method:'POST',body:{...input,previewOnly:true}});
    assert.equal((await ok(eventPath())).acceptances,undefined);
    await ok(eventPath()+'/accept-proposal',{method:'POST',body:input});
    assert.equal((await req(eventPath()+'/accept-proposal',{method:'POST',body:input})).status,409);
    const doc=await ok(eventPath()),e=(await operations()).events[id];
    assert.equal(doc.acceptances.length,1);assert.equal(e.revenueCents,222500);assert.equal(e.invoiceTotalCents,242247);
    assert.deepEqual(doc.booking,{confirmed:false,dateHeld:false,agreementSigned:false,paymentReceived:false});
  });
  await t.test('preparation changes invalidate checks and cannot override accepted machines',async()=>{
    f.nextWindow();let p=await prep(),changed=structuredClone(p.plan);changed.machines=2;
    for(const [k,n] of Object.entries({machines:2,cords:2,blocks:2,ipads:2,stands:2,shakers:4,funnels:2,glasses:4}))changed.equipment[k].quantity=n;
    await savePrep(p,changed,422);
    p.plan.drinksPerGuest=4;p=await savePrep(p);
    assert.equal(p.summary.totalDrinks,100);assert.equal(p.plan.menuConfirmed,false);
    assert.equal((await operations()).events[id].preparationNeedsReview,true);
    p.plan.menuConfirmed=true;p=await savePrep(p);
    assert.equal(p.summary.complete,true);assert.equal((await operations()).events[id].preparationNeedsReview,false);
  });
  await t.test('staff, deposits, receipts and reservations preserve exactly-once accounting',async()=>{
    f.nextWindow();await op('opening-zero');await op('staff',{name:'Synthetic Crew',role:'QA only',rateCents:5000,email:'',crewAccess:false});
    staffId=(await operations()).staff[0].id;
    const slot={staffId,role:'QA only',start:'2099-09-17T21:00:00Z',end:'2099-09-17T23:00:00Z',plannedHours:2,actualHours:null};
    await op('assign',slot);await op('assign',slot,422);
    await op('payment',{kind:'deposit',amountCents:accepted.depositCents,date:'2099-09-10',reference:'QA-DEPOSIT'});
    await op('payment',{kind:'deposit',amountCents:accepted.depositCents,date:'2099-09-10',reference:'QA-DEPOSIT'},422);
    const receipt={newItem:{name:'QA Mixer',kind:'consumable',unit:'ml'},quantity:1000,costCents:10000,paidCents:10000,supplier:'Synthetic supplier',reference:'QA-SUPPLY'};
    await op('receive-stock',receipt);await op('receive-stock',receipt,422);
    await op('receive-stock',{...receipt,newItem:{name:'QA Machine #001',kind:'equipment',unit:'each'},quantity:1,costCents:37500,paidCents:37500,reference:'QA-EQUIPMENT'});
    let s=await operations();supplyId=s.inventory.find(x=>x.name==='QA Mixer').id;machineId=s.inventory.find(x=>x.kind==='equipment').id;
    const times={start:'2099-09-17T20:00:00Z',end:'2099-09-18T01:00:00Z'};
    await op('reserve',{itemId:supplyId,quantity:1000,...times});await op('reserve',{itemId:machineId,quantity:1,...times});
    await op('reserve',{itemId:machineId,quantity:1,...times},422);
    const p=await prep();p.plan.bufferPercent=10;await savePrep(p,p.plan,422);
    assert.equal((await prep()).plan.bufferPercent,0);
  });
  await t.test('a stale preparation save cannot overwrite another operations update',async()=>{
    f.nextWindow();const stale=await prep();await op('task',{stage:0,index:0,done:true});
    stale.plan.equipment.shakers.packed=true;await savePrep(stale,stale.plan,409);
    assert.equal((await prep()).plan.equipment.shakers.packed,false);
    const s=await operations(),e=s.events[id];
    await op('event',{owner:'Synthetic QA Owner',due:'',notes:'Isolated rehearsal',revenueCents:e.revenueCents,targetMargin:80,leftoverCents:null,stockUsedCents:null,staffingConfirmed:true,actualHoursConfirmed:false,expenses:e.expenses.map((x,i)=>({plannedCents:i===2?2000:0,actualCents:i===2?2000:0,note:'Synthetic only'}))});
    await finishStage();await finishStage();await finishStage();
    assert.equal((await operations()).events[id].stage,3);
    const p=await prep();for(const x of Object.values(p.plan.equipment))if(x.quantity>0)x.packed=true;
    await savePrep(p);await op('advance',{},422);
  });
  await t.test('dispatch, event execution and partial returns cannot skip outstanding loads',async()=>{
    f.nextWindow();for(let index=0;index<2;index++)await op('task',{stage:3,index,done:true});
    await op('advance',{},422);
    loaded=(await operations()).reservations.filter(x=>x.eventId===id);
    for(const load of loaded)await op('dispatch',{id:load.id});
    await op('dispatch',{id:loaded[0].id},422);await op('advance');
    const p=await prep();p.plan.equipment.shakers.notes='Late change';await savePrep(p,p.plan,422);
    await finishStage();await finishStage();
    assert.equal((await operations()).events[id].stage,6);
    for(let index=0;index<2;index++)await op('task',{stage:6,index,done:true});
    await op('advance',{},422);
    f.nextWindow();
    const supply=loaded.find(x=>x.itemId===supplyId),machine=loaded.find(x=>x.itemId===machineId);
    await op('return',{id:supply.id,returned:250,lost:50,condition:'ready',note:''},422);
    await op('return',{id:supply.id,returned:250,lost:50,condition:'ready',note:'Synthetic spillage'});
    await op('return',{id:supply.id,returned:250,lost:50,condition:'ready',note:'Duplicate'},422);
    await op('advance',{},422);
    await op('return',{id:machine.id,returned:1,lost:0,condition:'charging',note:'Synthetic return'});
    await op('reserve',{itemId:machineId,quantity:1,start:'2099-09-19T20:00:00Z',end:'2099-09-20T01:00:00Z'},422);
    await op('advance');
    const s=await operations();assert.equal(s.events[id].stage,7);
    assert.equal(s.inventory.find(x=>x.id===supplyId).quantity,250);
    assert.equal(s.inventory.find(x=>x.id===supplyId).stockValueCents,2500);
    assert.equal(s.inventory.find(x=>x.id===machineId).stockValueCents,37500);
  });
  await t.test('payment correction, inventory valuation and closeout reconcile without altering revenue',async()=>{
    f.nextWindow();let s=await operations(),e=s.events[id],assignment=e.staffing[0];
    await op('assign',{...assignment,actualHours:2});
    await op('event',{owner:e.owner,due:e.due,notes:e.notes,revenueCents:e.revenueCents,targetMargin:e.targetMargin,leftoverCents:null,stockUsedCents:null,staffingConfirmed:true,actualHoursConfirmed:true,expenses:e.expenses});
    await op('payment',{kind:'payment',amountCents:accepted.balanceCents,date:'2099-09-18',reference:'QA-BALANCE'});
    await op('payment',{kind:'payment',amountCents:1000,date:'2099-09-18',reference:'QA-ENTRY-TO-CORRECT'});
    await op('payment',{kind:'refund',amountCents:1000,date:'2099-09-18',reference:'QA-COMPENSATING-REFUND'});
    await op('payment',{kind:'refund',amountCents:accepted.totalCents+1,date:'2099-09-18',reference:'QA-EXCESSIVE-REFUND'},422);
    const before=await ok('/api/admin/operations'),finance=before.financials[id];
    assert.equal(finance.payments.balanceCents,0);assert.equal(before.state.events[id].revenueCents,222500);
    assert.equal(finance.consumed,19500);assert.equal(finance.cash,59500);assert.equal(finance.profit,203000);
    assert.equal(finance.ledger.equipmentLossCents,0);
    await finishStage();s=await operations();assert.equal(s.events[id].stage,8);
    const p=await prep();p.plan.costOverrides.push({name:'QA only',unit:'ml',packAmount:1000,priceCents:100,supplier:'QA'});await savePrep(p,p.plan,422);
    await op('payment',{kind:'payment',amountCents:1,date:'2099-09-18',reference:'QA-CLOSED-WRITE'},422);
    const persisted=await f.store.get(id);assert.equal(persisted.acceptances.length,1);
    assert.equal(persisted.booking.confirmed,false);assert.equal(persisted.booking.paymentReceived,false);
    t.diagnostic('Synthetic HTTP lifecycle complete. Pre-tax revenue 222500 cents; tax 19747; gross 242247; consumed cost 19500; cash 59500; profit 203000. No external payments or messages.');
  });
});
