import test from 'node:test';import assert from 'node:assert/strict';import {emptyOperations,defaultEvent,applyOperation,finances} from '../backend/operations.mjs';
const E='00000000-0000-4000-8000-000000000001',F='00000000-0000-4000-8000-000000000002',actor='fareed@barsys.com',slot={start:'2026-10-01T12:00:00Z',end:'2026-10-01T22:00:00Z'};
const run=(s,action,payload)=>applyOperation(s,{action,payload},actor);
const stock=(kind='consumable',quantity=10)=>run(emptyOperations(),'inventory',{name:kind==='equipment'?'360-001':'Vodka',unit:kind==='equipment'?'each':'bottle',kind,quantity,condition:'ready',note:'Counted for test'});
test('unknown inventory and overbooked consumables reject; returns credit once',()=>{let s=stock('consumable',null),id=s.inventory[0].id;assert.throws(()=>run(s,'reserve',{eventId:E,itemId:id,quantity:1,...slot}),/Count/);s=stock();id=s.inventory[0].id;s=run(s,'reserve',{eventId:E,itemId:id,quantity:7,...slot});assert.throws(()=>run(s,'reserve',{eventId:F,itemId:id,quantity:4,...slot}),/Not enough/);const r=s.reservations[0].id;s=run(s,'dispatch',{eventId:E,id:r});assert.equal(s.inventory[0].quantity,3);s=run(s,'return',{eventId:E,id:r,returned:2.5,lost:0,condition:'ready',note:''});assert.equal(s.inventory[0].quantity,5.5);assert.equal(s.reservations[0].consumed,4.5);assert.throws(()=>run(s,'return',{eventId:E,id:r,returned:2.5,lost:0,condition:'ready'}),/not awaiting/);});
test('individually tracked equipment rejects overlapping reservations and uncounted loss',()=>{let s=stock('equipment',1),id=s.inventory[0].id;s=run(s,'reserve',{eventId:E,itemId:id,quantity:1,...slot});assert.throws(()=>run(s,'reserve',{eventId:F,itemId:id,quantity:1,...slot}),/already reserved/);assert.throws(()=>run(s,'inventory',{name:'360-001',unit:'each',kind:'equipment',quantity:1,condition:'ready'}),/already exists/);s=run(s,'dispatch',{eventId:E,id:s.reservations[0].id});assert.throws(()=>run(s,'return',{eventId:E,id:s.reservations[0].id,returned:0,lost:0,condition:'ready'}),/Account for every/);s=run(s,'return',{eventId:E,id:s.reservations[0].id,returned:1,lost:0,condition:'cleaning',note:'Clean before next event'});assert.throws(()=>run(s,'reserve',{eventId:F,itemId:id,quantity:1,...slot}),/not ready/);});
test('staff scheduling blocks overlap and snapshots rates',()=>{let s=run(emptyOperations(),'staff',{name:'Test Bartender',role:'Lead',rateCents:5000});const id=s.staff[0].id;s=run(s,'assign',{eventId:E,staffId:id,role:'Lead',plannedHours:8,actualHours:null,...slot});assert.throws(()=>run(s,'assign',{eventId:F,staffId:id,role:'Lead',plannedHours:8,actualHours:null,...slot}),/already assigned/);s=run(s,'staff',{id,name:'Test Bartender',role:'Lead',rateCents:6000});assert.equal(finances(s.events[E]).plannedStaff,40000);});
test('benchmark separates cash, inventory credits and actual event margin',()=>{const e=defaultEvent();e.revenueCents=1600000;e.expenses.forEach(x=>{x.plannedCents=0;x.actualCents=0;});e.expenses[0].actualCents=350000;e.leftoverCents=50000;e.stockUsedCents=0;e.staffingConfirmed=true;e.actualHoursConfirmed=true;const f=finances(e);assert.equal(f.cash,350000);assert.equal(f.consumed,300000);assert.equal(f.profit,1300000);assert.equal(f.margin,81.25);assert.equal(f.budget,320000);e.expenses[1].actualCents=null;assert.equal(finances(e).profit,null);});
test('closeout requires office return, confirmed costs and owner-attributed tasks',()=>{let s=stock();s.events[E]=defaultEvent();s.events[E].owner='Fareed';s.events[E].stage=7;s.events[E].tasks[7].forEach(t=>t.done=true);assert.throws(()=>run(s,'advance',{eventId:E}),/expenses/);s=run(s,'task',{eventId:E,stage:7,index:0,done:true});assert.equal(s.events[E].tasks[7][0].by,actor);assert.equal(s.audit.at(-1).actor,actor);});
test('complete event lifecycle closes only after dispatched equipment returns and financial review',()=>{let s=stock('equipment',1);const e=defaultEvent();s.events[E]=e;e.owner='Fareed';e.revenueCents=1600000;e.leftoverCents=50000;e.stockUsedCents=0;e.staffingConfirmed=true;e.actualHoursConfirmed=true;e.expenses.forEach(x=>{x.plannedCents=0;x.actualCents=0;});e.expenses[0].actualCents=350000;s=run(s,'payment',{eventId:E,kind:'payment',amountCents:1600000,date:'2026-09-10',reference:'TEST settled'});s=run(s,'reserve',{eventId:E,itemId:s.inventory[0].id,quantity:1,...slot});for(let stage=0;stage<8;stage++){for(let index=0;index<2;index++)s=run(s,'task',{eventId:E,stage,index,done:true});if(stage===3)s=run(s,'dispatch',{eventId:E,id:s.reservations[0].id});if(stage===6){assert.throws(()=>run(s,'advance',{eventId:E}),/every load/);s=run(s,'return',{eventId:E,id:s.reservations[0].id,returned:1,lost:0,condition:'charging',note:'Charge before reuse'});}s=run(s,'advance',{eventId:E});}assert.equal(s.events[E].stage,8);assert.equal(finances(s.events[E]).margin,81.25);assert.throws(()=>run(s,'task',{eventId:E,stage:7,index:0,done:false}),/closed/);s=run(s,'reopen',{eventId:E});assert.equal(s.events[E].stage,7);assert.equal(s.events[E].tasks[7][0].done,false);});

test('Barsys team members carry no event labor cost regardless of directory rate',()=>{let s=run(emptyOperations(),'staff',{name:'Team Lead',role:'Barsys team',rateCents:5000,internal:true});const id=s.staff[0].id;assert.equal(s.staff[0].internal,true);s=run(s,'assign',{eventId:E,staffId:id,role:'Lead',plannedHours:8,actualHours:null,...slot});assert.equal(s.events[E].staffing[0].rateCents,0);assert.equal(s.events[E].staffing[0].internal,true);assert.equal(finances(s.events[E]).plannedStaff,0);s=run(s,'staff',{id,name:'Team Lead',role:'Barsys team',rateCents:5000,internal:false});s=run(s,'assign',{eventId:F,staffId:id,role:'Lead',plannedHours:2,actualHours:null,start:'2026-10-02T12:00:00Z',end:'2026-10-02T14:00:00Z'});assert.equal(s.events[F].staffing[0].rateCents,5000);});
