import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultPreparation,validatePreparation,preparationSummary} from '../backend/preparation.mjs';
const event={guests:51,menus:['signature'],menuMode:'choose'};
test('equipment rounds up at 25 guests and leaves unapproved supply quantities unset',()=>{const p=defaultPreparation(event);assert.equal(p.machines,3);assert.equal(p.equipment.shakers.quantity,6);assert.equal(p.equipment.ipads.quantity,3);assert.equal(p.equipment.funnels.quantity,3);assert.equal(p.equipment.wipes.quantity,null);const s=preparationSummary(event,p);assert.equal(s.totalDrinks,153);assert.equal(s.complete,true);assert.equal(s.equipment.find(x=>x.id==='funnels').recommendedMax,6);assert.equal(defaultPreparation({...event,guests:50}).machines,2);});
test('ingredient aggregation conserves servings and applies buffer only once',()=>{const e={...event,guests:50},p=defaultPreparation(e);p.drinksPerGuest=2;p.bufferPercent=10;p.recipes.forEach((r,i)=>{r.confirmed=true;r.ingredients=[{name:i%2?'Lime juice':'lime juice',amount:15,unit:'ml'},{name:'Garnish',amount:1,unit:'each'}];});const s=preparationSummary(e,validatePreparation(p,e));assert.equal(s.totalDrinks,110);assert.equal(s.servings.reduce((n,x)=>n+x.count,0),110);assert.equal(s.ingredients.find(x=>x.unit==='ml').amount,1650);assert.equal(s.ingredients.find(x=>x.unit==='each').amount,110);assert.deepEqual(s.refills,{perMachineDrinks:55,min:1,max:1});assert.equal(s.complete,true);p.recipes[0].confirmed=false;assert.equal(preparationSummary(e,p).complete,false);});
test('unmeasured recipes and recommendation requests never produce a complete list',()=>{const p=defaultPreparation(event);p.recipes.forEach(r=>{r.confirmed=false;r.ingredients=[];});p.drinksPerGuest=2;assert.equal(preparationSummary(event,p).ingredients.length,0);assert.equal(preparationSummary(event,p).missing.length,4);p.recipes.forEach(r=>{r.confirmed=true;r.ingredients=[{name:'Water',amount:10,unit:'ml'}];});p.menuConfirmed=false;assert.equal(preparationSummary(event,p).complete,false);p.recipes.forEach(r=>r.share=0);assert.equal(preparationSummary(event,p).complete,false);});
test('invalid preparation, unsafe equipment shortages and unmeasured confirmation rejected',()=>{for(const edit of [p=>p.machines=2,p=>p.equipment.shakers.quantity=1,p=>p.equipment.machines.quantity=8,p=>p.drinksPerGuest=-2,p=>{p.recipes[0].confirmed=true;p.recipes[0].ingredients=[];},p=>p.recipes[0].ingredients=[{name:'Juice',amount:1,unit:'bottle'}],p=>p.equipment.wipes.packed=true,p=>p.recipes.pop()]){const p=defaultPreparation(event);edit(p);assert.throws(()=>validatePreparation(p,event),e=>e.status===422);}});
test('new public recipe drafts require review before shopping totals become complete',()=>{for(const id of ['bean-barrel','zen-juniper','bean-bolt-bitter','vermouth-valley','boisson-non-alcoholic-agave-lover-s-mixlist','the-ultra-records']){const payload={guests:25,menus:[id],menuMode:'choose'},p=defaultPreparation(payload),s=preparationSummary(payload,p);assert.ok(p.recipes.length>=4);assert.ok(p.recipes.every(r=>!r.confirmed&&r.sourceUrl.startsWith('https://barsys.com/recipe/')&&r.reviewNote));assert.equal(s.complete,false);assert.equal(s.costs.totalPurchaseCents,null);assert.match(s.catalogWarnings[0],/360 compatibility/);validatePreparation(p,payload);}});
