import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {defaultProposal,validateProposal,proposalView} from '../backend/proposals.mjs';import {calculateProposal,proposalGaps,proposalMarkup} from '../admin/proposal-model.js';import {validate,labels,estimate} from '../backend/model.mjs';import {createAPI} from '../backend/api.mjs';import {createStore} from '../backend/store.mjs';
const sample=()=>{const payload=validate({schemaVersion:1,type:'team',guests:25,tier:'signature',menus:['agave','vibrant','signature'],menuMode:'choose',addons:{'extra-hours':{quantity:1,variant:''}},program:'single',frequency:'exploring',commitment:'exploring',billing:'exploring',beverage:'mixed',serviceHours:3,details:{name:'Test Contact',email:'test@example.com',company:'Proposal Test',phone:'',date:'2099-09-17',startTime:'17:00',timezone:'America/New_York',city:'New York',region:'NY',venue:'Test venue',venueType:'office',budget:'',restrictions:'',notes:'PRIVATE INTERNAL NOTE',venueApproval:'pending',coi:'unsure',glassware:'barsys',contractEntity:'',marketingInterest:'no',photoPreference:'discuss'}});return {id:'00000000-0000-4000-8000-000000000077',createdAt:new Date().toISOString(),version:1,status:'received',owner:'',booking:{confirmed:false,paymentReceived:false},history:[],payload,labels:labels(payload),estimate:estimate(payload)};};
const priced=()=>{const p=defaultProposal(sample());p.billedGuests=20;p.graceGuests=5;p.rateCents=7000;p.taxMilliPercent=8875;p.lines=[{label:'Glassware',quantity:1,unitCents:10000,taxable:true},{label:'Transportation',quantity:1,unitCents:12000,taxable:true}];return p;};
test('proposal prefills wizard details and keeps prices requiring a quote unknown',()=>{const d=sample(),p=defaultProposal(d);assert.equal(p.details.name,'Test Contact');assert.equal(p.details.endTime,'20:00');assert.equal(p.planningGuests,25);assert.equal(p.billedGuests,25);assert.deepEqual(p.menuIds,d.payload.menus);assert.equal(p.rateCents,8500);assert.equal(p.taxMilliPercent,null);assert.ok(p.lines.some(x=>x.unitCents===null));assert.equal(calculateProposal(p).totalCents,null);assert.equal(p.details.terms,'');assert.ok(!JSON.stringify(p).includes('PRIVATE'));assert.equal(p.menuDue,'2099-09-10');assert.equal(p.balanceDue,'2099-09-24');assert.ok(proposalGaps(p).includes('Review pricing'));});
test('DataDome reference arithmetic: taxable subtotal, half-cent tax rounding and exact split',()=>{const p=validateProposal(priced()),c=calculateProposal(p);assert.equal(c.subtotal,162000);assert.equal(c.taxCents,14378);assert.equal(c.totalCents,176378);assert.equal(c.depositCents,88189);assert.equal(c.balanceCents,88189);assert.equal(c.includedGuests,25);p.lines[1].taxable=false;assert.equal(calculateProposal(p).taxCents,13313);p.taxMilliPercent=0;assert.equal(calculateProposal(p).taxCents,0);p.lines[0].unitCents=null;assert.equal(calculateProposal(p).totalCents,null);});
test('unknown zero and odd-cent deposit are distinct',()=>{const p=priced();p.lines=[];p.billedGuests=1;p.rateCents=101;p.taxMilliPercent=0;let c=calculateProposal(p);assert.equal(c.depositCents,51);assert.equal(c.balanceCents,50);p.rateCents=0;assert.equal(calculateProposal(p).totalCents,0);p.depositBps=null;assert.equal(calculateProposal(p).depositCents,null);});
test('rejects invalid money, dates, menus, confirmation types and malicious extra totals',()=>{for(const edit of [p=>p.rateCents=-1,p=>p.rateCents=1.1,p=>p.taxMilliPercent=100001,p=>p.depositBps=10001,p=>p.details.date='2099-02-30',p=>p.details.email='bad',p=>p.menuIds=['fake'],p=>p.menuIds=['agave','agave'],p=>p.confirmed.pricing='true',p=>p.lines[0].quantity=0]){const p=priced();edit(p);assert.throws(()=>validateProposal(p),e=>e.status===422);}const p=priced();p.totalCents=1;assert.equal(validateProposal(p).totalCents,undefined);});
test('proposal HTML escapes input, excludes internal notes and preserves draft and booking separation',()=>{const d=sample(),view=proposalView(d);view.plan.details.company='<img src=x onerror=alert(1)>';const html=proposalMarkup(view.plan,view.menus);assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img src=x'));assert.ok(!html.includes('PRIVATE INTERNAL'));assert.ok(html.includes('DRAFT'));assert.ok(html.includes('does not hold a date'));});
test('saved proposal persists with CAS, auth and audit without mutating inquiry or finances',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'barsys-proposal-'));let store=await createStore({filename:join(dir,'test.sqlite')}),actor='fareed@barsys.com',handler;const doc=sample();await store.insert(doc,'proposal-test','fingerprint');const server=http.createServer((req,res)=>handler(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const auth={clientId:'test',require:async()=>{if(!actor)throw Object.assign(Error('Sign in'),{status:401});return actor;}};handler=createAPI({store,origin,auth});t.after(async()=>{await new Promise(r=>server.close(r));await store.close();await rm(dir,{recursive:true,force:true});});const url=origin+'/api/admin/inquiries/'+doc.id+'/proposal';const get=await(await fetch(url)).json();assert.equal(get.savedAt,null);const before=await store.getOperations();const request=version=>fetch(url,{method:'PATCH',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({version,plan:priced()})});const results=await Promise.all([request(1),request(1)]);assert.deepEqual(results.map(x=>x.status).sort(),[200,409]);const saved=await store.get(doc.id);assert.deepEqual(saved.payload,doc.payload);assert.deepEqual(saved.booking,doc.booking);assert.deepEqual(saved.estimate,doc.estimate);assert.deepEqual(await store.getOperations(),before);assert.equal(saved.history[0].actor,'fareed@barsys.com');await store.close();store=await createStore({filename:join(dir,'test.sqlite')});handler=createAPI({store,origin,auth});const again=await(await fetch(url)).json();assert.equal(again.calculation.totalCents,176378);assert.equal(again.revision,1);actor='crew@barsys.com';assert.equal((await fetch(url)).status,403);assert.equal((await request(2)).status,403);actor=null;assert.equal((await fetch(url)).status,401);
});
