import {escapeHTML as esc} from './proposal-model.js';
const $=s=>document.querySelector(s);let settingsDirty=false;let data,selected,token='',expires=0,busy=false,nextOffset=null,dirty=false;
async function api(path='',method='GET',body){const r=await fetch('/api/admin/email-inquiries'+path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),d=await r.json();if(r.status===401&&!path.includes('sync'))location.href='/admin/login.html';if(!r.ok)throw Error(d.error);return d;}
async function load(more=false){const d=await api(more?'?offset='+nextOffset:'');data=more?{...d,items:[...data.items,...d.items]}:d;if(!settingsDirty)$('#keywords').value=d.settings.keywords.join('\n');nextOffset=d.nextOffset;$('#more').hidden=nextOffset===null;$('#queue').innerHTML=data.items.length?data.items.map((x,i)=>`<button data-mail="${i}">${esc(x.subject||'(No subject)')}<br><small>${esc(x.from)}</small></button>`).join(''):'<p>No imported inquiries yet. Connect Gmail to find matching inquiries.</p>';}
const fieldNames={name:'Client name',email:'Client email',phone:'Phone',company:'Company',date:'Date (leave blank if unknown)',startTime:'Start time (New York)',city:'City',venue:'Venue / floor',restrictions:'Allergies / restrictions',notes:'Internal notes'};
$('#queue').onclick=e=>{const b=e.target.closest('[data-mail]');if(!b)return;if(dirty&&!confirm('Discard the unsaved review and open another email?'))return;selected=data.items[Number(b.dataset.mail)];dirty=false;$('#review').hidden=false;$('#subject').textContent=selected.subject||'(No subject)';$('#from').textContent=selected.from;$('#source').textContent=selected.text;$('#result').textContent='';$('#confirm').checked=false;const p=selected.payload;$('#fields').innerHTML=Object.entries(fieldNames).map(([k,label])=>`<label>${label}<input name="${k}" maxlength="${['notes','restrictions'].includes(k)?2000:254}" type="${k==='date'?'date':k==='startTime'?'time':k==='email'?'email':'text'}" value="${esc(p.details[k])}" ${['name','email','city'].includes(k)?'required':''}></label>`).join('')+`<label>Planning guests<input name="guests" type="number" min="1" max="10000" step="1" required value="${p.guests||''}"></label><label>State / region<select name="region">${['NY','NJ','CT','Other'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Service hours<select name="serviceHours"><option value="">Unknown</option>${Array.from({length:8},(_,i)=>`<option>${i+1}</option>`).join('')}</select></label><label>Package<select name="tier" required><option value="">Choose package after review</option>${data.packages.map(x=>`<option value="${x.id}" ${x.id===p.tier?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`;$('#menus').innerHTML=data.menus.map(x=>`<label class="check"><input type="checkbox" name="menu" value="${x.id}" ${p.menus.includes(x.id)?'checked':''}>${esc(x.name)}</label>`).join('');$('#review').scrollIntoView({behavior:'smooth',block:'start'});};
$('#form').oninput=e=>{dirty=true;if(e.target.id!=='confirm')$('#confirm').checked=false;};
$('#form').onsubmit=async e=>{e.preventDefault();$('#create').disabled=true;try{const f=e.target.elements,p=structuredClone(selected.payload);for(const k of Object.keys(fieldNames))p.details[k]=f[k].value;p.details.region=f.region.value;p.guests=Number(f.guests.value);p.serviceHours=f.serviceHours.value?Number(f.serviceHours.value):null;p.tier=f.tier.value;p.menus=Array.from(document.querySelectorAll('[name="menu"]:checked'),x=>x.value);p.menuMode=p.menus.length?'choose':'recommend';p.addons=p.serviceHours>2?{'extra-hours':{quantity:p.serviceHours-2,variant:''}}:{};const d=await api('/'+selected.messageId+'/create','POST',{payload:p,confirmed:$('#confirm').checked});dirty=false;$('#result').innerHTML=`${d.existing?'This email thread already has an event.':'Event created.'} <a href="/admin/operations.html?event=${encodeURIComponent(d.id)}">Open event →</a>`;}catch(e){$('#result').textContent=e.message;}finally{$('#create').disabled=false;}};
async function sync(){if(busy)return;if(settingsDirty){$('#message').textContent='Save your keyword changes before checking mail.';return;}if(!token||Date.now()>=expires){disconnect();$('#message').textContent='Connect Gmail to authorize another read.';return;}busy=true;$('#sync').disabled=true;try{let pageToken=null,added=0;const settingsVersion=data.settings.version;do{const d=await api('/sync','POST',{accessToken:token,pageToken,settingsVersion});added+=d.added;pageToken=d.nextPageToken;$('#message').textContent='Importing matching messages… '+added+' new drafts.';}while(pageToken&&token);await load();$('#message').textContent=added+' new drafts imported. Review the queue before creating events.';}catch(e){$('#message').textContent=e.message;}finally{busy=false;$('#sync').disabled=!token;}}
function disconnect(){token='';expires=0;$('#automatic').checked=false;$('#disconnect').disabled=true;$('#sync').disabled=true;}
$('#connect').onclick=()=>{if(!data?.clientId||!window.google?.accounts?.oauth2){$('#message').textContent='Google authorization is unavailable. Reload and try again.';return;}google.accounts.oauth2.initTokenClient({client_id:data.clientId,scope:'https://www.googleapis.com/auth/gmail.readonly',include_granted_scopes:false,login_hint:'fareed@barsys.com',callback:r=>{if(r.error||!r.access_token){$('#message').textContent='Gmail connection was not authorized.';return;}token=r.access_token;expires=Date.now()+Number(r.expires_in||3600)*1000;$('#disconnect').disabled=false;$('#sync').disabled=false;sync();},error_callback:()=>{$('#message').textContent='Google authorization did not finish. Try Connect Gmail again.';}}).requestAccessToken();};
$('#disconnect').onclick=()=>{disconnect();$('#message').textContent='Session disconnected. Saved drafts remain. You can revoke Google access in your Google account permissions.';};$('#sync').onclick=sync;$('#more').onclick=()=>load(true).catch(e=>$('#message').textContent=e.message);setInterval(()=>{if($('#automatic').checked&&!document.hidden)sync();},300000);window.addEventListener('beforeunload',e=>{if(dirty||settingsDirty){e.preventDefault();e.returnValue='';}});load().catch(e=>$('#message').textContent=e.message);

$('#keywords').oninput=()=>{settingsDirty=true;$('#keyword-status').textContent='Unsaved keyword changes';};
$('#save-keywords').onclick=async()=>{if(busy){$('#keyword-status').textContent='Wait for the current mail check to finish.';return;}try{const saved=await api('/settings','PATCH',{version:data.settings.version,keywords:$('#keywords').value.split(/\n/).map(x=>x.trim()).filter(Boolean)});data.settings=saved;settingsDirty=false;$('#keywords').value=saved.keywords.join('\n');$('#keyword-status').textContent='Keywords saved. The next check uses these phrases.';}catch(e){$('#keyword-status').textContent=e.message;}};

$('#test-send').onclick=()=>{const button=$('#test-send'),status=$('#send-status');if(!data?.clientId||!window.google?.accounts?.oauth2){status.textContent='Google authorization unavailable. Reload and try again.';return;}button.disabled=true;google.accounts.oauth2.initTokenClient({client_id:data.clientId,scope:'https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/userinfo.email',include_granted_scopes:false,login_hint:'fareed@barsys.com',callback:async r=>{try{if(r.error||!r.access_token)throw Error('Sending was not authorized.');status.textContent='Sending test to Fareed…';await api('/test-send','POST',{accessToken:r.access_token});status.textContent='Gmail accepted the test. Check your inbox and Sent mail. Automatic customer emails remain disabled.';}catch(e){status.textContent=e.message;}finally{button.disabled=false;}},error_callback:()=>{status.textContent='Authorization did not finish.';button.disabled=false;}}).requestAccessToken();};
