import {escapeHTML as esc} from './proposal-model.js';
const $=s=>document.querySelector(s),id=new URLSearchParams(location.search).get('event');let saved,dirty=false,reviewed=false;
async function api(method='GET',body){const r=await fetch('/api/admin/inquiries/'+id+'/details',{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),d=await r.json();if(r.status===401){location.replace('/admin/login.html');throw Error('Sign in required.');}if(!r.ok)throw Error(d.error);return d;}
const names={name:'Contact name',email:'Email',phone:'Phone',company:'Company',contractEntity:'Contracting entity',date:'Event date',startTime:'Service starts',timezone:'Timezone',city:'City',region:'State / region',venue:'Venue and floor',restrictions:'Allergies / restrictions',notes:'Internal event notes'};
function render(){const p=saved.payload;$('#fields').innerHTML=saved.editableDetails.map(k=>`<label>${names[k]}${['notes','restrictions'].includes(k)?`<textarea name="${k}" maxlength="2000">${esc(p.details[k])}</textarea>`:k==='region'?`<select name="region">${['NY','NJ','CT','Other'].map(x=>`<option ${x===p.details[k]?'selected':''}>${x}</option>`).join('')}</select>`:`<input name="${k}" value="${esc(p.details[k])}" maxlength="254" ${k==='timezone'?'readonly':''} type="${k==='date'?'date':k==='startTime'?'time':k==='email'?'email':'text'}">`}</label>`).join('')+`<label>Planning guests<input name="guests" type="number" min="1" max="10000" step="1" required value="${p.guests}"></label><label>Service hours<select name="serviceHours"><option value="">Undecided</option>${Array.from({length:8},(_,i)=>`<option value="${i+1}" ${p.serviceHours===i+1?'selected':''}>${i+1}</option>`).join('')}</select></label><label>Package<select name="tier">${saved.packages.map(x=>`<option value="${x.id}" ${p.tier===x.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`;$('#menus').innerHTML=saved.menus.map(m=>`<label class="check"><input type="checkbox" name="menu" value="${m.id}" ${p.menus.includes(m.id)?'checked':''}>${esc(m.name)}</label>`).join('');$('#edit-form').hidden=false;$('#accepted-note').textContent=saved.accepted?'An accepted proposal is on record. Scope edits require a revised proposal before using profit figures or advancing the event.':'';}
function collect(){const f=$('#edit-form'),p=structuredClone(saved.payload);for(const k of saved.editableDetails)p.details[k]=f.elements[k].value;p.guests=Number(f.elements.guests.value);p.serviceHours=f.elements.serviceHours.value===''?null:Number(f.elements.serviceHours.value);p.tier=f.elements.tier.value;const chosen=Array.from(document.querySelectorAll('[name="menu"]:checked'),x=>x.value);p.menus=[...saved.payload.menus.filter(x=>chosen.includes(x)),...chosen.filter(x=>!saved.payload.menus.includes(x))];return p;}
$('#edit-form').oninput=e=>{if(e.target.id==='ack')return;dirty=true;reviewed=false;$('#save').disabled=true;$('#save').hidden=true;$('#ack-row').hidden=true;$('#ack').checked=false;$('#impact').hidden=true;};
$('#review').onclick=async()=>{try{const impact=await api('POST',{version:saved.version,operationsVersion:saved.operationsVersion,payload:collect()});$('#impact').hidden=false;$('#impact').innerHTML=`<h3>${impact.changed.length?'Changes: '+esc(impact.changed.join(', ')):'No changes'}</h3>${impact.warnings.map(x=>'<p>'+esc(x)+'</p>').join('')}${impact.blockers.map(x=>'<p><b>'+esc(x)+'</b></p>').join('')}`;reviewed=impact.changed.length>0&&!impact.blockers.length;$('#ack-row').hidden=$('#save').hidden=!reviewed;$('#message').textContent='';}catch(e){$('#message').textContent=e.message;}};
$('#ack').onchange=()=>$('#save').disabled=!reviewed||!$('#ack').checked;
$('#edit-form').onsubmit=async e=>{e.preventDefault();if(!reviewed||!$('#ack').checked)return;$('#save').disabled=true;try{await api('PATCH',{version:saved.version,operationsVersion:saved.operationsVersion,payload:collect(),acknowledgeImpact:true});dirty=false;location.href='/admin/operations.html?event='+id;}catch(e){$('#message').textContent=e.message;$('#save').disabled=false;}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{if(!/^[a-f0-9-]{36}$/.test(id||''))throw Error('Open an event first.');$('#back').href='/admin/operations.html?event='+id;saved=await api();render();}catch(e){$('#message').textContent=e.message;}})();
