'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=new URLSearchParams(location.search).get('event');let saved,event,dirty=false;
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json'}});const d=await r.json();if(r.status===401){location.replace('/admin/login.html');throw Error('Sign-in required.');}if(!r.ok)throw Error(d.error||'Request failed.');return d;}
const dollars=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
function summary(data){const s=data.summary;$('#capacity').textContent=s.totalDrinks===null?'Enter a drinks-per-guest estimate to calculate ingredients and refills.':`${s.totalDrinks} planned drinks including buffer. About ${s.refills.perMachineDrinks} drinks per machine; ${s.refills.min}–${s.refills.max} refills per machine after the initial fill. Minimum ${s.minimumMachines} machines.`;$('#completeness').textContent=s.complete?'Measured estimate for the saved drink mix. Check stock, pack sizes, ice and service supplies separately.':'INCOMPLETE — '+[!data.plan.menuConfirmed?'Finalize and confirm the event menu first.':'',!data.plan.recipes.length?'No collections selected.':'',s.totalDrinks===null?'Drinks-per-guest estimate is missing.':'',!data.plan.recipes.some(r=>r.share>0)?'At least one recipe needs a positive weight.':'',s.missing.length?`${s.missing.length} recipes need measured ingredients and confirmation. Listed totals cover confirmed recipes only.`:''].filter(Boolean).join(' ');$('#ingredients').innerHTML=s.ingredients.length?`<ul>${s.ingredients.map(x=>`<li><strong>${esc(x.name)}</strong> — ${x.amount.toLocaleString()} ${esc(x.unit)}${x.unit==='ml'?' ('+(x.amount/1000).toLocaleString()+' L)':''}</li>`).join('')}</ul>`:'<p>No ingredient quantities available yet.</p>';$('#packed-count').textContent=`${s.packed} of ${s.equipment.length} checklist items marked packed. Optional and unquantified items stay visible.`;}
function render(data){saved=data;const p=data.plan;$('#menu-confirmed').checked=p.menuConfirmed;$('#drinks').value=p.drinksPerGuest??'';$('#buffer').value=p.bufferPercent;$('#machines').value=p.machines;$('#machines').min=data.summary.minimumMachines;$('#recipes').innerHTML=p.recipes.length?p.recipes.map((r,i)=>`<details class="recipe" data-recipe="${i}"><summary>${esc(r.name)} · ${data.summary.servings[i].count??'—'} servings · ${r.confirmed?'confirmed':'needs recipe'}</summary>${r.reviewNote?`<p class="notice">${esc(r.reviewNote)}</p><p><a href="${esc(r.sourceUrl)}" target="_blank" rel="noopener noreferrer">View published recipe ↗</a></p>`:''}<label>Drink name<input data-name maxlength="150" required value="${esc(r.name)}"></label><label>Demand weight<input data-share type="number" min="0" max="100" step="0.1" required value="${r.share}"></label><label>Measured ingredients<textarea data-ingredients placeholder="Ingredient name | amount | ml">${esc(r.ingredients.map(x=>`${x.name} | ${x.amount} | ${x.unit}`).join('\n'))}</textarea></label><label class="check"><input type="checkbox" data-confirmed ${r.confirmed?'checked':''}>Recipe ingredients and measurements confirmed</label></details>`).join(''):'<p>No selected collections. Finalize the client menu before ingredient planning.</p>';$('#equipment').innerHTML=data.summary.equipment.map(e=>`<div class="equipment-row" data-equipment="${e.id}"><label>${esc(e.name)}${e.minimum===null?' — quantity to confirm':` — minimum ${e.minimum}${e.recommendedMax>e.minimum?' / up to '+e.recommendedMax+' recommended':''}`}<input data-quantity type="number" min="${e.minimum??0}" max="10000" step="1" value="${e.quantity??''}" ${e.id==='machines'?'readonly':''}></label><label class="check"><input type="checkbox" data-packed ${e.packed?'checked':''}>Packed</label><label>Notes<input data-notes maxlength="300" value="${esc(e.notes)}"></label></div>`).join('');summary(data);renderCosts(data);dirty=false;$('#download-prep').disabled=false;}
function collect(){const p=structuredClone(saved.plan);p.menuConfirmed=$('#menu-confirmed').checked;p.drinksPerGuest=$('#drinks').value===''?null:Number($('#drinks').value);p.bufferPercent=Number($('#buffer').value);p.machines=Number($('#machines').value);for(const el of document.querySelectorAll('[data-recipe]')){const r=p.recipes[Number(el.dataset.recipe)];r.name=el.querySelector('[data-name]').value;r.share=Number(el.querySelector('[data-share]').value);r.confirmed=el.querySelector('[data-confirmed]').checked;r.ingredients=el.querySelector('[data-ingredients]').value.split('\n').filter(x=>x.trim()).map(line=>{const parts=line.split('|').map(x=>x.trim());if(parts.length!==3)throw Error('Ingredient lines must use name | amount | unit.');return {name:parts[0],amount:Number(parts[1]),unit:parts[2].toLowerCase()};});}for(const el of document.querySelectorAll('[data-equipment]')){const q=el.querySelector('[data-quantity]').value;p.equipment[el.dataset.equipment]={quantity:q===''?null:Number(q),packed:el.querySelector('[data-packed]').checked,notes:el.querySelector('[data-notes]').value};}p.costOverrides=[...(p.costOverrides||[]).filter(x=>!saved.summary.costs.rows.some(r=>r.name.toLowerCase()===x.name.toLowerCase()&&r.unit===x.unit))];for(const el of document.querySelectorAll('[data-cost]')){const row=saved.summary.costs.rows[Number(el.dataset.cost)],pack=el.querySelector('[data-pack]').value,price=el.querySelector('[data-price]').value,supplier=el.querySelector('[data-supplier]').value.trim();if(!pack&&!price&&!supplier)continue;if(!pack||!price||!supplier)throw Error('Complete all three price fields for '+row.name+', or clear all three to use the reference.');p.costOverrides.push({name:row.name,unit:row.unit,packAmount:Number(pack),priceCents:Math.round(Number(price)*100),supplier});}return p;}
$('#prep-form').addEventListener('input',e=>{dirty=true;$('#download-prep').disabled=true;$('#save-state').textContent='Unsaved changes. Save to recalculate ingredient costs, quantities and refills.';if(e.target.matches('[data-quantity]'))e.target.closest('[data-equipment]').querySelector('[data-packed]').checked=false;if(e.target.matches('[data-name],[data-ingredients]'))e.target.closest('[data-recipe]').querySelector('[data-confirmed]').checked=false;});
$('#machines').addEventListener('change',()=>{const n=Number($('#machines').value);for(const e of saved.summary.equipment){if(e.minimum===null)continue;const el=document.querySelector(`[data-equipment="${e.id}"]`),q=el.querySelector('[data-quantity]');const minimum=e.minimum/saved.plan.machines*n;q.min=minimum;q.value=e.id==='machines'?n:Math.max(Number(q.value),minimum);el.querySelector('[data-packed]').checked=false;}});
$('#prep-form').onsubmit=async e=>{e.preventDefault();const button=e.submitter||e.currentTarget.querySelector('button[type=submit]');if(button)button.disabled=true;try{const plan=collect();const data=await api(`/api/admin/inquiries/${id}/preparation`,{method:'PATCH',body:JSON.stringify({version:saved.version,operationsVersion:saved.operationsVersion,plan})});render(data);$('#save-state').textContent='Preparation saved. '+(data.impact?.warnings?.join(' ')||'Ingredient costs, quantities and equipment checklist updated.');}catch(error){$('#save-state').textContent=error.message;}finally{if(button)button.disabled=false;}};
$('#download-prep').onclick=()=>{const blob=new Blob([JSON.stringify({eventId:id,company:event.payload.details.company,guests:event.payload.guests,...saved},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Barsys-preparation-${id}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{if(!/^[a-f0-9-]{36}$/.test(id||''))throw Error('Open an event from the dashboard first.');event=await api('/api/admin/inquiries/'+id);const data=await api(`/api/admin/inquiries/${id}/preparation`);$('#event-context').textContent=`${event.payload.details.company||event.payload.details.name} · ${event.payload.guests} guests · ${event.labels.menus.join(', ')||'Menu undecided'}`;render(data);const workflow=document.createElement('a');workflow.className='prep-link';workflow.href='/admin/operations.html?event='+id;workflow.textContent='Open event workflow →';$('#event-context').after(workflow);$('#prep-form').hidden=false;$('#prep-message').textContent='Saved planning figures are estimates. Equipment ratios supplied by Barsys.';}catch(e){$('#prep-message').textContent=e.message;}})();

function renderCosts(data){
 const c=data.summary.costs;
 $('#cost-status').textContent=(c.complete?'Estimated ingredient totals':'INCOMPLETE — known ingredient subtotals')+`: ${dollars(c.knownUsedCents)} used · ${dollars(c.knownPurchaseCents)} whole packs. ${c.priceMissing} prices missing; ${c.yieldMissing} pack yields needed; ${c.estimatedRows||0} ingredient rows use estimated yields or budgeting selections. `+(!data.summary.complete?'Recipe/menu planning is also incomplete. ':'')+'Check retailer prices again before purchasing.';
 $('#purchase-packs').innerHTML='<h3>Combined whole-pack purchases</h3><ul>'+c.purchases.map(p=>`<li>${esc(p.product)} — ${p.packs} packs × ${dollars(p.priceCents)} = <strong>${dollars(p.purchaseCents)}</strong> (${esc(p.ingredients.join(', '))})</li>`).join('')+'</ul>';
 $('#mixlist-costs').innerHTML=c.menus.map(m=>`<div class="cost-card"><strong>${esc(m.name)}</strong><span>${m.servings} planned drinks</span><b>${dollars(m.knownUsedCents)} ${m.complete?'estimated ingredient cost':'known subtotal'}</b><small>${m.missing} unpriced recipe ingredients · ${m.unmeasured} unmeasured recipes</small></div>`).join('')||'<p>Select collections before costing.</p>';
 $('#catalog-warnings').textContent=(data.summary.catalogWarnings||[]).join(' ');
 $('#load-recipes').disabled=!data.plan.recipes.some((r,i)=>!r.ingredients.length&&data.recipeDefaults?.[i]?.ingredients.length);
 $('#cost-inputs').innerHTML=c.rows.map((r,i)=>{const o=(data.plan.costOverrides||[]).find(x=>x.name.toLowerCase()===r.name.toLowerCase()&&x.unit===r.unit),p=r.price;return `<details class="recipe" data-cost="${i}"><summary>${esc(r.name)} — ${r.amount.toLocaleString()} ${esc(r.unit)} · ${p?dollars(r.usedCents)+' used / '+dollars(r.purchaseCents)+' if purchased alone':r.reference?'PACK YIELD NEEDED':'PRICE NEEDED'}</summary><p>${p?`${r.packs} packs × ${p.packAmount} ${esc(r.unit)} at ${dollars(p.priceCents)} per pack. ${esc(p.source)}${p.supplier?' — '+esc(p.supplier):''}.`:'No calculated cost yet. Enter a product, usable pack yield and price below; garnish counts must be measured.'}</p>${r.reference?`<p>${r.reference.url?`<a href="${esc(r.reference.url)}" target="_blank" rel="noopener noreferrer">View ${esc(r.reference.source||'retailer')} product ↗</a>`:esc(r.reference.source||'Budget allowance')}${r.reference.product?' — '+esc(r.reference.product):''} · ${dollars(r.reference.priceCents)} / ${esc(r.reference.packLabel||r.reference.packAmount+' '+r.unit)} · checked ${esc(r.reference.checkedAt)}. ${esc(r.reference.basis||'Regular bottle price; confirm availability.')}</p>`:''}${r.reference?`<button type="button" data-use-reference="${i}">Use reference price and enter yield</button>`:''}<div class="prep-grid"><label>Supplier / product override<input data-supplier maxlength="200" value="${esc(o?.supplier||'')}" placeholder="Supplier and exact product"></label><label>Usable yield per purchased pack (${esc(r.unit)})<input data-pack type="number" min="0.001" max="100000" step="any" value="${o?.packAmount??''}"></label><label>Price per pack (USD)<input data-price type="number" min="0" max="100000" step="0.01" value="${o?(o.priceCents/100).toFixed(2):''}"></label></div></details>`;}).join('')||'<p>Load or confirm measured recipes, then save to generate ingredient price fields.</p>';
}
$('#load-recipes').onclick=()=>{try{const plan=collect();let count=0;plan.recipes=plan.recipes.map((r,i)=>{const source=saved.recipeDefaults?.[i];if(r.ingredients.length||!source?.ingredients.length)return r;count++;return {...structuredClone(source),share:r.share};});const previous=saved;render({...saved,plan});saved={...previous,plan};dirty=true;$('#download-prep').disabled=true;$('#save-state').textContent=`${count} empty recipes filled from the CMS snapshot. Save preparation to calculate quantities and costs.`;}catch(e){$('#save-state').textContent=e.message;}};

$('#cost-inputs').addEventListener('click',e=>{const button=e.target.closest('[data-use-reference]');if(!button)return;const r=saved.summary.costs.rows[Number(button.dataset.useReference)],el=button.closest('[data-cost]'),p=r.reference;el.querySelector('[data-supplier]').value=(p.source+' / '+p.product).slice(0,200);el.querySelector('[data-price]').value=(p.priceCents/100).toFixed(2);el.querySelector('[data-pack]').value=p.packAmount??'';el.querySelector('[data-pack]').focus();el.querySelector('[data-pack]').dispatchEvent(new Event('input',{bubbles:true}));});
