import {detailFields,confirmations,calculateProposal,proposalGaps,proposalMarkup,money,escapeHTML as esc} from './proposal-model.js';
import {customerInquiryLabel,customerInquirySlug} from './inquiry-label.js';
const labelFor=(p,rev)=>customerInquiryLabel({payload:{details:{company:p.details.company,email:p.details.email,date:p.details.date}}})+' · Rev '+rev;
const slugFor=p=>customerInquirySlug({payload:{details:{company:p.details.company,email:p.details.email,date:p.details.date}}});
const $=s=>document.querySelector(s),id=new URLSearchParams(location.search).get('event');let data,plan,step=0,dirty=false,allFields=false,busy=false;
async function api(method='GET',body){const r=await fetch(`/api/admin/inquiries/${id}/proposal`,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(r.status===401){location.replace('/admin/login.html?next='+encodeURIComponent(location.pathname+location.search));throw Error('Sign in required.');}if(!r.ok)throw Error(d.error||'Unable to load proposal.');return d;}
const input=(key,label,value,{type='text',scale=1,wide=false,max=254}={})=>`<label class="${wide?'wide ':''}${value===''||value===null?'needs-value':''}" data-field="${key}" ${key.startsWith('details.')&&value&&!allFields&&!['scope','terms'].includes(key.slice(8))?'hidden':''}>${esc(label)}${type==='textarea'?`<textarea data-key="${key}" maxlength="${max}">${esc(value)}</textarea>`:`<input data-key="${key}" type="${type}" value="${esc(value===null?'':typeof value==='number'?value/scale:value)}" ${type==='number'?`min="0" step="${scale===1000?'0.001':scale===100?'0.01':'1'}" data-scale="${scale}"`:`maxlength="${max}"`}>`}<span class="field-origin">${value===''||value===null?'To confirm':key.startsWith('details.')?'Prefilled · editable':'Proposal value · editable'}</span></label>`;
function draw(){
 const d=plan.details;$('#accepted-history').hidden=!data.latestAcceptance;if(data.latestAcceptance){const a=data.latestAcceptance;$('#accepted-summary').textContent='View accepted proposal revision '+a.revision;$('#accepted-evidence').textContent='Recorded '+a.at+' by '+a.by+' · '+a.reference;$('#accepted-preview').innerHTML=proposalMarkup(a.plan,a.menus||data.menus,{draft:false,number:labelFor(a.plan,a.revision),savedAt:a.at});}$('#details-fields').innerHTML=detailFields.filter(([k])=>!['scope','terms'].includes(k)).map(([k,label])=>input('details.'+k,label,d[k],{type:k==='date'?'date':k==='email'?'email':['startTime','endTime','loadIn','departure'].includes(k)?'time':k==='restrictions'?'textarea':'text',wide:['venue','restrictions'].includes(k),max:k==='restrictions'?2000:254})).join('');
 $('#guest-fields').innerHTML=[['planningGuests','Planning guests'],['billedGuests','Billable guests'],['graceGuests','Complimentary guests'],['machines','360 machines']].map(([k,l])=>input(k,l,plan[k],{type:'number'})).join('');
 $('#menu-options').innerHTML=data.menus.map(m=>`<label class="check"><input type="checkbox" data-menu="${m.id}" ${plan.menuIds.includes(m.id)?'checked':''}>${esc(m.name)}</label>`).join('');
 $('#pricing-fields').innerHTML=input('rateCents','Price per billed guest (USD)',plan.rateCents,{type:'number',scale:100})+input('taxMilliPercent','Tax rate % — enter 0 only if confirmed',plan.taxMilliPercent,{type:'number',scale:1000})+input('depositBps','Deposit %',plan.depositBps,{type:'number',scale:100})+input('overageCents','Additional guest rate (USD), optional',plan.overageCents,{type:'number',scale:100})+`<label class="check"><input type="checkbox" data-key="packageTaxable" ${plan.packageTaxable?'checked':''}>Package is taxable — review</label>`;
 drawLines();$('#date-fields').innerHTML=[['expires','Offer expires'],['menuDue','Menu sign-off'],['guestDue','Final guests & allergies'],['depositDue','Deposit due'],['balanceDue','Balance due']].map(([k,l])=>input(k,l,plan[k],{type:'date'})).join('');
 $('#scope-fields').innerHTML=['scope','terms'].map(k=>input('details.'+k,k==='scope'?'Included service':'Additional event terms',d[k],{type:'textarea',wide:true,max:6000})).join('');
 $('#review-checks').innerHTML=[['scope','I reviewed inclusions, exclusions and service duration'],['pricing','I reviewed prices, taxable items, totals and payment amounts'],['terms','I reviewed deadlines and proposed service terms']].map(([k,l])=>`<label class="check"><input type="checkbox" data-confirm="${k}">${l}</label>`).join('');
 for(const el of document.querySelectorAll('[data-confirm]'))el.checked=plan.confirmed[el.dataset.confirm];
 $('#source-review-row').hidden=!data.sourceStale;$('#source-notes').textContent=[JSON.stringify(data.source.details,null,2),'Current guests: '+data.source.guests+'; menus: '+data.source.menus.join(', '),data.source.notes.join('\n'),data.source.details.notes,data.source.serviceHours?'Requested service: '+data.source.serviceHours+' hours':'Service duration undecided',data.source.details.photoPreference?'Publicity preference: '+data.source.details.photoPreference+' (not permission)':''].filter(Boolean).join('\n');$('#source-notes').style.whiteSpace='pre-wrap';
 $('#context').textContent=(d.company||d.name||'Event')+' · '+(d.date||'Date to confirm')+' · '+plan.planningGuests+' planned guests';$('#revision').textContent=data.revision?(data.acceptedRevision===data.revision?'Accepted revision ':'Draft revision ')+data.revision:'New draft';update();showStep();
}
function drawLines(){$('#price-lines').innerHTML=plan.lines.map((l,i)=>`<div class="price-line" data-line="${i}"><label>Item<input data-line-key="label" maxlength="150" value="${esc(l.label)}"></label><label>Quantity<input data-line-key="quantity" type="number" min="1" max="10000" step="1" value="${l.quantity}"></label><label>Unit price USD<input data-line-key="unitCents" type="number" min="0" step="0.01" value="${l.unitCents===null?'':l.unitCents/100}" placeholder="Unknown"></label><label class="check tax-check"><input data-line-key="taxable" type="checkbox" ${l.taxable?'checked':''}>Taxable</label><button type="button" class="remove" data-remove="${i}" aria-label="Remove ${esc(l.label)}">Remove</button></div>`).join('');}
function invalidate(keys){for(const k of keys){plan.confirmed[k]=false;const el=document.querySelector(`[data-confirm="${k}"]`);if(el)el.checked=false;}}
function update(){const c=calculateProposal(plan),g=proposalGaps(plan);$('#total').textContent=money(c.totalCents);$('#known').textContent=c.totalCents===null?'Known line items: '+money(c.knownSubtotal)+' · total incomplete':'Proposed price, including entered tax';for(const k of ['subtotal','tax','deposit','balance'])$('#'+k).textContent=money(c[k==='subtotal'?'subtotal':k+'Cents']);$('#gap-count').textContent=g.length?g.length+' items to complete or review':'All proposal checks complete';$('#gaps').innerHTML=g.map(x=>'<li>'+esc(x)+'</li>').join('');$('#readiness').textContent=g.length?'Draft · needs review':'Reviewed · ready to export';$('#saved-state').textContent=dirty?'Unsaved changes':data.savedAt?'Saved '+new Date(data.savedAt).toLocaleString():'Not saved yet';$('#download').disabled=$('#print').disabled=dirty||!data.savedAt||busy;$('#download').textContent=g.length?'Download draft HTML':'Download proposal HTML';$('#preview').innerHTML=proposalMarkup(plan,data.menus,{draft:g.length>0,number:labelFor(plan,data.revision||'new'),savedAt:data.savedAt});$('#acceptance').hidden=!!g.length||dirty||!data.savedAt||data.sourceStale||data.acceptedRevision===data.revision;$('#handoff-values').textContent='Revenue before tax '+money(c.subtotal)+' · Sales tax '+money(c.taxCents)+' · Client total '+money(c.totalCents)+'. Guest count, menu, service schedule and machine allocation transfer from this proposal; preparation must be rechecked.';$('#accept-proposal').hidden=true;$('#handoff-impact').hidden=true;$('#menu-summary').textContent=plan.menuIds.length+' mixlists selected · '+plan.menuIds.map(id=>data.menus.find(m=>m.id===id)?.name).join(', ');}
function showStep(scroll=false){document.querySelectorAll('[data-panel]').forEach(el=>el.hidden=Number(el.dataset.panel)!==step);document.querySelectorAll('[data-step]').forEach(el=>el.setAttribute('aria-current',Number(el.dataset.step)===step?'step':'false'));$('#previous').hidden=step===0;$('#next').hidden=step===2;if(scroll)document.querySelector('.proposal-steps').scrollIntoView({block:'start'});}
$('#proposal-form').addEventListener('input',e=>{
 const el=e.target;
 if(el.dataset.confirm){plan.confirmed[el.dataset.confirm]=el.checked;}
 else if(el.dataset.menu){plan.menuIds=Array.from(document.querySelectorAll('[data-menu]:checked'),x=>x.dataset.menu);invalidate(['menus','scope']);}
 else if(el.dataset.lineKey){const l=plan.lines[Number(el.closest('[data-line]').dataset.line)],k=el.dataset.lineKey;l[k]=k==='taxable'?el.checked:k==='label'?el.value:el.value===''?null:(k==='unitCents'?Math.round(Number(el.value)*100):Number(el.value));invalidate(['pricing']);}
 else if(el.dataset.key){const k=el.dataset.key;let value=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?null:(Number(el.dataset.scale||1)===1?Number(el.value):Math.round(Number(el.value)*Number(el.dataset.scale)))):el.value;if(k.startsWith('details.')){plan.details[k.slice(8)]=value;invalidate([k==='details.scope'?'scope':k==='details.terms'?'terms':'details']);}else{plan[k]=value;invalidate(['pricing',...(['machines','planningGuests','billedGuests','graceGuests'].includes(k)?['details']:[]),...(['expires','menuDue','guestDue','depositDue','balanceDue'].includes(k)?['terms']:[])]);}}
 else return;dirty=true;update();
});
$('#all-fields').onclick=()=>{allFields=!allFields;$('#all-fields').textContent=allFields?'Show missing details only':'Show prefilled details';document.querySelectorAll('#details-fields [data-field]').forEach(el=>{const k=el.dataset.field.slice(8);el.hidden=!allFields&&!!plan.details[k];});};
$('#price-lines').onclick=e=>{const b=e.target.closest('[data-remove]');if(!b)return;plan.lines.splice(Number(b.dataset.remove),1);invalidate(['pricing','scope']);dirty=true;drawLines();update();};
$('#add-line').onclick=()=>{if(plan.lines.length>=30){$('#message').textContent='Maximum 30 price lines.';return;}plan.lines.push({id:'new-'+plan.lines.length,label:'Additional service',quantity:1,unitCents:null,taxable:true});invalidate(['pricing']);dirty=true;drawLines();update();};
for(const el of document.querySelectorAll('[data-step]'))el.onclick=()=>{step=Number(el.dataset.step);showStep(true);};$('#next').onclick=()=>{step=Math.min(2,step+1);showStep(true);};$('#previous').onclick=()=>{step=Math.max(0,step-1);showStep(true);};
$('#proposal-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('#save').disabled=true;try{data=await api('PATCH',{version:data.version,plan,reviewCurrentEvent:$('#source-reviewed').checked});plan=structuredClone(data.plan);dirty=false;draw();$('#message').textContent='Proposal saved. Event revenue, booking and payments unchanged.';}catch(e){$('#message').textContent=e.message;}finally{busy=false;$('#save').disabled=false;update();}};
async function load(){data=await api();plan=structuredClone(data.plan);dirty=false;draw();$('#workspace').hidden=false;$('#message').textContent='';}
$('#reload').onclick=async()=>{if(dirty&&!confirm('Discard your unsaved proposal edits and reload the saved version?'))return;try{await load();}catch(e){$('#message').textContent=e.message;}};
$('#download').onclick=async()=>{try{if(dirty||!data.savedAt)return;const response=await fetch('/admin/proposal.css');if(!response.ok)throw Error('Export styles unavailable.');const css=await response.text(),html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Barsys event proposal</title><style>body{max-width:850px;margin:40px auto;padding:24px;font:15px/1.5 Arial,sans-serif}'+css+'</style></head><body>'+proposalMarkup(plan,data.menus,{draft:proposalGaps(plan).length>0,number:labelFor(plan,data.revision),savedAt:data.savedAt})+'</body></html>';const url=URL.createObjectURL(new Blob([html],{type:'text/html'})),a=document.createElement('a');a.href=url;a.download='Barsys-proposal-'+slugFor(plan)+'-r'+data.revision+'.html';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);$('#message').textContent='Proposal download requested. Review before sharing.';}catch(e){$('#message').textContent=e.message;}};
$('#print').onclick=()=>{if(dirty||!data.savedAt)return;step=2;showStep();window.print();};window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{if(!/^[a-f0-9-]{36}$/.test(id||''))throw Error('Open an event and choose Create proposal.');$('#back').href='/admin/operations.html?event='+id;await load();}catch(e){$('#message').textContent=e.message;}})();

let handoffVersion=null;
async function handoff(previewOnly){const r=await fetch('/api/admin/inquiries/'+id+'/accept-proposal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:data.version,operationsVersion:handoffVersion,revision:data.revision,confirmed:$('#acceptance-confirmed').checked,reference:$('#acceptance-reference').value,acknowledgeImpact:!previewOnly,previewOnly})}),d=await r.json();if(!r.ok)throw Error(d.error);return d;}
$('#review-handoff').onclick=async()=>{try{const r=await fetch('/api/admin/inquiries/'+id+'/details'),d=await r.json();if(!r.ok)throw Error(d.error);if(d.version!==data.version)throw Error('Event changed. Reload the proposal before accepting.');handoffVersion=d.operationsVersion;const preview=await handoff(true);$('#handoff-impact').textContent=[...preview.impact.changed.map(x=>'Update '+x),...preview.impact.warnings,'Recorded acceptance does not replace booking checks.'].join(' • ');$('#handoff-impact').hidden=false;$('#accept-proposal').hidden=false;}catch(e){$('#message').textContent=e.message;}};
for(const selector of ['#acceptance-reference','#acceptance-confirmed'])$(selector).addEventListener('input',()=>{$('#accept-proposal').hidden=true;$('#handoff-impact').hidden=true;});
$('#accept-proposal').onclick=async()=>{if(handoffVersion===null)return;$('#accept-proposal').disabled=true;try{await handoff(false);dirty=false;location.href='/admin/operations.html?event='+id;}catch(e){$('#message').textContent=e.message;$('#accept-proposal').disabled=false;}};
