import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import vm from 'node:vm';
const context={window:{}};vm.runInNewContext(readFileSync('config.js','utf8'),context);const c=context.window.BARSYS;
const esc=s=>String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const nav=[['packages','Packages'],['mixlists','Mixlists'],['events','Events'],['about','About'],['contact','Contact'],['faq','FAQ']];
const cards=items=>`<div class="cards">${items.join('')}</div>`;
const card=(title,body,url)=>`<article><h2>${esc(title)}</h2>${body}<a href="${url}">Explore <span aria-hidden="true">↗</span></a></article>`;
const pages=[];
function page(slug,title,description,body){pages.push({slug,title,description});writeFileSync(`site/${slug}.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${esc(title)} | Barsys Happy Hours</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)} | Barsys Happy Hours"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="stylesheet" href="/site/site.css"></head><body><a class="skip" href="#main">Skip to content</a><header><a href="/" aria-label="Barsys home"><img src="/assets/logos/Black_Horizontal.svg" width="156" height="30" alt="Barsys"></a><nav aria-label="Main navigation">${nav.map(([id,label])=>`<a href="/site/${id}.html" ${id===slug?'aria-current="page"':''}>${label}</a>`).join('')}</nav></header><main id="main" tabindex="-1"><p class="eyebrow">BARSYS / HAPPY HOURS / NEW YORK CITY</p><h1>${esc(title)}</h1><p class="intro">${esc(description)}</p>${body}<section class="closing"><h2>Your next gathering starts here.</h2><a class="button" href="/#proposal">Plan my event ↗</a><p>A plan is an inquiry, not a confirmed booking. Availability and final scope require confirmation.</p></section></main><footer><a href="/">Barsys Happy Hours</a><a href="/#privacy-policy">Privacy</a><a href="/#event-terms">Event terms</a><a href="/#accessibility-help">Accessibility</a><span>Barsys Inc. · New York City</span></footer></body></html>`);}
mkdirSync('site',{recursive:true});
page('packages','A package for your kind of gathering.','Compare Classic, Signature and Reserve office happy-hour packages.',cards(Object.entries(c.packages).map(([id,p])=>card(p.name,`<p class="price">$${p.rate}<small> / guest</small></p><p>${esc(p.description)}</p>`,`/site/${id}.html`)))+'<p>Two-hour baseline. Estimates exclude applicable tax and unpriced requests. Final scope and availability are confirmed in your proposal.</p>');
for(const [id,p] of Object.entries(c.packages))page(id,`${p.name} happy hours`,p.description,`<section class="split"><div><p class="price">$${p.rate}<small> / guest</small></p><p>Two-hour baseline · ${c.minGuests}-guest minimum for standard planning</p><p>${esc(p.detail)}</p></div><div><h2>The details</h2><ul>${p.features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul><p>Choose up to ${p.menuLimit} menus. See currently eligible collections after selecting this package in the planner.</p><a href="/#packages">Choose ${esc(p.name)} in the planner ↗</a></div></section><p>Tax, additional hours and unpriced requests are confirmed separately. Larger or unsupported events follow a custom-quote process.</p>`);
page('mixlists','Find your first pour.','Explore the Barsys collection library. Package eligibility and final event menus are confirmed in the planner.',cards(c.menus.map(m=>card(m.name,`<p>${esc(m.description)}</p>`,`/site/mixlist-${m.id}.html`))));
for(const m of c.menus){const a=c.assets[m.image];page(`mixlist-${m.id}`,m.name,m.description,`<section class="split">${a?.local?`<img class="cover" src="/${esc(a.local)}" alt="${esc(m.name)} collection cover" width="720" height="900">`:''}<div><h2>${esc(m.tag||'The collection')}</h2><p>${esc(m.detail||m.flavor||'Final recipes and spirit brands are confirmed with your event team.')}</p>${m.examples?.length?`<h3>Featured drinks</h3><ul>${m.examples.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<p>This library includes collections that may not be available for your package or machine setup. The planner shows current eligibility; this page does not reserve a menu.</p><a href="/#menus">See package-eligible menus ↗</a></div></section>`);}
page('about','Good drinks. Better connections.','Barsys brings an interactive cocktail bar to office gatherings in New York City.',`<section class="split"><div><h2>The office, after hours.</h2><p>Our event service brings together Barsys cocktail machines and bartending, with setup and cleanup included in the approved package scope.</p><p>From a team happy hour to a client gathering, start with the occasion, guest count and venue. We work through the final menu and event details with you.</p></div><div><h2>Plan with people.</h2><p>Contact Fareed at <a href="mailto:${c.email}">${c.email}</a>.</p><p>Barsys Inc.<br>44 W 37th St<br>New York, NY 10018</p></div></section>`);
page('contact','Tell us what you have in mind.','Planning an office happy hour, client gathering or milestone in New York City?',`<section class="split"><div><h2>Start with your event.</h2><p>Use the planner for your date, guest count, package and menu preferences. Your team reviews the details before a booking is confirmed.</p><a class="button" href="/#proposal">Open the event planner ↗</a></div><div><h2>Talk to Fareed.</h2><a href="mailto:${c.email}">${c.email}</a><p>For venue access, custom service areas or a larger gathering, include the location and event details in your inquiry. Service availability requires confirmation.</p></div></section>`);
page('events','A little atmosphere.','Real Barsys event imagery, from the existing collection.',`<img class="wide" src="/assets/curated/posters/nyc-event.jpg" width="1600" height="900" alt="Barsys evening event atmosphere"><section><h2>See the service in motion.</h2><p>Explore the event films and photography on our main page. Imagery illustrates the atmosphere; venue, decor, food and specific recipes are not implied package inclusions.</p><a href="/#experience">Explore the experience ↗</a></section>`);
page('faq','Before the first cheers.','Answers to the essentials of planning your Barsys event.',[['What is included?','Packages use a two-hour service baseline. Review each package for inclusions; final scope is confirmed in your proposal.'],['Which menus can I choose?','Select your package in the planner to see current eligible mixlists. Final recipes and spirit brands require confirmation.'],['Does an inquiry hold my date?','No. Sending an inquiry does not reserve a date, sign an agreement or take payment.'],['Can you handle a custom event?','Submit your guest count, venue and requirements. Events outside the standard planning range are reviewed as custom quotes.'],['How do cancellations work?','Deposit, cancellation and rescheduling terms are confirmed in your event proposal and agreement.'],['Where do you operate?','This site focuses on New York City office gatherings. Ask the team to confirm availability for your exact venue.']].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join(''));
writeFileSync('site/pages.json',JSON.stringify(pages,null,2)+'\n');
console.log(`Built ${pages.length} public content pages; indexing remains disabled.`);
