import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import vm from 'node:vm';
const context={window:{}};vm.runInNewContext(readFileSync('config.js','utf8'),context);const c=context.window.BARSYS;
const esc=s=>String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const nav=[['packages','Packages'],['mixlists','Mixlists'],['technology','Technology'],['about','About'],['contact','Contact'],['faq','FAQ']];
const cards=items=>`<div class="cards">${items.join('')}</div>`;
const card=(title,body,url)=>`<article><h2>${esc(title)}</h2>${body}<a href="${url}">Explore <span aria-hidden="true">↗</span></a></article>`;
const pages=[];
const clip=(text,max=160)=>{text=String(text).replace(/\s+/g,' ').trim();if(text.length<=max)return text;const cut=text.slice(0,max);const stop=Math.max(cut.lastIndexOf('. '),cut.lastIndexOf('; '));return (stop>0?cut.slice(0,stop+1):cut.replace(/\s+\S*$/,'')).trim();};
const describe=(...parts)=>clip(parts.filter(Boolean).join(' '));
function page(slug,title,description,body,image=null,intro=description){pages.push({slug,title,description,...(image?{image}:{})});writeFileSync(`site/${slug}.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${esc(title)} | Barsys Happy Hours</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)} | Barsys Happy Hours"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="icon" href="/assets/brand-mark.png"><meta name="theme-color" content="#ffffff"><link rel="stylesheet" href="/site/site.css"></head><body><a class="skip" href="#main">Skip to content</a><header><a href="/" aria-label="Barsys home"><img src="/assets/logos/Black_Horizontal.svg" width="156" height="30" alt="Barsys"></a><nav aria-label="Main navigation">${nav.map(([id,label])=>`<a href="/site/${id}.html" ${id===slug?'aria-current="page"':''}>${label}</a>`).join('')}</nav></header><main id="main" tabindex="-1"><p class="eyebrow">BARSYS / HAPPY HOURS / NEW YORK CITY</p><h1>${esc(title)}</h1><p class="intro">${esc(intro)}</p>${body}<section class="closing"><h2>Your next gathering starts here.</h2><a class="button" href="/#proposal">Plan my event ↗</a><p>An inquiry is not a booking.</p></section></main><footer><a href="/">Barsys Happy Hours</a><a href="/#privacy-policy">Privacy</a><a href="/#event-terms">Event terms</a><a href="/#accessibility-help">Accessibility</a><span>Barsys Inc. · New York City</span></footer></body></html>`);}
mkdirSync('site',{recursive:true});
page('packages','A package for your kind of gathering.','Compare the Classic, Signature and Reserve office happy-hour packages from Barsys: per-guest rates, a two-hour service baseline and what each package includes.',cards(Object.entries(c.packages).map(([id,p])=>card(p.name,`<p class="price">$${p.rate}<small> / guest</small></p><p>${esc(p.description)}</p>`,`/site/${id}.html`)))+'<p>Two-hour baseline. Tax and extras are confirmed in your proposal.</p>');
for(const [id,p] of Object.entries(c.packages))page(id,`${p.name} happy hours`,describe(p.description,p.detail,`From $${p.rate} per guest for New York City office events.`),`<section class="split"><div><p class="price">$${p.rate}<small> / guest</small></p><p>Two-hour baseline · ${c.minGuests}-guest minimum for standard planning</p><p>${esc(p.detail)}</p></div><div><h2>The details</h2><ul>${p.features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul><p>Up to ${p.menuLimit} menus. Tax, extra hours and unpriced requests are confirmed in your proposal.</p><a href="/#packages">Choose ${esc(p.name)} in the planner ↗</a></div></section>`,null,p.description);
page('mixlists','Find your first pour.','Explore the Barsys mixlist library for office happy hours in New York City. Package eligibility and final event menus are confirmed in the planner.',cards(c.menus.map(m=>card(m.name,`<p>${esc(m.description)}</p>`,`/site/mixlist-${m.id}.html`))));
for(const m of c.menus){const a=c.assets[m.image];page(`mixlist-${m.id}`,m.name,describe(m.description,m.detail||m.flavor,`A Barsys mixlist for office happy hours and events in New York City.`),`<section class="split">${a?.local?`<img class="cover" src="/${esc(a.local)}" alt="${esc(m.name)} collection cover" width="720" height="900">`:''}<div><h2>${esc(m.tag||'The collection')}</h2><p>${esc(((x)=>x&&x.startsWith(m.description)?x.slice(m.description.length).trim():x)([m.detail,m.flavor].find(x=>x&&x!==m.description))||'Final recipes and spirit brands are confirmed with your event team.')}</p>${m.examples?.length?`<h3>Featured drinks</h3><ul>${m.examples.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}<p>Package eligibility is shown in the planner.</p><a href="/#menus">See package-eligible menus ↗</a></div></section>`,a?.local?`/${a.local}`:null,m.description);}
page('about','Good drinks. Better connections.','Barsys brings an interactive cocktail bar to office gatherings in New York City.',`<section class="split"><div><h2>The office, after hours.</h2><p>Barsys cocktail machines, bartenders, setup and cleanup, brought to your office.</p><p>From a team happy hour to a client gathering, start with the occasion, guest count and venue. We work out the menu and details with you.</p></div><div><h2>Plan with people.</h2><p>Contact Fareed at <a href="mailto:${c.email}">${c.email}</a>.</p><p>Barsys Inc.<br>44 W 37th St<br>New York, NY 10018</p></div></section>`);
page('contact','Tell us what you have in mind.','Planning an office happy hour, client gathering or milestone in New York City?',`<section><h2>Talk to Fareed.</h2><a href="mailto:${c.email}">${c.email}</a><p>Include the date, guest count and venue if you have them. We come back with availability and next steps.</p></section>`);
page('technology','The bar we bring.','The Barsys 360 cocktail machine and the Shaker Pro smart shaker: what they are, how they pour, and how they work together at a Barsys happy hour.',
`<section class="split"><img class="cover" src="/assets/tech/360-hero-hd.jpg" alt="The Barsys 360 cocktail machine with a glass centered under the dispensing ring" width="1400" height="788"><div><p class="eyebrow">BARSYS 360</p><h2>The countertop cocktail machine.</h2><p>Six insulated 25 oz canisters hold 152 oz of spirits, fresh juice and mixers, cold for six hours without refrigeration. Every measure is calibrated to a tenth of an ounce, so the fortieth pour matches the first.</p><ul><li>No plumbing, no compressor, one outlet</li><li>Pairs with the Barsys app over Bluetooth 5.0 (iOS and Android)</li><li>2,000+ classics, plus menus composed by Barbot, the Barsys AI</li><li>Any standard glass, centered under the ring</li><li>44 × 20 × 43 cm, about 10 lbs</li></ul><a href="https://360.barsys.com/" rel="noopener" target="_blank">More on the 360 ↗</a></div></section>
<section class="split"><div><p class="eyebrow">HOW IT POURS</p><h2>One evening. Four moves.</h2><ul><li><strong>Pair it.</strong> Plug in and pair with the free Barsys app.</li><li><strong>Pick the drink.</strong> Guests choose from the event menu on the tablet.</li><li><strong>Load the bar.</strong> Spirits, juice and mixers go into the canisters.</li><li><strong>It pours.</strong> Every measure exact; the bartender garnishes and serves.</li></ul></div><img class="cover" src="/assets/tech/360-dsc5986.jpg" alt="Close view of the Barsys 360 pouring into a glass" width="1400" height="931"></section>
<section class="split"><img class="cover" src="/assets/tech/sp-instrument-light.jpg" alt="The Shaker Pro smart cocktail shaker with its illuminated base" width="1400" height="933"><div><p class="eyebrow">SHAKER PRO</p><h2>The shaker that lights the way.</h2><p>Pick a recipe in the Barsys AI app, pour until the light says stop, then shake and serve. Accurate to under a milliliter, about 1⁄30 oz.</p><ul><li>Light-guided pour signals: start, slow, stop</li><li>Removable tin, balanced weight, USB-C fast charge</li><li>Bluetooth 5.1, free Barsys AI app on iOS and Android</li><li>1,965 crafted recipes, plus any drink Barbot builds on demand</li><li>Tin rinses like a classic shaker; the electronics stay dry</li></ul><a href="https://shakerpro.barsys.com/" rel="noopener" target="_blank">More on the Shaker Pro ↗</a></div></section>
<section class="split"><div><p class="eyebrow">AT YOUR EVENT</p><h2>Machines pour. People host.</h2><p>A Barsys happy hour pairs 360s on the bar with Shaker Pro stations for the bartenders. Guests pick a drink on the tablet, the 360 pours it exactly, and the team shakes, garnishes and hands it over. Zero-proof menus run on the same machines.</p><p>The Barsys team brings, sets up and takes down everything: machines, tablets, ingredients, ice and glassware as agreed in your proposal.</p></div><img class="cover" src="/assets/tech/sp-served-light.jpg" alt="A finished cocktail served beside the Shaker Pro" width="1400" height="933"></section>`,
'/assets/tech/360-hero-hd.jpg','The Barsys 360 cocktail machine and the Shaker Pro smart shaker, and how they work together at your happy hour.');
page('faq','Before the first cheers.','Answers to the essentials of planning a Barsys office happy hour: inclusions, menus, dates, custom events and cancellations.',[['What is included?','Packages use a two-hour service baseline. Review each package for inclusions; final scope is confirmed in your proposal.'],['Which menus can I choose?','Select your package in the planner to see current eligible mixlists. Final recipes and spirit brands require confirmation.'],['Does an inquiry hold my date?','No. Sending an inquiry does not reserve a date, sign an agreement or take payment.'],['Can you handle a custom event?','Submit your guest count, venue and requirements. Events outside the standard planning range are reviewed as custom quotes.'],['How do cancellations work?','Deposit, cancellation and rescheduling terms are confirmed in your event proposal and agreement.'],['Where do you operate?','This site focuses on New York City office gatherings. Ask the team to confirm availability for your exact venue.']].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join(''));
writeFileSync('site/pages.json',JSON.stringify(pages,null,2)+'\n');
console.log(`Built ${pages.length} public content pages; indexing remains disabled.`);
